### ISSUE TITLE
Use History API to close the mmenu using back button

### ISSUE THREAD

**Issue by chrisblakley** [BeSite/jQuery.mmenu#158]
Not sure if this is the best place for it, but maybe it'll inspire someone else. Here's what I've been doing to allow the mmenu to be closed using the back button. Maybe this would be more of an idea for experimental documentation rather than building something into core. Who knows?

[You can see it in action for the mobile viewport sizes here.](http://gearside.com/nebula/)

```js
jQuery("#selector").mmenu().on('opened.mm', function(){
	history.replaceState(null, document.title, location);
	history.pushState(null, document.title, location);
});

if (window.history && window.history.pushState) {
	window.addEventListener("popstate", function(e) {
		if ( jQuery('html.mm-opened').is('*') ) {
			jQuery(".mm-menu").trigger("close.mm");
			e.stopPropagation();
		}
	}, false);
}
```

**Comment by flashtopia** [comment]
The problem with this approach is that the URL does not change.  It would be nice if MM menu fully supported HTML History with routing to update the url based on menu item.  It would also be great if based on the URL it could position the menu to the correct level, and support back button.

**Comment by FrDH** [comment]
Just to let you know, the new version (coming soon) ships with an add-on called "backButton" :-)

**Comment by chrisblakley** [comment]
So glad to hear that! Thanks for the heads-up!
