### ISSUE TITLE
Show Search Result Child Menus

### ISSUE THREAD

**Issue by krherzog** [BeSite/jQuery.mmenu#165]
Take the following structure
<ul>
  <li><a href="http://home">Home</a></li>
  <li>
     <span>Products</span>
    <ul>
      <li><a href="http://loc1">Item 1</a></li>
      <li><a href="http://loc2">Item 2</a></li>
    </ul>
  </li>
</ul>

When using the search searchfield add-on and setting the showLinksOnly option to false, if the user types in "Products", the Products span is the only item shown, but it loses it's ability to be clicked on to view the items in its submenu.  It seems odd to filter to it but not be able to drill into it.

Not sure if this by design and therefore a feature request.?.

**Comment by FrDH** [comment]
Happy to inform you this behavior will be available by default in the next version.
