### ISSUE TITLE
Disable the "Page Scroll" in Chrome

### ISSUE THREAD

**Issue by osushil** [BeSite/jQuery.mmenu#236]
When the mmenu is opened, (in Chrome Browser), we can scroll the page (mm-page). I don't know if it should be disabled or allowed to perform the scroll. I checked it in the "Firefox" and the "IE" browsers, I could not scroll the pages in them.

**Comment by FrDH** [comment]
I don't think there is much that can be done about how Chrome interprets the combination of CSS.
Like I said, there isn't an absolute solution to prevent it that'll work on all browsers.
A fix for Chrome will probably introduce worse issues on other browsers.

If you do find a solution that doesn't break on other browsers, please let me know.

**Comment by osushil** [comment]
I added "mm-page" CSS "position: fixed !important", this solves the problem to avoid Scrolling.
