### ISSUE TITLE
SimplePie newsblocks.inc.php stops jQuery.mmenu from showing menu on click

### ISSUE THREAD

**Issue by pcxdmb** [BeSite/jQuery.mmenu#249]
Hi, I am completely out of my depth here. 

I have recently integrated the latest jQuery.mmenu download into a website, in which I am using SimplePie version 1.1.3 with newsblocks.inc.php version 2.0, to make an RSS feed aggregator. 

I'm using JQuery v1.10.1 and jquery.mmenu.min.all.js with jquery.mmenu.all.css.

The menu works fine for all pages except the one page that uses newsblocks.inc.php and simplepie.inc. On this page, when clicking the link at:

div class="header_menu"
a href="#menu" /a Demo
/div

which usually opens the menu, I just get #menu appended onto the page address in the browser address bar and nothing happens with the menu (it stays hidden). 

jquery.mmenu.debugger.js doesn't report any errors.

Has anyone seen this before? Have any idea of a work around?

I am completely scratching my head. My knowledge of JS is poor so delving into  jquery.mmenu.min.all.js is proving very difficult.

Any help would be be much appreciated.

Cheers,

Dan.

**Comment by FrDH** [comment]
Don't unbind the click event from the body...
If that isn't an option, I guess you could try to fire the mmenu plugin after all other scripts. Maybe even onWindowLoad instead of onDocumentReady.
