### ISSUE TITLE
Menu Stops Working on SPA using Angular

### ISSUE THREAD

**Issue by rsigmond** [BeSite/jQuery.mmenu#256]
All,

I am working on a project and we have implemented the jQuery mmenu and have come across an issue that we are unable to resolve.  The issue presents itself on after we scroll to the bottom of a page that has a lot of content.  When we scroll back to the top of the page and attempt to show/hide the menu it stops responding and we have to refresh the page.  Not optimal.

Can you point us in a direction that will help resolve this issue?

Randy Sigmond

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
Otherwise I'm going to close this issue.

**Comment by rsigmond** [comment]
Fred,

Thank for your response, you can close this issue. 

Thank you,

Randy Sigmond
U.S. Department of Defense
Defense Contract Audit Agency, HQ
Ph: 703.767.0221
randy.sigmond@dcaa.mil





-----Original Message-----
