### ISSUE TITLE
Is there a way to stop the text from being cut off in the menu?

### ISSUE THREAD

**Issue by KonradPZuse** [BeSite/jQuery.mmenu#259]
Hello all,

I have started to populate my menu, but have noticed some list items  are too long and get cut off from the menu.  I was hoping that the menu would automatically resize, but on default it doesn't seem ot be the case.  Is there a way to make the menu bigger for larger list items?

Thanks!

**Comment by FrDH** [comment]
In the next version, there'll be an extension for this.
