### ISSUE TITLE
Close the menu on mobile Safari (ios) every time a link is fired.

### ISSUE THREAD

**Issue by savox84** [BeSite/jQuery.mmenu#265]
Hello!

I am having an issue with functionality on Safari browser (mobile version) only.
The mmenu version I use is 4.0.0 version.

I am using the following script to trigger the close function every time a link is fired only if the menu is already opened.

$(document).ready(function() {
    $('a').click(function() {
        if($('#mm-right').hasClass('mm-opened')) {
            $("nav").trigger("close.mm touchstart");
        }
    });
});

The above script is working fine on all devices and browsers apart from IOS devices and only on Safari.

The functionality I am trying to get, is every time a link is fired the menu must close first and then it should navigate to the new page.

Without the above function the mmenu its stays open the the browser redirects.

The touchstart function is working partly as the menu slide 20% in order to close, then the menu stick's and finally the browser opens the new page.

Could you please explain me or guide me to find a solution to this problem.

Best Regards,
savox

**Comment by FrDH** [comment]
Like I said:
> My guess is the browser stops all javascript (and maybe even CSS transitions) when opening a new page. There's not much I can do about that.
