### ISSUE TITLE
Opening (sub-)submenu by clicking it's text

### ISSUE THREAD

**Issue by Egretta** [BeSite/jQuery.mmenu#266]
this hack below working well if submenu involved, but not with sub-submenu. is it possible to make it happen with sub-submenus as well? this topic was first time issued here: https://github.com/BeSite/jQuery.mmenu/issues/84

$("#main-menu").mmenu({
                 "counters": true,
                  "offCanvas": {
                  "position": "right"
               }
})
.on('opened.mm', function() {
        $('.mm-current .mm-subopen', this).each(function() {
            var that = this;
            $(this).next().off('click').on('click', function() {
                $(that).click();
                return false;
            });
        });
});

**Comment by FrDH** [comment]
My first reaction (replacing the A with a SPAN) still is the best, most semantic solution.

**Comment by Egretta** [comment]
i have big reason why i can't replace it:

my client site's multi-level menu is quite big, with lots of categories and sub-categories. it needs to be easy for client to update such menu. right now it is - just write the new category name into field, choose correct parent category and click ok. that's it. but if i replace anchors with spans, client has to start updating it manually, he needs to know html and so. clearly, it's too much for him.

**Comment by Egretta** [comment]
can anybody help with that code? i need it badly. :(

**Comment by FrDH** [comment]
I guess you could also add the classname "mm-fullsubopen" to all the links:
````javascript
$("#menu").mmenu();
$("#menu").find( ".mm-subopen" ).addClass( "mm-fullsubopen" );
````

**Comment by Egretta** [comment]
how the whole code will then look like? like this?

$("#main-menu").mmenu();
$("#main-menu").find( ".mm-subopen" ).addClass( "mm-fullsubopen" );

$("#main-menu").mmenu({
"counters": true,
"offCanvas": {
"position": "right"
}
})
.on('opened.mm', function() {
$('.mm-current .mm-subopen', this).each(function() {
var that = this;
$(this).next().off('click').on('click', function() {
$(that).click();
return false;
});
});
});

**Comment by FrDH** [comment]
No, you don't need to call `mmenu()` twice.

**Comment by Egretta** [comment]
like this?

$("#main-menu").mmenu({
"counters": true,
"offCanvas": {
"position": "right"
}
})

$("#main-menu").find( ".mm-subopen" ).addClass( "mm-fullsubopen" );

.on('opened.mm', function() {
$('.mm-current .mm-subopen', this).each(function() {
var that = this;
$(this).next().off('click').on('click', function() {
$(that).click();
return false;
});
});
});

if not, could you provide a correct code please?

**Comment by FrDH** [comment]
Please keep in mind the GitHub bugtracker is meant for reporting issue with the plugin. It's not a support forum, try sites like stackoverlfow.com for more help with javascript in general.

````javascript
$("#main-menu").mmenu();
$("#main-menu").find( ".mm-subopen" ).addClass( "mm-fullsubopen" );
$("#main-menu").on('opened.mm', function() {
  // ...
});
````

**Comment by Egretta** [comment]
brilliant! thank you!
