### ISSUE TITLE
Duplicating Forms

### ISSUE THREAD

**Issue by andrewrogersroi** [BeSite/jQuery.mmenu#267]
For some reason my forms are being duplicated when I use this plugin. Can someone please let me know what's wrong? Here is my url - http://www.episcopalretirement.com/?hs_preview=r3aKllPT-2286019411

In the footer there should only be one form but it's duplicating for some reason:( The menu is visible when viewing in tablet or phone view. I have inspected the elements in chrome but I don't see any issues in the console. Thanks for any help!

**Comment by FrDH** [comment]
I really doubt if this really has anything to do with the mmenu plugin.
However, I did find you're including the mmenu plugin .js file THREE times, Try removing two of those.
<script type="text/javascript" src="http://info.episcopalretirement.com/hs-fs/hub/237937/file-2287390815-js/jquery.mmenu/jquery.mmenu.min.js"></script>

**Comment by andrewrogersroi** [comment]
Thanks for the advice. I have removed the extra instances of the plugin load. I'll try removing some other javascript to see if it's something else causing the issue.

**Comment by andrewrogersroi** [comment]
Ok. After much trial and error I have found where the issue is. I believe it has something to do with the off -canvas function. When I change the "offCanvas" to false instead of {
                  "position": "right",
                  "zposition": "front"
               }
it stopped duplicating the forms. The only problem is that the mobile menu stops working when I do this. Any thoughts?

**Comment by andrewrogersroi** [comment]
@FrDH I have discovered that this isn't a one off issue. I decided to test this on another HubSpot site to see if I would get different results. For this test I used only the defaults and used the step by step tutorial. Here is the link http://www.cleriti.com/mmenu-testing?hs_preview=Tn_61thy-2308883803
If you scroll all the way down you can see where the form is being overrode and css is being stripped. Here is the code I included:
<script src="http://www.cleriti.com/hs-fs/hub/160303/file-2314844167-js/mmenu/jquery.mmenu.min.all.js"></script>
<link href="http://www.cleriti.com/hs-fs/hub/160303/file-2313311404-css/mmenu/css/jquery.mmenu.all.css" type="text/css" rel="stylesheet" />
<script type="text/javascript">
   $(document).ready(function() {
      $("#my-menu").mmenu();
   });
</script>
------ In the head ------

Here is the code used for the menu:
<a href="#my-menu">Open the menu</a>
<nav id="my-menu">
   <ul>
      <li><a href="/">Home</a></li>
      <li>
         <a href="/about/">About us</a>
         <ul>
            <li><a href="/about/history/">History</a></li>
            <li><a href="/about/team/">The team</a></li>
            <li><a href="/about/address/">Our address</a></li>
         </ul>
      </li>
      <li><a href="/contact/">Contact</a></li>
   </ul>
</nav>

Please review and let me know if this is something you plan on fixing in the plugin or if I should look else where. We will be happy to donate to your plugin if we can get it working:)

**Comment by skielbasa** [comment]
We were also having this issue. It does track back to the off-canvas addon. We fixed it by commenting out line 269 (of the separated plugin); the menu still seems to work without that line.

```javascript
$page = $page.wrapAll( '<' + this.conf[ _ADDON_ ].pageNodetype + ' />' ).parent();
```
to

```javascript
// $page = $page.wrapAll( '<' + this.conf[ _ADDON_ ].pageNodetype + ' />' ).parent();
```

or if you're using the minified all version do a find for (on line 34)

```javascript
&&(t=t.wrapAll("<"+this.conf[o].pageNodetype+" />").parent())
```
and comment that out like so

```javascript
/* &&(t=t.wrapAll("<"+this.conf[o].pageNodetype+" />").parent()) */
```

Hope this helps.

**Comment by andrewrogersroi** [comment]
@skielbasa Thank you so much! That fixed our duplicating form issue. For some reason now when I click the menu all the content disappears. This is minor though:) Thanks again!

**Comment by skielbasa** [comment]
This was another issue we ran into. Different bug, same addon.

comment out (on the minified all version)

```javascript
var s=0;a.$wndw.on(i.resize,function(e,t){if(t||a.$html.hasClass(n.opened)){var o=a.$wndw.height();(t||o!=s)&&(s=o,a.$page.css("minHeight",o))}}),
```

like so 

```javascript
/* var s=0;a.$wndw.on(i.resize,function(e,t){if(t||a.$html.hasClass(n.opened)){var o=a.$wndw.height();(t||o!=s)&&(s=o,a.$page.css("minHeight",o))}}), */
```

OR lines 292 - 304 in the off canvas addon

```javascript
        var _h = 0;
        glbl.$wndw
            .on(_e.resize,
                function(e, force) {
                    if (force || glbl.$html.hasClass(_c.opened)) {
                        var nh = glbl.$wndw.height();
                        if (force || nh != _h) {
                            _h = nh;
                            glbl.$page.css('minHeight', nh);
                        }
                    }
                }
            );
```

like so

```javascript
//        var _h = 0;
//        glbl.$wndw
//            .on(_e.resize,
//                function(e, force) {
//                    if (force || glbl.$html.hasClass(_c.opened)) {
//                        var nh = glbl.$wndw.height();
//                        if (force || nh != _h) {
//                            _h = nh;
//                            glbl.$page.css('minHeight', nh);
//                        }
//                    }
//                }
//            );
```

**Comment by andrewrogersroi** [comment]
@skielbasa Good deal. Thanks again!

**Comment by FrDH** [comment]
In general, commenting out lines of code isn't a good idea.
Also, the "wrapAll" method by itself should not create a copy of a FORM, so I don't think that's really the issue.

Have you read the tutorial (http://mmenu.frebsite.nl/tutorial/setting-up-the-html.html)?
It states: 
> if you can, please wrap all markup in only one DIV

Also, have a look at the documentation for the off-canvas add-on:
http://mmenu.frebsite.nl/documentation/addons/off-canvas.html
You can tell the plugin what HTML node it should consider to be the page by using the `offCanvas.pageSelector` configuration option.

Hope this helps.

**Comment by skielbasa** [comment]
I agree that it's not a great idea, but it made a pretty decent bandaid. We couldn't think of a reason why that would be doubling forms either. We stumbled on that 'fix' by accident. Further, both my team and andrewrogersroi, are implementing this on Hubspot, so we don't really have access to much of the raw markup. Are you thinking that the lack of the single container is behind both of these issues?

**Comment by FrDH** [comment]
The lack of a single container is the only reason the plugin wraps the containers in a new div:
````javascript
if ( $page.length > 1 )
{
   $page = $page.wrapAll( '<' + this.conf[ _ADDON_ ].pageNodetype + ' />' ).parent();
}
````

**Comment by skielbasa** [comment]
I'll see if I can find some workaround for HubSpot to get the site wrapped in a single div. I'll report back on whether or not that fixes our issue.

**Comment by andrewrogersroi** [comment]
@skielbasa I have found a fix for this in HubSpot. It's not the very best but would work perfect when using html pages rather than the COS GUI. I cloned my file to a coded file and added my menu in this with this jinja code:
<pre><code>                {% menu "my_menu" label="My Menu", flow="horizontal", flyouts="true", max_levels=4, root_key=None, root_type="site_root", site_map_name="default", no_wrapper="true", extra_classes="true" %}</code></pre>

Notice that I added the "no_warpper" and "extra_classes" options. This seems to strip all the crazy code layers HubSpot appends. I then uncommented the code in the mmenu js file. IT WORKED:)
Let me know how that would work in your process.

**Comment by skielbasa** [comment]
I'll bring it up with my team on Monday.

**Comment by andrewrogersroi** [comment]
Thanks again for all your help.Also thanks to @FrDH for having an awesome plugin!

**Comment by skielbasa** [comment]
A little ghetto, but the solution we came up with was to use

```javascript
$('body > *').wrapAll('<div class="random-wrapper-div"></div>');
```

**Comment by mnjit20** [comment]
thank you @skielbasa
