### ISSUE TITLE
can't change page while using mmenu with jquery mobile 

### ISSUE THREAD

**Issue by avishayhajbi** [BeSite/jQuery.mmenu#268]
i'm using jquery mobile and i can not change page in the navigation bar while i'm using the mmenu js file.
when he is canceled   the change page works fine.
for example: (just import the mmenu css & js)

        <!DOCTYPE html>
        <html>
         <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1,     minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
    
        
        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.css">
        <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
        <script src="http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js"></script>

        
        <link rel="stylesheet" href="css/offmenu/jquery.mmenu.all.css">
        <script type="text/javascript" src="js/offmenu/jquery.mmenu.min.all.js"></script>

        
          <script type="text/javascript">
             $(document).ready(function() {
                $("#menu").mmenu({
                   "offCanvas": {
                      "position": "right"
                   }
                });
             });
          </script>
    </head>
    <body>
        <div data-role="page" id="map_page">
            <header> <p></p> </header>
            <div data-role="content" class="ui-content" id="content">
                <div id="map"> </div>
            </div>
            <footer data-role="footer">
                <div data-role="navbar">
                    <ul>
                        <li>
                            <a href="#map_page" id="" rel="external" data-transition="fade" data-inline="true"><img src="img/map.png" /> Map </a>
                        </li>
                        <li>
                            <a href="#notification_page" id="" rel="external" data-transition="fade" data-inline="true"><img src="img/notification.png" /> Notification</a>
                        </li>
                        <li>
                            <a href="#menu" id="" rel="external" data-transition="fade" data-inline="true" ><img src="img/more.png" /> More</a>
                        </li>
                    </ul>
                </div>
            </footer>
        </div>
        
        <div data-role="page" id="notification_page">
            <header> <p></p> </header>
            <div data-role="content" class="ui-content" id="content">
            </div>
            <footer data-role="footer" >
                <div data-role="navbar" >
                    <ul>            
                        <li>
                            <a href="#map_page" id="" rel="external" data-transition="fade" data-inline="true"><img src="img/map.png" /> Map </a>
                        </li>
                        <li>
                            <a href="#notification_page" id="" rel="external" data-transition="fade" data-inline="true"><img src="img/notification.png" /> Notification</a>
                        </li>
                        <li>
                            <a href="#menu" id="" rel="external" data-transition="fade" data-inline="true" ><img src="img/more.png" /> More</a>
                        </li>
                    </ul>
                </div>
            </footer>
        </div>
         
         <nav id="menu">
             <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/about">About us</a>
                   <ul>
                      <li><a href="/about/history">History</a></li>
                      <li><a href="/about/team">The team</a></li>
                      <li><a href="/about/address">Our address</a></li>
                   </ul>
                </li>
                <li><a href="/contact">Contact</a></li>
             </ul>
          </nav>
    </body>
</html>

just import the off menu css & js and check it ! 
thanks.

**Comment by FrDH** [comment]
You'll probably need to set some options for this markup to work.
First, the plugin needs to know what DIV it should consider to be the page, you can use the `offCanvas.pageSelector` configuration for this.
Also, you'll need to update this when changing pages using the `setPage` custom event.
Finally, you might need to trigger `$.mobile.changePage` method when an anchor inside the menu is clicked, jQM might do this automatically though.

FYI, there was a jQM demo in an earlier version of the plugin:
https://github.com/BeSite/jQuery.mmenu/blob/v4.1.0/demo/jqmobile/index.html
Note that this is an old version of the plugin and uses an old version of jQM.
