### ISSUE TITLE
Add cdn info

### ISSUE THREAD

**Issue by PeterDaveHello** [BeSite/jQuery.mmenu#270]
Hi @BeSite,

I'm Peter from cdnjs.com,

I wonder if you would like to add cdn info in the readme or the website?

This is the page we provide cdn for jQuery.mmenu - https://cdnjs.com/libraries/jquery.mmenu

Thanks!

**Comment by FrDH** [comment]
Sure, I'll update the websites download page with the next release.

**Comment by PeterDaveHello** [comment]
Thanks!
