### ISSUE TITLE
Change width without SASS

### ISSUE THREAD

**Issue by IngwiePhoenix** [BeSite/jQuery.mmenu#271]
I only wish to modify the width and change down a little. The default is very, very wide and for my liking, a bit too wide. Therefore I'd like to change it to about 1/4.

I tried so by changing `.mm-menu`'s width from `80%` to `20%`. The menu resizes, but there is a huuuuge gap between it and the page contents. How do I get rid of that?

**Comment by FrDH** [comment]
The best approach would be to override the default sass variables, or to create a new scss file:
http://mmenu.frebsite.nl/documentation/custom-css/custom-sizes.html

Without sass, you can probably override the css values manually. Have a look at this file and you should be able to figure out what css rules to override:
https://github.com/BeSite/jQuery.mmenu/blob/master/src/scss/inc/_sizing.scss
