### ISSUE TITLE
Using FixedElements configuration with a header that is fixed after scroll

### ISSUE THREAD

**Issue by lcavezza** [BeSite/jQuery.mmenu#272]
I am having the issue that my fixed header disappears when I open the mmenu, and I've attached the fixedElements configuration. I tried adding the FixedTop class, and also tried using the configuration: 

            classNames: {
                fixedElements: {
                   fixedTop: "is-fixed"
                }
             }

The 'is-fixed' class is what is added to my header on scroll to make it fixed when it reaches the top. However, since the configuration is happening on page load (and the header isn't yet fixed on page load, and the is-fixed class isn't yet attached to the element until scrolled to the top), the fixedElements configuration isn't working. Any thoughts on how I could still stop my header from disappearing when it isn't yet fixed on page load?

Thanks!

**Comment by BornKillaz** [comment]
Same thing happens to me! Couldn't found any solution yet. My header is
"position: fixed;" and disappears when I open the menu, and returns after
the menu closes.

#header { height: 40px; width: 100%; position: fixed; left: 0; top: 0; }


It's not obstructive, so I didn't concerned too much about it, but it sure
needs to be fixed. It took me hours trying to figure it out a workaround
playing with CSS, without success.

**Comment by FrDH** [comment]
The plugin searches for the "fixedTop" elements when the plugin is fired. It's not "live", there is no "onClassnameChange" event or something like that.

I'd recommend to clone the header and give the "fixedTop" classname to only one of the two. After that, don't add/remove the classname when scrolling, but show/hide the two elements.
