### ISSUE TITLE
FixedElements + Position Bottom Issue With Detecting Clicks On Fixed Element

### ISSUE THREAD

**Issue by ltamrazov** [BeSite/jQuery.mmenu#273]
We have set up the following mmenu:

    $shareTooltip.mmenu({
            // *** options
            offCanvas: {
                position: "bottom",
                zposition: "front"
            },
            onClick:{ 
                close: true,
                setSelected: false
            },
        },{
            // *** configuration
            offCanvas: {
                pageSelector: "#wrapper",
            },
            panelNodetype: "ul"
        });

We also included the FixedElements add on, and added a Fixed Top to our header.

    <div id='#wrapper'>
        <header class="FixedTop"></header>
    </div>

Once the page loads, the mmenu modifies the structure to the following:

    <div id="#wrapper"></div>
    <div class="mm-blocker"></div>
    <header class="FixedTop"></header>

The tooltip opens as expected. However, once its opened, we cannot close it by clicking on the header (the fixed element). Clicking inside the #wrapper closes it as expected. Clicking inside <header> does nothing. 

This also only seems to happen with the "tooltip" implementation of the menu (position bottom, zposition front). We have another menu implemented on the same page (regular slide out menu) and it functions as expected. 

We found that if the header is moved above "mm-blocker", then the click works.

    <div id="#wrapper"></div>
    <header class="FixedTop"></header>
    <div class="mm-blocker"></div>
    
The reason is that "mm-blocker" and header both get the same z-index of 0; But <header> is below the blocker in HTML and therefore the <header> z-index takes precedence and as a result, the blocker does not cover the header and the click never registers.

Easy fix would be to:
1. set ".mm-blocker" z-index to 1
2. set ".mm-menu.mm-front" z-index to 2 instead of 1 (to make sure all the links inside the menu still register)

Alternatively, ensuring that the FixedElement add on moves "FixedTop" / "FixedBottom" element to a position above the ".mm-blocker" in html, should also fix the issue.

Thanks in advance.

**Comment by FrDH** [comment]
I see.
I'll rethink the z-indexes for `zposition: "front"`.

Thanks for reporting the issue.

**Comment by FrDH** [comment]
Should be fixed in the next release.

**Comment by ltamrazov** [comment]
great, thanks!
