### ISSUE TITLE
Any examples of a horizontal responsive menu?

### ISSUE THREAD

**Issue by B45man** [BeSite/jQuery.mmenu#275]
Hi all, I love how mmenu looks, it's really beautiful. I have a single question. If I want to have mmenu only appear on mobile devices, and turn into a regular navigation menu on a desktop browser, how would I go about doing this? I can't read anything about it in the documentation, so I assume it's not supported. Is this easily accomplished, or am I trying to force mmenu into a role it was not designed for?

**Comment by FrDH** [comment]
Basically, the menu can't simply switch back to the original state. But you can use the "clone" configuration option to clone the menu:
http://mmenu.frebsite.nl/support/tips-and-tricks.html#tt-responsive-layouts
