### ISSUE TITLE
Multiple instances using clone

### ISSUE THREAD

**Issue by Legin76** [BeSite/jQuery.mmenu#277]
For a responsive page I've set up an on-canvas inline version of the code for the menu on larger screens, which works really well (took a fair bit of css tweaking).

As the menu is huge (800 categories) I want to use the clone function to create a second version for smaller screens, which is off canvas, so that it does not have to be downloaded twice. I need both to run and use different classes so that they can have their own styles etc. 

I don't appear to be able to get both offcanvas: false and clone to work at the same time.

So my question is... How do I use the clone to make two working instances on the same page with their own configurations and classes?

            $("#menu").mmenu({
               "header": {
                  "title": "Categories",
                  "add": true,
                  "update": true
               },
               offCanvas: false,
            }, {
               // configuration
               clone: true,
            });

**Comment by FrDH** [comment]
The `clone` configuration option is indead only used by the`offcanvas` add-on.
You can ofcourse clone the menu manually, here's a short tutorial:
http://mmenu.frebsite.nl/support/tips-and-tricks.html#tt-responsive-layouts

Note that now you probably need to set an unique ID for all elements in the cloned menu:
````javascript
var $menu = $("#my-menu").clone();
$menu.add( $menu.find( "[id]" ) ).each(function() {
    $(this).attr( "id", "clone-" + $(this).attr( "id" ) );
});
````

**Comment by FrDH** [comment]
By the way, for an on-canvas version of the menu on larger screens, you could probably also use the "widescreen" extension: http://mmenu.frebsite.nl/documentation/extensions/widescreen.html

**Comment by Legin76** [comment]
That's great thanks..
I have two small issues now. 
1st is that I seem to be able to get both off canvas or on canvas but not different. The large screen inline version needs to be on canvas and the small screen version needs to be off-canvas.

2nd is that no matter which I click the links on only the top menu changes even with the different id's. Both load correctly but only the first menu changes.

      $(document).ready(function() {
            $("#menu").mmenu({
               "header": {
                  "title": "Categories",
                  "add": true,
                  "update": true
               },
               offCanvas: false,           
            });
          var $menu = $("#menu").clone();
          $menu.attr( "id", "my-mobile-menu" );
          $menu.attr( "class", "my-mobile-menu" );
          $menu.mmenu({
               "header": {
                  "title": "Categories",
                  "add": true,
                  "update": true
               },
               offCanvas: true,
            },
          });
      });

**Comment by FrDH** [comment]
I'm currently working on a couple of other tutorials as well, so I'll probably include an onCanvas menu as well.
Having seen what you're JS looks like, I think you might be better of using the "widescreen" extension. Have you tried it? You can see it in action on http://mmenu.frebsite.nl (simply resize your browser to > 1430px)
