### ISSUE TITLE
Multiple lists in sidebar

### ISSUE THREAD

**Issue by alokjain-lucky** [BeSite/jQuery.mmenu#278]
I want to show 3 different lists in sidebar (menu), and each list have its own heading.

Looks like current version of mmenu supports only one list is sidebar, other lists are hidden because you have used position absolute on each list. 

Is there any simple way so solve this issue?

**Comment by FrDH** [comment]
You can ofcourse manually append the LIs from the second and third UL to the first UL and seporate them with a "Label" LI:
````html
<ul>
  <li class="Label">First list</li>
  <li><a>first</a></li>
  <li><a>second</a></li>
  <li class="Label">Second list</li>
  <li><a>first</a></li>
  <li><a>second</a></li>
</ul>
````

You can also wrap the three ULs in a DIV:
````html
<div>
  <ul>
    <li><a>first</a></li>
  </ul>
  <p>some text</p>
  <ul>
    <li><a>second</a></li>
  </ul>
  <p>some text</p>
  <ul>
    <li><a>third</a></li>
  </ul>
</div>
````
