### ISSUE TITLE
Extend setup tutorial

### ISSUE THREAD

**Issue by fschleifenbaum** [BeSite/jQuery.mmenu#279]
If you don't specify a background-color for the <body>-tag, the Animation gets nasty. I've fumbled three hours around to find that out. Please include this in your tutorial to save others some time!

**Comment by FrDH** [comment]
It's mentioned in the tips and tricks page:
http://mmenu.frebsite.nl/support/tips-and-tricks.html

But I'll see how I can extend the tutorial, because noone wants to fumbling around for three hours :)
