### ISSUE TITLE
Simple method to implement mmenu in WordPress

### ISSUE THREAD

**Issue by LebCit** [BeSite/jQuery.mmenu#280]
Hello everyone,

First of all, a BIG BRAVO, and a million thanks to the developer of mmenu.
Since I've searched a lot and didn't found a tutorial on how to do it,
i made multiple tests and finally found a simple solution.
I really think that  WordPress is great because a lot of persons are ready
to share knowledge for free like the author of this great and cool plugin.
My contribution to this plugin, is how to implement it in WordPress, so let's go !

1- In your theme folder, create a new folder **mmenu** and put inside it the two main files **jquery.mmenu.min.all.js** and **jquery.mmenu.all.css** then  enqueue scripts in a function in your functions.php file
```php
function mmenu_scripts() {
wp_enqueue_script( 'jquery-mmenu-min-all-js', get_template_directory_uri() . '/mmenu/jquery.mmenu.min.all.js', array('jquery'), '4.7.5', false );
wp_enqueue_style( 'jquery-mmenu-all-style', get_template_directory_uri() . '/mmenu/jquery.mmenu.all.css' );
}
add_action( 'wp_enqueue_scripts', 'mmenu_scripts' );
```
2- In **header.php** JUST UNDER `<body <?php body_class(); ?>>` put the following code
```javascript
<script type="text/javascript">
  (function ($) {
     $(document).ready(function() {
        $("nav#menu").mmenu({
           "classes": "mm-slide mm-light",
           "counters": true,
           "footer": {
              "add": true,
              "title": "Footer"
           },
           "header": true,
           "searchfield": true,
           "offCanvas": {
              "zposition": "front"
               }
        });
     });
     })(jQuery);
</script>
```
PAY ATTENTION TO LINE 4 `$("nav#menu")`
This line is assuming that your menu is wrapped in a `<nav>` that have an id of menu !
So let's create the wp_nav_menu for this one.

3- In **footer.php** JUST BEFORE `<?php wp_footer(); ?>` put the following code
```php
<nav id="menu">
    <?php wp_nav_menu( array( 
    'theme_location' => 'primary',
    'container' => false,
    ) ); ?>
</nav>
```
PAY ATTENTION TO LINE 3 ` 'theme_location' => 'primary'`
This line is assuming that you are assigning/using the **primary** location menu.
You should not remove the `'container' => false` line, because it prevents WordPress from wrapping your menu with a `<div>` !

4- After adding some menu items to the primary location in the back-end of WP,
you just have to add a single line to see the magic in action.
In **header.php**, you can put under the  opening `<header>` tag the following line
```html
<a href="#menu">Open the menu</a>
```
Now you will see a link in the header of the theme a **Open the menu** link, just click it :wink:

Finally, you can play with the options of the plugin as you want and style the link that open the menu to be an icon like the hamburger on the site of mmenu plugin.

Hope that someone will benefit from this very simple integration and make a cool WP menu with mmenu !

**Comment by FrDH** [comment]
Hi,
Thank you for taking the time to write this tutorial.
Coincidentally I'm currently writing a WP plugin that does all this (and helps you set the options).

I'll see if I can set up this tutorial on the website somewhere.

**Comment by LebCit** [comment]
Hello,

You are most welcome :smile: 
Your jquery plugin is great, again BRAVO !
It would be great to have icons possibility within each level like
[Multi-Level Push Menu ](http://tympanus.net/Development/MultiLevelPushMenu/index2.html)
I had a little problem with mmenu when logged in to WP and using the default zposition or
```javascript
"offCanvas": {
    "zposition": "next"
}
```
This is why I've used `"zposition": "front"`
I've found a workout css solution to use the default or next zposition when logged in but it was not a pretty code and a little bit creepy :smile: so I've toke the front zposition
Thanks again, waiting to see your WP plugin, please tell me when you launch it.

Have a great WP coding :wink:

**Comment by nowton** [comment]
@FrDH I assume the WP-plug is still in the works? Have been unable to find it, yet, am certainly interested.

**Comment by FrDH** [comment]
Stil working on it, have been kept pretty busy lately.

**Comment by FrDH** [comment]
Here's a beta version:
http://mmenu.frebsite.nl/mmenu.zip

Install it by clicking the "Upload Plugin" button in the "Plugins -> Add New" menu.
After that, assign a menu to the "App look-alike" location.
Go to the "mmenu" menu to customize the menu.

**Comment by nowton** [comment]
Thanks @FrDH will check it out.

**Comment by nowton** [comment]
Hmm, need a little more guidance: uploaded, installed, created a menu mmenu, added items, added a link in the header with #mmenu as anchor. On clicking that nothing happens and no menu is shown. I can see it in source though. What am I overlooking?

**Comment by FrDH** [comment]
Hmm, here are a few pointers:
Are you getting any errors in the console?
Did you assign the menu to the "App look-alike menu" location?
Did you check the "mmenu" page from the wordpress menu? Did it work?

**Comment by nowton** [comment]
1. Download the plugin
2. Install the plugin
3. Assign a menu to the secondary location (App lookalike menu)
4. add <a href="#menu">Open the menu</a> to header.php
5. clickyclicky, nothing happens. (mmenu is visible in source though)

not sure what you mean by "Did you check the "mmenu" page from the wordpress menu?"

**Comment by FrDH** [comment]
After installing the plugin, there's a menu item added to the WP menu called "mmenu", click it to go to the mmenu settings page.
Is there an online example I could have a look at?

**Comment by FrDH** [comment]
Wait, did you say "#menu"?
That should be "#mmenu".

**Comment by nowton** [comment]
K have found the mmenu settings after testing it in another project; another issue arises there as it seems to clash with our custom menu walker.

**Comment by FrDH** [comment]
Any idea why? Basically all the plugin does, is include the needed .js and .css files and fire the plugin onDocumentReady:
````javascript
$("#mmenu").mmenu({
    // options
});
````

**Comment by nowton** [comment]
We have a custom walker for our menu defined in our theme. On activating the plugin we get the following error message in the backend:

'Strict Standards: Declaration of Walker_Anchor_Menu::start_lvl() should be compatible with Walker_Page::start_lvl(&$output, $depth = 0, $args = Array) in /media/sites/www.clientnameremoved.dev/wp-content/themes/clientnameremoved-verslag2014/functions.php on line 103

Strict Standards: Declaration of Walker_Anchor_Menu::start_el() should be compatible with Walker_Page::start_el(&$output, $page, $depth = 0, $args = Array, $current_page = 0) in /media/sites/www.clientnameremoved.dev/wp-content/themes/clientnameremoved-verslag2014/functions.php on line 103
'

**Comment by FrDH** [comment]
Sound like an issue with the Walker_Anchor_Menu class.
I don't have anything to do with that.

**Comment by nowton** [comment]
Nevermind, we managed to solve this on our end. We used a custom walker for wp_list_pages, so that's not a WordPress menu. Thanks for a great piece of software!
