### ISSUE TITLE
Code from tutorial isn't working

### ISSUE THREAD

**Issue by helloncanella** [BeSite/jQuery.mmenu#281]
Hi. I'm exploring your the mmenu from the tutorial. I've translated the code to my notes, but it isn't working. I don't know what.

![screenshot 2015-02-01 05 26 40 2](https://cloud.githubusercontent.com/assets/6288484/5991392/f5e176ae-a9d2-11e4-81f9-1f93121efadb.png)

**Comment by LebCit** [comment]
Hello,

First of all, the script should be JUST BEFORE the closing `</head>` tag.
Secondly, all your `<nav>...</nav>` should be JUST BEFORE the closing `</body>` tag.
Don't forget to put some content to your page :wink:

**Comment by helloncanella** [comment]
Hi @LebCit 

Thank you for respond my message.

I've tried your approach. The result persists: a blank page (I didn't report it before).

THE CODE:
![screenshot 2015-02-01 17 08 05](https://cloud.githubusercontent.com/assets/6288484/5993367/7671805e-aa35-11e4-8797-6bb7dea93338.png)

THE RESULT
![screenshot 2015-02-01 17 13 15](https://cloud.githubusercontent.com/assets/6288484/5993377/b5bf61ae-aa35-11e4-9ddf-0bb54a50b3c2.png)

I've tested the the code on codepen, using the jquery.mmenu.all.css and jquery.mmenu.min.all.js used in the demos (http://mmenu.frebsite.nl/mmenu/js/jquery.mmenu.min.all.js   and http://mmenu.frebsite.nl/mmenu/css/jquery.mmenu.all.css )

The result rendered in the codepen was the same. For sake of explanation, the link http://codepen.io/helloncanella/pen/XJebbK.

Thank you for the attention

**Comment by LebCit** [comment]
Hello,

The blank page is a very good sign.
I told you before to add some content to your page !
At least try to add before the `<nav>` the following code to see something
```
<a href="#my-menu">Open the menu</a>
```
Now go and click the link !
Hope this will solve your issue, it should do it :smile:

**Comment by helloncanella** [comment]
@LebCit Thank you for the help. All it is ok.
