### ISSUE TITLE
using demo in asp.net web forms cause a non return values to my controls in code behind 

### ISSUE THREAD

**Issue by eliesaber** [BeSite/jQuery.mmenu#282]
Hi, I have used the mmenu demo in my web application.
I have a search button that should return to me a text value.
When I stopped the mmenu.js from my page and now I m obtained the value.

master page:
<div id="page"> 
<form id="form1" runat="server">
...
</form>
</div>

In code behind I have a break point but with no value for text 
![page](https://cloud.githubusercontent.com/assets/10322017/6019079/34fc56be-aba5-11e4-9b47-bc0db790d7ca.png)

**Comment by eliesaber** [comment]
Hi,
I have found the problem causing this issue.
I m using mmenu.all.js and fixedelements.js together and this cause for not sending any data to code behind.
I have replace the all.js and fixedelements.js by each library individually and the problem is fixed.
The problem now is that when Im using some of these libraries the whole page including the footer is shaking like a zumba dance. 
if there is a fix for this problem I appreciate. thanks.

**Comment by FrDH** [comment]
I'm not sure what you did to solve this issue (nor how a page shaking like a zumba dance would look like), but if you've include the .all.js file, you already have the fixedelements.js file so you don't need to include it seporately.

**Comment by eliesaber** [comment]
I didn't know that .all.js include also fixedelements.js anyway I have same result; I have stopped every js library except jquery and all.js and no result for my controls in my code behind, and when I use mmenu libraries individually the result appears normally but I'm loosing the fixation of the footer and not all libraries work for me they directly stop my controls to give results.
It seems there is an error in some of these libraries and in all.js.
By the way thanks a lot for your fast response, really I appreciate and I will donate because you  deserve  Really.

**Comment by eliesaber** [comment]
Do you have any suggestions about this issue?

**Comment by FrDH** [comment]
I don't think I understand the issue, is there an online example?

**Comment by eliesaber** [comment]
No, but the problem is that if I use mmenu.all.js, all the returning values are empty in code behind file like the picture above. If I use mmenu.js, I got all my values normally.

I need to use .all.js for many reasons like fixation for the header and footer..., thanks.

**Comment by FrDH** [comment]
I can't think of a reason why the seporate files would behave different from the concatinated file.
Does it make any difference if you include all minified files seporately instead of the concatinated file?

**Comment by eliesaber** [comment]
I can only use mmenu.js, dragopen.js and buttonbars.js, All the rest libraries if I use them I loose my values.

**Comment by FrDH** [comment]
Are you getting any errors?
The seporate files seem to be working OK over here so I don't think there is much I can do.

**Comment by eliesaber** [comment]
No errors and  the seperate files are not working ok (fixedelements, counters, header, footer, labels, toggles, searchfield and all.js) the problem reside in these files they are stopping my values. Thanks.

**Comment by eliesaber** [comment]
Hi, If you can see this issue again thanks.

**Comment by FrDH** [comment]
What exactly do you mean when you say "the files are stopping your values"?
All files seem to work fine on the website and in the demo pages.

**Comment by eliesaber** [comment]
I m using the libraries in asp.net webforms applications and when I use (fixedelements, counters, header, footer, labels, toggles, searchfield and all.js) the returning values in my code behind for all my controls give empty results. You can see this in my first comment. thanks.

**Comment by FrDH** [comment]
I really don't understand what you mean with "returning values in my code behind".
I don't think I can help you with that.

Like I mentioned before, all files seem to work fine on the website and in the demo pages. So I don't think there is much I can change anyway.

**Comment by eliesaber** [comment]
The thing is when postback to the server my values are empty it's possible that these libraries are affecting the postback in some way.

**Comment by eliesaber** [comment]
If there is a replacement for fixed elements I can use it it will solve my problem because on IE the header and footer are fixed and don't move when opening the menu and I can 't use the fixedelements library it will stop my values like i told you before thanks.

**Comment by eliesaber** [comment]
Please If you can answer me to fix this issue, Thanks?

**Comment by FrDH** [comment]
Basically, all the fixed elements add-on does, is add a classname (mm-fixed) to the elements and put them directly inside the BODY.
You can manually do that (either with JS or by changing the HTML) and remove the add-on.

I really have no idea about postback values to the server.
