### ISSUE TITLE
Subtitle before the CHILDREN UL.

### ISSUE THREAD

**Issue by epiblue** [BeSite/jQuery.mmenu#284]
Hi,

This is an awesome plugin, I'm loving it... 

That beeing said, I would like to ask, how can I change subtitle position?

I'm using Foundation framework and my ul. has class to display blocks according to the device and I would like to include the subtitle to be full width of the container. 

How can I do that? I don't want to damage any of your code, because it works perfectly.

Thanks,

**Comment by epiblue** [comment]
Also, would like to know, how to disable link removal of parent elements? I use this for website, not mobile app, so I would like the parent link also be clickable and if clicked on the arrow, then taken to the second window. 

Thanks, Hope to hear from you soon.

Best wishes,

**Comment by FrDH** [comment]
I don't think I understand the question, what do you mean with:
> include the subtitle to be full width of the container

**Comment by epiblue** [comment]
Hello,

Sorry for the late reply,

I will try to explain with some images.

Now I have them like this (child menu):
![image](https://cloud.githubusercontent.com/assets/6641569/6191174/e0c99c90-b3a7-11e4-8e12-59e845f28253.png)

Here's the main menu:
![image](https://cloud.githubusercontent.com/assets/6641569/6191186/ef399212-b3a7-11e4-9e57-3c00b55230c0.png)

what I mean is how can I specify that the subtitle of the parent menu would be in a separate container and make it full with and the elements inside to be as is in the list, to witch I will apply foundation grid.

Also, I've noticed that in the parent menu, the links are beeing deleted, how to prevent that? What I mean, that I want the category title to maintain the link to the main category page and if clicked on the arrow, continue to the submenu.

Thanks

**Comment by epiblue** [comment]
Any help, please :)

**Comment by FrDH** [comment]
You can't change the position of the subtitle with an option or anything. You could use the header add-on I guess: http://mmenu.frebsite.nl/documentation/addons/header.html
