### ISSUE TITLE
Menu trigger doesn't change to 'X' on iOS Safari

### ISSUE THREAD

**Issue by pathetix** [BeSite/jQuery.mmenu#285]
Screenshot attached.
![screenshot-2015-02-06-13 42 17](https://cloud.githubusercontent.com/assets/1005635/6075065/1a04bdd4-ae06-11e4-84c7-fbb9e4893854.png)

**Comment by FrDH** [comment]
This is probably due to some missing "-webkit-" prefix / Mobile Safari not supporting some CSS transitions without a prefix.
Fortunately this hamburger-icon isn't part of the plugin, so I'm going to close this issue.
