### ISSUE TITLE
Option for slidingSubmenus: false, on specified submenus

### ISSUE THREAD

**Issue by mintcanary** [BeSite/jQuery.mmenu#286]
It would be nice to have to option to effectively set `slidingSubmenus` to false, only on specified submenus. For example, to list subsections of a single page. It wouldn't make sense to treat these the same as links to a different page. Alternatively, just the option of mmenu ignoring specified lists (and them being treated as regular lists). As far as I can see, this isn't currently possible..

**Comment by FrDH** [comment]
Not a bad idea, I'll have to do some research if this can be achieved without too much hassle (and with hassle I mean creating issues for other options and add-ons).
You can make the plugin ignore a list by adding the classname "mm-nolist" to the UL.
````html
<nav id="menu">
    <ul>
        <li>
            <a href="#">test</a>
            <ul class="mm-nolist">
                ...
            </ul>
        </li>
    </ul>
</nav>
````

**Comment by FrDH** [comment]
Happy to inform you, this behavior will be available in the next major release (coming soon):
````html
<nav id="menu">
    <ul>
        <li>
            <a href="#">test</a>
            <ul class="Vertical">
                <li><span>This list will expand below its parent</span></li>
            </ul>
        </li>
    </ul>
</nav>
````
