### ISSUE TITLE
Chrome 40.0.2214.111 m issue

### ISSUE THREAD

**Issue by svenssonhenke** [BeSite/jQuery.mmenu#287]
Menu doesn't open properly, and when it does submenus open only half way in the latest Chrome version (both desktop and mobile). Earlier version works fine. 
The examples on the site are affected by this as well.

Anyone else have this issue?

**Comment by FrDH** [comment]
I'm on version 40.0.2214.111 (64-bit) on a macbook but can't find anything wrong with the menu or examples.

**Comment by FrDH** [comment]
Any update on your side?
I still can't reproduce the issue.

**Comment by svenssonhenke** [comment]
I'm now on 40.0.2214.115 m and the issue is gone!
