### ISSUE TITLE
forgot to include  jquery.mmenu.js?

### ISSUE THREAD

**Issue by thet** [BeSite/jQuery.mmenu#288]
i can only find minified versions of jquery.mmenu in https://github.com/BeSite/jQuery.mmenu/tree/master/src/js - but not the unminified source file.

**Comment by FrDH** [comment]
There is no unminified version of that file. It is a combination of the oncanvas and offcanvas files. Both do have an unminified version.

**Comment by thet** [comment]
I see. How the files are compiled is defined in https://github.com/BeSite/jQuery.mmenu/blob/master/Guardfile
thanks for the pointer.
