### ISSUE TITLE
Complete parent links as a trigger for the submenus

### ISSUE THREAD

**Issue by anyway** [BeSite/jQuery.mmenu#289]
Hi,

at first: thank you so much for that great menu!

Just wondering, if it is possible (in a simple way) using the complete parent links as a trigger for the submenus. Not only the arrow. The parent pages with children should be not clickable. Not the best usablity, I know, but I need it that way for that particular project. 

Is that possible?

Thanks for your help!

**Comment by FrDH** [comment]
Duplicate issue:
https://github.com/BeSite/jQuery.mmenu/issues/84
https://github.com/BeSite/jQuery.mmenu/issues/266
