### ISSUE TITLE
Tooltip header dissapears on Ios

### ISSUE THREAD

**Issue by apod42** [BeSite/jQuery.mmenu#291]
Hello,

On devices running Ios (tested on an Iphone 4 and Ipad 3), the header of the Tooltip shows as the tooltip opens, but as soon as the transition is complete, it disappears. However, the close button is still functional, if you click in its area. 

The issue appears only on Ios, not Android. On Ios the issue is present only if the tooltip has lots of text, requiring scroll. If there is only little content and no scrolling needed there is no problem. 

Steps to reproduce:

1. Open http://mmenu.frebsite.nl/examples.html
2. Using an Ios device click on the tooltip example - "This is a demo. Have you ever thought about how tooltips should work on mobile devices?"
3. Notice how the header containing the title and X close button does not show.

This only happens if content inside the tooltip is vertically overflowed.

**Comment by FrDH** [comment]
Hi, I noticed the same issue, but only when viewed directly from the examples page, i.e. in an iframe.
If you view the demo in a new window, it seems to work as intended.
My guess is, ios has some issues with iframes.

**Comment by apod42** [comment]
Hello,

The issue is not related to iframes. When viewing the demo in a new window the viewport is much larger and text inside the tooltip has no vertical overflow (no scrolling). So this is why the problem does not appear in this case.

The issue appears on IOS when the tooltip contains a large amount of text, and scrolling is needed. Managed to reproduce this issue on my website, no iframes. And can't seem to find a solution.

Another question please: how can I add some padding or a margin just below the fixed header? Can't seem to do this with css, maybe I should work on the header javascript addon?

**Comment by apod42** [comment]
Ok, after wasting half a day on this, simple one line css fix: add this line

-webkit-transform: translate3d(0,0,0);

to the .mm-header class. Full explanation here: http://stackoverflow.com/questions/9807620/ipad-safari-scrolling-causes-html-elements-to-disappear-and-reappear-with-a-dela

Question two remains: How can I add some padding or a margin just below the fixed header? If in the .mm-header class I do this: padding-bottom: 10em; nothing happens. Why?

**Comment by FrDH** [comment]
That's really odd. Any idea why it only disappears in that example?
Anyway, I'll implement it in the next version.

For the second question, try adding padding-top to the .mm-panel class.

**Comment by apod42** [comment]
Thanks for the tip, worked! No idea why the header bug appears only for the tooltip...
