### ISSUE TITLE
1st level menu url is beeing replaced with #

### ISSUE THREAD

**Issue by epiblue** [BeSite/jQuery.mmenu#292]
Hey,

I have mmenu in my magento site, but the 1st level menu link's are replaced with #, am I doing something wrong?

Please suggest how to fix it?

Thanks,

**Comment by FrDH** [comment]
Are you sure this is done by the mmenu plugin? I can't think of any reason it would do that.

**Comment by epiblue** [comment]
Sorry, my mistake! It was my php failing :) Thanks for the help :)
