### ISSUE TITLE
Fixed positioning: can't stop page anchoring to the top when mmenu opened.

### ISSUE THREAD

**Issue by petebarr** [BeSite/jQuery.mmenu#302]
Hi,

I need to have a fixed mobile bar at the top of the page and I've got the following html:
```
<div class="mobile-bar FixedTop">
        <a href="#main-menu" class="burger-menu"></a>
</div>
```
and javascript: 
```
$("#main-menu").mmenu({
         // options
    }, {
		// configuration
		classNames: {
         	selected: "current-menu-item"
		  },
		clone: true 
    });
```
However when the burger menu anchor is clicked to open the mobile menu,  the page always anchors to the top rather than maintaining it's scroll position.

I've tried adding the Fixed Position addon with 'FixedTop'  class added to the fixed position 'mobile-bar' but it doesn't do anything.

Cheers.

**Comment by FrDH** [comment]
The page jumping back to the top has nothing to do with the fact your header bar has `position: fixed`. It probably because the `height` of the `HTML` and/or `BODY` nodes is set to `100%`.

Have you read the tips and tricks page?
http://mmenu.frebsite.nl/support/tips-and-tricks.html

**Comment by petebarr** [comment]
Thanks for the response Fred. That appeared to work initially, however when you close the menu the fixed mobile bar no longer is fixed and appears to go back inline thus moving itself back to the top of the document.

**Comment by FrDH** [comment]
For fixed elements, it is recommended to use the "fixedElements" addon:
http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html

**Comment by petebarr** [comment]
I was using that but still no joy.

**Comment by FrDH** [comment]
Are you sure you implemented it correctly?
Did you get any errors in the console?

**Comment by petebarr** [comment]
Sorry for the delay. I believe so. I added the plugin and was using the above code. I'm quite far into the project now and have removed it so I don't remember seeing errors, but I may look at it again later when we do final tweaks. Thanks, I'll let you know.

**Comment by FrDH** [comment]
OK, an online demo always helps debugging :)
