### ISSUE TITLE
Change the menu panels to have different ul/li list

### ISSUE THREAD

**Issue by protherj** [BeSite/jQuery.mmenu#304]
I see from the issue here that its possible to add links dynamically to the menu: https://github.com/BeSite/jQuery.mmenu/issues/57

However, I'm trying to change the entire menu and would like mmenu to re initialize more than just a single panel.

How would I go about that?

**Comment by FrDH** [comment]
If you're chaning the entire menu (the DIV or NAV around the UL), you can probably remove the old menu and create the new one like you normally would:
````javascript
$("#my-menu").mmenu();

// after some event
$("#my-menu").remove();
$("body").prepend( the_new_menu_html );
$("#new-menu").mmenu();
````

Adding multiple (and nested) ULs is possible by default as described in issue 57 (`$ul` can be any (set of) ULs with nested sub-ULs).
