### ISSUE TITLE
2 instances of mm-opening on left/right menu system?

### ISSUE THREAD

**Issue by zuhloobie** [BeSite/jQuery.mmenu#306]
I have successfully implemented a left and right side menu along with the fixed div solution. They work great, thanks!

What I don't like is how the left and right navicon's animate at the same. I believe this is due to it calling the same, shared "html.mm-opening" css. How can I get them to animate independently? Probably a noob question, sorry, but thanks in advance. I've asked on StackOverflow, but didn't get a response so hoping someone is kind enough to comment here :)

Fiddle: http://jsfiddle.net/jn4h0nfw/5/

**Comment by FrDH** [comment]
That fiddle gives a js-error:
TypeError: $(...).mmenu is not a function.

**Comment by zuhloobie** [comment]
Sorry about that...I had moved some external files on my server since the version I linked in my post so it was having a couple 404 errors, etc. I added the correct external paths back in: http://jsfiddle.net/zuhloobie/jn4h0nfw/6/

**Comment by FrDH** [comment]
Try using the `classes` option, all specified classes will be added to the menu- and HTML node when the menu opens.
````javascript
$("#menu-left").mmenu({
   classes: "left-menu-opened"
});
$("#menu-right").mmenu({
   classes: "right-menu-opened"
});
````
