### ISSUE TITLE
Fixing Accessibility Issues

### ISSUE THREAD

**Issue by dcaryll** [BeSite/jQuery.mmenu#308]
I'm attempting to fix accessibility issues tested with the WAVE plugin. I'm getting the following error on any top level parent links: "A link contains no text". 

Is there a way to change the Javascript to give the anchor tags text so that this error doesn't exist (this error is visible when tested with the WAVE plugin on http://mmenu.frebsite.nl/)?

Thanks for any help!
-Dan

**Comment by FrDH** [comment]
Although there isn't any text actually inside the anchor, it does have visual content (the arrow).
So I'm not really sure how important this is.

**Comment by FrDH** [comment]
If you really need a text in the anchors, I guess you could add it manually:
````javascript
$("#menu").mmenu().find( ".mm-subopen" ).append( "<span>Open the submenu</span>" );
````
Add some CSS to hide the text:
````css
.mm-subopen span { display: none; }
````

**Comment by dcaryll** [comment]
Thanks! This should work perfectly. I'll try it and let you know if it then
passes.

Thanks again!
-Dan



Web Developer / Graphic Designer
http://www.DanCaryllDesign.com <http://www.dancarylldesign.com/>

**Comment by hidayah87** [comment]
hi @dcaryll  do u already solve the problem? i had been trying a few times but disnt work...
@FrDH where to put the code that you provided? 
$("#menu").mmenu().find( ".mm-subopen" ).append( "<span>Open the submenu</span>" );
