### ISSUE TITLE
Scripts inside of mm-page run twice

### ISSUE THREAD

**Issue by greyvugrin** [BeSite/jQuery.mmenu#309]
First off, great plugin! It's super lightweight and I've used it on many sites without fail. This is the first time I've noticed anything weird.

Recently I noticed some strange behavior with scripts on a client's Shopify store, and pinpointed mmenu as the culprit. It appears that any script inside of the page wrapper div gets executed twice: once on page load, and again when mmenu is initialized (and `.mm-page` is added as a wrapper).

More context:
```
<div class="wrapper" id="page">
<!-- Tons of extra stuff... -->
    {{ content_for_layout }} <!-- << This contains markup for products, pages, etc  -->
</div>
```

For most scripts this isn't a problem because they can be moved around, but some of Shopify's scripts are located in their templates by default, and could lead to complications down the line.

This could be a known issue, but just in case some folks run into the same problem, this is your heads up.

**Comment by FrDH** [comment]
You should make sure `.mm-page` isn't added as a wrapper:
http://mmenu.frebsite.nl/tutorial/setting-up-the-html.html
> You probably don't need to make any changes to the HTML of your page.
> But if you can, please wrap all markup in only one DIV:

**Comment by chadwithuhc** [comment]
I believe the code gets ran twice because the elements are cloned.

**Comment by FrDH** [comment]
The plugin does not clone elements on the page. The "fixedElements" add-on does relocate elements from inside the page to directly in to the `<body>`.
If that's the case, you should not use the "fixedElements" add-on but the elements directly in the `<body>` and add the needed classnames manually.

**Comment by coffeeshell** [comment]
I have the same problem and I would like to know if will be some changes to fix this or I should find another plugin to use.

**Comment by FrDH** [comment]
@coffeeshell Did you try the solution suggested in this thread?

**Comment by coffeeshell** [comment]
I use a CMS that "doesn't allow" me to make such changes in my markup.
I really like this plugin, best one that I found so far but for the project I work on (that include many scripts inside my layout) I can't use it :(

**Comment by FrDH** [comment]
In the next version, there'll be a config option to prevent the plugin from wrapping multiple DIVs in one DIV. Note that this is NOT recommended usage becauce it probably introduces new issues you'll have to address manually.
