### ISSUE TITLE
submenu chrome issue

### ISSUE THREAD

**Issue by cistecky2** [BeSite/jQuery.mmenu#310]
Hi,
I am using mmenu in my help page. I have like 15 items in the main menu. 5 of them are used as link to other submenus (#mm-1, ...... ,#mm-5). The problem is, if one of those submenus is longer than Chrome's window height. 

Mmenu will automatically show vertical scrollbar, but i can't use it by my scrolling wheel. I must click on the scrollbar and drag down with my mouse. 

When I close the menu and reopen it. Appears the submenu again, but it is possible to scroll now.

It happens only pc version of Chrome. Opera, Firefox, IE and all mobile and tablet browsers are OK.

![mmenu](https://cloud.githubusercontent.com/assets/11314800/6592515/cb52fa00-c7cf-11e4-8717-016de3868e62.png)

Thanks for any response and sorry for my english.

**Comment by FrDH** [comment]
I don't think there is much I can do about a browser not enabling the scroll wheel on your mouse.

**Comment by cistecky2** [comment]
Well it is not working in Chome when subpage is too long. Looks like bug of mmenu/chrome.
