### ISSUE TITLE
Menu Link Suppressing Click Event

### ISSUE THREAD

**Issue by nsggroup** [BeSite/jQuery.mmenu#311]
Hi,

I have the menu plugin setup and working correctly - however some of the menu items in my structure link to modal windows and as such there are data attributes on the links to define additional details.

On the link I have a class and my JQuery listens for this class then retrieves the various data attributes on the link in order to create the modal window based on the various params.

With my standard menu in desktop view this is working as expected - however when Mobile Menu engages in mobile width it seems .click is suppressed and the functions are never called.

Is there any way to get around this and to be able to call a function on click?

Thanks

**Comment by FrDH** [comment]
You can tell the plugin when to prevent the default clicking behavior (and when not) with the `onClick.preventDefault` option:
````javascript
$("#menu").mmenu({
    onClick: {
        preventDefault: function() {
            if ( $(this).hasClass( "modal" ) ) {
                return false;
            } else {
                return true;
            }
        }
    }
});
````
I guess something like that should do the trick.

**Comment by nsggroup** [comment]
Hi Thanks for the reply - that seems to have suppressed the menu closing on selection but its still not firing the modal function. Even a simple .click alertbox

**Comment by nsggroup** [comment]
In fact adding the above seems to have prevented the normal pages (without the class 'modal') loading
```
 $('nav#menu').mmenu({
        onClick: {
            preventDefault: function () {
                if ($(this).hasClass("appButton")) {
                    return false;
                } else {
                    return true;
                }
            }
        }
    }, {
        // configuration
        classNames: {
            selected: "active"
        }
    });
```

**Comment by nsggroup** [comment]
Just experimenting with that example and have found if I use alerts for feedback on the class check I got the expected outcome - in that it correctly identified if the class was present or not and for nodes without the class the page correctly clicked through.

However when I included the return true/false again it stopped the click through on standard links - so i have reversed the true/false and thats again allowing click through on pages without the class and for pages with the class I get the alert but the modal functions still not being called:
```
$('nav#menu').mmenu({
        onClick: {
            preventDefault: function () {
                if ($(this).hasClass("appButton")) {
                    alert("Has Class call function")
                    return true;
                } else {
                    //alert("Doesnt Have Class") << this now allows clicking as normal
                    return false;
                }
            }
        }
    }, {
        // configuration
        classNames: {
            selected: "active"
        }
    });
```

**Comment by nsggroup** [comment]
I think a solution may lie in calling the modal function from within the preventDefault function. 

It seems preventDefault as an option doesn't necessarily allow scope to external click events but has some relation to the use of # tag urls having scanned the documentation.

As such my modal function which is called naturally through listening on $('.modal').click(){} I could manually call from based on your suggested if statement:

Thanks for your help

```
$('nav#menu').mmenu({
        onClick: {
            preventDefault: function () {
                if ($(this).hasClass("appButton")) {
                    modal($(this));
                    return true;
                } else {

                    return false;
                }
            }
        }
    }, {
        // configuration
        classNames: {
            selected: "active"
        }
    });
```
