### ISSUE TITLE
Menu Items not selected after page load

### ISSUE THREAD

**Issue by phillafrance** [BeSite/jQuery.mmenu#312]
Hi, I am having issues with the menu items not appearing selected after I click on them. When I click on one of the links from the menu, after the page finishing loading the menu does not show the item as having been selected and it also doesn't show the submenu as being open. So I'm not sure if there is something wrong with how I am doing it or something else. Any help you can provide is appreciated.

**Comment by FrDH** [comment]
Does the LI have the classname "Selected" (or the classnames specified in the classNames.selected configuration option)?
mmenu.frebsite.nl/tutorial/styling-lists.html

**Comment by phillafrance** [comment]
It does not. The weird thing is that the <a> tag that is the child element of the li that is supposed to be active has the Selected classname on it. so it's like 
<li>
  <a c lass="mm-selected"></a>
</li>

I have no idea why it's happening but all if the classes that are supposed to get added to the <li> elements are instead being added to the <a> tags.

**Comment by FrDH** [comment]
Sounds to me there's something wrong with your HTML. Maybe a missing close-tag or something.
Anyway, your HTLM should look like this:
````html
<nav>
   <ul>
      <li><a href="#">Text</a></li>
      <li class="Selected"><a href="#">Text</a></li>
   </ul>
</nav>
````

**Comment by phillafrance** [comment]
```html
<nav id="menu">
        <ul>
            <li><a href="test.html" class="mm-selected">YCYW 2014 Admin</a></li>
            <li><a href="/">Hess Acquisition Entries</a></li>
        </ul>
    </nav>
```

This is what I have for my html. I have tried changing the class to Slected and that also did not work. I am not missing any closing tags as this is the only html on my page within the \<body> tag. I don't know what I'm doing wrong because I can't even get the item to be selected no matter what I do.

**Comment by FrDH** [comment]
Like I said, the "Selected" class needs to be on the LI, not the A.
That should solve the issue.
