### ISSUE TITLE
Menu items not firing onclick event

### ISSUE THREAD

**Issue by erikadanis81** [BeSite/jQuery.mmenu#313]
Im allocating an id to each menu item, and in my javascript listening for the onclick event. However it doesnt fire at all. Im getting no errors and "sometimes" when i make a change to the code and refresh the page the onclick fires at randow.
 A sample of my menu items is below:

< nav id="menu" >
        < ul >
            < li >
                < span id="showScanDataBtn" >
                    < i class="menu-icon fa fa-leaf" ></ i > Scan Data
                </ span >
            < /li >
        </ ul >
    </ nav >

and my javascript:

$(function () {
 $("#showScanDataBtn").click(function (e) {
            alert("button clicked!!");
            $(".panels").hide();
            $("#scanDataPanel").show();
        });
});

The javascript show and hides my panels/divs. Any help would be greatly appreciated.

**Comment by FrDH** [comment]
Do you fire that JS before or after creating the menu?
Also, check the documentation on the `onClick` option, any option inside it can be a function that (once an anchor in the menu is clicked) loops through all anchors.
http://mmenu.frebsite.nl/documentation/options/

**Comment by erikadanis81** [comment]
I had fired the JS after the mmenu was initialised. I managed to work around it by changing my <span> to an <a href="#" onclick="showScanDataBtn();"> and put my js in a function outside jquery's document.ready.

function showScanDataBtn () {
alert("button clicked!!");
$(".panels").hide();
$("#scanDataPanel").show();
}
 
Seems to be working fine now.
