### ISSUE TITLE
Css issue on Samsung S3 and HTC one S running android 4.3

### ISSUE THREAD

**Issue by erikadanis81** [BeSite/jQuery.mmenu#316]
The menu when first expanded has some white padding to the right as per image. But snaps back into place when you click anywhere inside the menu.
However this doesnt happen on HTC M8 on android 5.0.1

![test-image](https://cloud.githubusercontent.com/assets/1965047/6627304/32ac8808-c8f5-11e4-98f2-5f923ba43af9.jpg)

**Comment by FrDH** [comment]
I think this is the same issue as described here:
https://github.com/BeSite/jQuery.mmenu/issues/260

If so, it'll be solved in the next version (coming soon) where the box-shadow (available via an extension) is actually added to the menu, not the page.
