### ISSUE TITLE
mmnu closes after pressing anywhere

### ISSUE THREAD

**Issue by Qlbaz** [BeSite/jQuery.mmenu#317]
In Firefox is close down the list after pressing anywhere on the page, even on the same list
I hope to find a solution to it.

في فيرفوكس يتم إعلاق القائمة بعد الضغط على أي مكان في الصفحة، حتى على القائمة نفسها
ارجو أن اجد حل لها.

**Comment by FrDH** [comment]
Is this issue present in any of the examples on the website or in the download pack?
Of not this probably is not an issue with the plugin and an online example would je helpfull

**Comment by Qlbaz** [comment]
Thank you
You solve the problem after calling the library again
