### ISSUE TITLE
Olark Chat

### ISSUE THREAD

**Issue by verzosa** [BeSite/jQuery.mmenu#318]
Hi,
When i add Olark script in the body section, Olark chat does not work. Mmenu is wrapping everything in the body. Is there a way to go around this?

Olark is fine when the srcript is placed in the head section.

Regards

Edward

**Comment by FrDH** [comment]
Have you tried Googling the issue?
https://www.olark.com/help/mmenu

**Comment by verzosa** [comment]
That is the first thing i did. The only answer i found was on this site....which is not really a permanent solution for me. Placing the script in the head section is a temporary solution.

**Comment by verzosa** [comment]
Did not work with the latest mmenu plugin

**Comment by FrDH** [comment]
I can't verify that fix really works because I don't use the Olak chat myself.
But if it worked, it probably should still work.
I did notice the `pageSelector` configuration option was moved to the `offCanvas` object:
````javascript
$("#my-menu").mmenu({
   // options
}, {
   // configuration
   offCanvas: {
      pageSelector: "#olark-wrapper"
   }
});
````
