### ISSUE TITLE
Trigger Or Manually Close All Submenus When Menu Trigger Is Closed

### ISSUE THREAD

**Issue by metaskills** [BeSite/jQuery.mmenu#322]
I have been reading thru the source and I can not find a clean even or interface to do this. I am currently using `oncanvas` and `offcanvas`with sliding submenus. Is the only way to do this is to listen for the `close.mm` event and find all opened `.mm-panel` divs and start removing class names? Thanks in advance!!!

**Comment by metaskills** [comment]
This is what I am doing now for my menu's `close.mm` event.

```javascript
this.menuMobile
  .find('.mm-panel')
  .removeClass('mm-opened mm-subopened mm-hidden mm-highest mm-current')
  .addClass('mm-hidden');
this.menuMobile
  .find('#mm-0')
  .removeClass('mm-hidden')
  .addClass('mm-opened mm-current')
```

**Comment by FrDH** [comment]
Opening the first panel ("#mm-0") should close all opened sub-panels.
````javascript
$("#mm-0").trigger( "open.mm" );
````

**Comment by metaskills** [comment]
Great idea! But that does not work. If I navigate down into a few sub menus, then close. It will indeed put the main menu at the top, but clicking on the same submenu will animate it in from the wrong direction. I suspect there are some artifact class names left on the sub panels in-between the main and nested one when the menu was closed.

**Comment by FrDH** [comment]
Have a look at this issue: https://github.com/BeSite/jQuery.mmenu/issues/237

Basically, the navigation is mainly based on the idea you only go back 1 step at a time.
I'll see if I can come up with a better way of closing opened submenus when opening a parent for the next update.

**Comment by metaskills** [comment]
Thanks! For now this hack will work for me. Closing. Thanks again for your time.

**Comment by FrDH** [comment]
The issue is a bit more complex so I decided to introduce an API method called `closeAllPanels`.
This will immediately close all opened subpanels and open the first.

Note that in version 5.0.0 I replaced the custom events with an API:
````javascript
var $menu = $("#my-menu");
$menu.mmenu();

var api = $menu.data( "mmenu" );
api.bind( "closed", function() {
    api.closeAllSubmenus();
});
````

For more info, check the documentation:
http://mmenu.frebsite.nl/documentation/api.html

**Comment by nicole-wright** [comment]
Hi there,

Thanks for the great plugin.  Question about using the API.  I'm using the CDN for the js with the newest version; *all.min.js.  When I try and trigger closeAllSubmenus(), I get a console error where the function is not defined.  Everything else on the menu is working beautifully, so I wonder if I'm missing something?

Thanks.

**Comment by FrDH** [comment]
If the function is undefined, you're probably doing something wrong. I can't tell you what you're doing wrong without some example code.

**Comment by nicole-wright** [comment]
Thanks for getting back to me.
My use case is that I'm using the vertical sub-menus on some of the list items, while others have no sub-menu.  I want all expanded sub-menus to close when the menu is closed, and the menu to auto-close when an item with an ajax load is clicked (the list items without sub-menus & the sub-menu items), the menu should close.

The following works for me. I'm wondering about event propagation when I'm using the click method, however.  Do you think this hack have side effects on the mmenu javascript?

var $menu = $("#my-menu");
        $menu.mmenu({
            slidingSubmenus: false,
            extensions: [
                "theme-dark"
            ],
            onClick: {
                close: true
            }
        }, {
            offCanvas: {
                pageNodetype: "section"
            }
        });

        var api = $menu.data("mmenu");
        api.bind("closed", function () {
            $.each($("li.mm-vertical.mm-opened a.mm-next"), function (obj) {
                $(obj).click();
            })
        });

**Comment by gilestaylor** [comment]
Is it possible to recreate the 'closeAllSubmenus' to toggle and 'openAllSubmenus'
