### ISSUE TITLE
only first link works in jquery mobile

### ISSUE THREAD

**Issue by asad786r** [BeSite/jQuery.mmenu#323]
hi i am trying to use your wonderful jquery plugin with jquery mobile and chrome. I am running into some issues, mainly on a multiple "data-role=page" document, the mmenu only slides out and links only function on the first page (index.html). 

However, unfortunately any other pages, loaded into the dom by jquery, such as page3.html or index.html#page2, do not seem to have any links functioning. This includes links on the the main  body of the page newly loaded pages, and also the menu button does not seem to slide out the menu. However external links on newly loaded pages such as http://www.google.com still work.

```
<!DOCTYPE html>
<html class="index">
	<head>
		<meta charset="utf-8" />
		<meta name="author" content="www.frebsite.nl" />
		<meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes" />

		<title>jQuery.mmenu demo</title>
  
 	    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css" />       
                
		<link type="text/css" rel="stylesheet" href="../css/demo.css" />
		<link type="text/css" rel="stylesheet" href="../../src/css/jquery.mmenu.css" />
        
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.3.min.js"></script>

		<script type="text/javascript" src="../../src/js/jquery.mmenu.min.js"></script>
                        
        <script type="text/javascript">

			$(function() {
				$('#menu').mmenu({
					onClick: {
						preventDefault: true
					}
				}, {
					offCanvas: {
						pageSelector: 'div[data-role="page"]:first'
					}
				});

				$('#menu a').on(
					'click',
					function()
					{
						var _t = this;
						$('#menu').one(
							'closed.mm',
							function()
							{
								$.mobile.changePage( _t.href, {
									transition: 'slide'
								});
							}
						);
					}
				);
			});

			$(document).on(
				'pageshow',
				function( e, ui )
				{
					$('#menu').trigger( 'setPage', [ $(e.target) ] );
					$('#menu a').each(
						function()
						{
							if ( $.mobile.path.parseUrl( this.href ).href == window.location.href )
							{
								$(this).trigger( 'setSelected.mm' );
							}
						}
					);
				}
			);

			
		</script>
        
     <script src="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>        
    
    </head>
	<body>
		<div data-role="page">
			<div class="header">
				<a href="#menu" data-ajax="false"></a>
				Demo
			</div>
			<div class="content" data-role="content">
				<p><strong>This is a page 1.</strong><br />
					Click the menu icon to open the menu.</p>
				
				<p>This page integrates the jQuery.mmenu plugin in a jQuery Mobile project.</p>
			</div>
		</div>

		<div id="page2" data-role="page">
			<div class="header">
				<a href="#menu" data-ajax="false"></a>
				Demo
			</div>
			<div class="content" data-role="content">
				<p><strong>This is page 2</strong><br />
					Click the menu icon to open the menu.</p>
                <p>
                <a href="http://www.google.com">Page 3</a>
                </p>
                
                
			</div>
		</div>

		<nav id="menu">
			<ul>
				<li class="Selected"><a href="index.html">Page 1</a></li>
				<li><a href="index.html#page2">Page 2</a></li>
				<li><a href="page3.html">Page 3</a></li>
			</ul>
		</nav>
	</body>
</html>
```

what I have done here is, and you will have to forgive me for this, is to take your jqmobile example form mmenu version-4.6.4, and combine it with the latest jquery, jqmobile. I also used the latest version of the demo.css and mmenu css and js files from mmenu version 4.7.5.

The reason why i have done this, is because I have tried all day to get jquery mobile to work with mmenu, unsuccessfully. The couldn't even get a mmenu panel menu to appear using only 4.7.5 sources. There is no other jquery mobile multi data-role=page example after 4.6.4, all other examples or solutions online were either too complex or not suitable for my problem. I feel as if i am missing something obvious because now that i have the menu working (on initial load, one page, with working links), the rest of the links on other jquery loaded pages do not seem to work...:(

Lastly i want to thank you for reading this lengthy issue, and congratulate you for such an amazing plugin. I look forward to hearing back from you soon. Thank you

**Comment by FrDH** [comment]
You'll need to tell the plugin the "page" changed. 
In the current version (5.0.0) you can use the API method `setPage`:
````javascript
var $menu = $("#menu");
$menu.mmenu();

var api = $menu.data( "mmenu" );
api.setPage( $("#my-page") );
````

In earlier versions you can use the custom event `setPage`.
````javascript
var $menu = $("#menu");
$menu.mmenu();
$menu.trigger( "setPage.mm", [ $("#my-page") ] );
````

**Comment by FrDH** [comment]
Havent tested it, but I guess you could use the navbars addon and specify `"<gcse:searchbox></gcse:searchbox>"` for the content:
````javascript
$("#menu").mmenu({
    navbars: [{
        position: "top",
        content: [ "<gcse:searchbox></gcse:searchbox>" ]
    }]
});
````
Note that for this to work, mmenu needs to be fired before google does its magic.

**Comment by FrDH** [comment]
I'm currently working on a "framework wrapper" for jq mobile. Basically, it should be a fix for this issue w/o you having to do any extra work. Stay tuned for the update.
