### ISSUE TITLE
Changing the text of the Header title

### ISSUE THREAD

**Issue by jryanad** [BeSite/jQuery.mmenu#324]
I am trying to change the header text via the Header options but it doesn't seem to work unless I am missing something. I have this:

`header: {
    add: true,
    title: "Main Menu"
}`

Any advice would be greatly appreciated. Awesome plugin by the way!

**Comment by FrDH** [comment]
I realize it's a bit odd, but adding and updating the header are seporate options.
Try adding `update: true` to the `header` object.

**Comment by jryanad** [comment]
Perfect! Again, awesome job on this.
