### ISSUE TITLE
iconbar bug with demo plus other questions

### ISSUE THREAD

**Issue by KonradPZuse** [BeSite/jQuery.mmenu#325]
Hello sir, hope you've been well,

I was looking at the demo for iconbar here http://mmenu.frebsite.nl/documentation/extensions/iconbar.html#mm-2 and I noticed that when I opened the menu, it was as if it just opened a little extra portion of the menu, and that the rest was hidden.  This was confirmed when I clicked about us, and then closed the menu, as the about us, and the back arrow were present, and I was able to go back to the original icons.

Just figured you would like to know this.

My next comment is that I use this menu as more of a selection tool, rather than a menu, i.e., option color, suboption red, green, blue.  with multiple options and suboptions.

How the menu works now is that you select an item and then it selects the last selected option.  What I would like is if I could have each suboption selected for each option.  So if I have 3 options, I would have 3 different selected items, if that makes sense.

Also I have one part of my menu which is generated from information from the server, so I use it's id to grab the info, and then attach a onClick to it.  The problem I am having is that instead of the item itself being clicked, the menuOption is getting clicked.

i.e., MenuItem1's Option a gets clicked, and instead of a getting highlighted, MenuItem1 gets highlighted instead.

Not too sure what's going on, I tried multiple onClick methods, I tried to change from a custom id name to mm-1 id (auto-generated by you), but nothing is working... Any idea what it could be?  This third issue has to do with issue 2 as well.

I think that's all for now, thanks! :)

**Comment by FrDH** [comment]
The iconbar example seems to be working as intended (the whole point of the extension is to show a little of menu while it isn't opened).
If the rest of your question isn' an issue with the plugin, please try asking it on stackoverflow.com
Lots of people over there that are eager to help you with that kind of stuff.

**Comment by KonradPZuse** [comment]
Yeah I know that it shows the little menu, but if you open the menu, click the submenu for "about us" and then "close the menu" it will show the text from the submenu about us, with a back arrow, and not the icons.

I was saying I noticed the icons were part of the main menu, so if you click a sub menu, it will show a little part of that menu instead

I wasn't sure if the rest of my question was a feature that was needed, or if it was something that's a regular question, which is why I asked here.  I'll check SO then, thank you.

**Comment by FrDH** [comment]
> Yeah I know that it shows the little menu, but if you open the menu, click the submenu for "about us" and then "close the menu" it will show the text from the submenu about us, with a back arrow, and not the icons.
That's exactly what the extension is supposed to do.

**Comment by KonradPZuse** [comment]
I wouldn't think part of text would be shown for the icon bar, I would assume if there were no icons on the next page, it would revert back to the page with icons, not cutoff text that doesnt' serve icon purposes?
