### ISSUE TITLE
New Theme not recognized?

### ISSUE THREAD

**Issue by csgaraglino** [BeSite/jQuery.mmenu#330]
In the jquery.mmenu.themes.css file I have created a new theme called theme-red and when calling the plug-in I have it set to call the red theme - but for some reason it is not - it is using the white theme instead?

$(document).ready(function() {
            $("#menu").mmenu({
               "extensions": [
                  "border-full",
                  "effect-zoom-menu",
                  "pageshadow",
                  "theme-red"
               ],
               "counters": true,
               "footer": {
                  "add": true,
                  "title": "<a href='http://www.ilgm.com'>Desktop Version</a>"
									
               },
               "header": true,
               "searchfield": true
            });
         });

![screen shot 2015-04-03 at 10 17 16 am](https://cloud.githubusercontent.com/assets/11787784/6984877/a1ac7640-d9ea-11e4-930d-478e176e552d.png)

**Comment by csgaraglino** [comment]
However - if I update the jquery.mmenu.all.css file it does read the proper CSS

I guess I am confused as to why there are two files and which ones should I be updating?

**Comment by FrDH** [comment]
How did you create that CSS?
Using the SCSS mixins?

**Comment by csgaraglino** [comment]
I just edited the existing .css file

**Comment by FrDH** [comment]
Are you sure the css file is included in the webpage?
Does the menu get the classname `mm-theme-red`?

**Comment by FrDH** [comment]
By the way, if the background color for the menu is all you changed, you can simply override it without having to create a new theme:
````css
#my-menu {
  background: red;
}
````

**Comment by csgaraglino** [comment]
Good-morning Fred,

Yes - the all the files are with the webpage, and yes the class name was also correct.

Thanks for the tip on the override - what That will work for a lot of cases, in this case I will be customizing the theme to match the clients brand - and therefore need to change quite a bit of the styles.

As a workaround I was able to update the jquery.mmenu.all.css file instead - but I am not sure if that is the proper way to do this or should I be using the jquery.mmenu.themes.css file for all my updates?

**Comment by FrDH** [comment]
Is there an online example? Because I don't see any reason why it wouldn't work if the classname is added and the correct CSS files are included.

**Comment by csgaraglino** [comment]
http://dev.ilgm.com/mobile

**Comment by csgaraglino** [comment]
Right now the INDEX.HTML file is calling "theme-red"

Only the jquery.mmenu.themes.css file contains the RED information - I pulled it out of the jquery.mmenu.all.css file and the system is defaulting to WHITE.

FYI: The rest of the html files (for this demo) are using the dark theme.

**Comment by FrDH** [comment]
So on index.html you've added `theme-red` to  the `extensions` option, but you don't include include the file `jquery.mmenu.themes.css`?
So basically all CSS for `theme-red` is NOT included in the webpage?
