### ISSUE TITLE
how to change width?

### ISSUE THREAD

**Issue by craigh** [BeSite/jQuery.mmenu#331]
I've read and accomplished this http://stackoverflow.com/questions/24363523/mmenu-custom-width-settings

so now I have a `.css` file and a `.css.map` file but I don't know how to proceed (complete sass newbie). I'm loading the newly generated `.css` file, but it makes no difference. (also have an annoying border issue).

Sorry to litter the bug/issues area with support requests. :confused: thanks in advance.

![screen shot 2015-04-05 at 10 29 54 am](https://cloud.githubusercontent.com/assets/350048/6997167/ba26fe80-db7e-11e4-924a-6d7cf5f93183.png)

**Comment by FrDH** [comment]
You should add the new classname ("hiddenpanel-customwidth") to the menu.
You can do this manually (in the HTML) or by adding "hiddenpanel-customwidth" to the `classes` option (in versions older than 5.0.0).
As of version 5.0.0 the `classes` option is replaced with the `extensions` option:
````javascript
$("#menu").mmenu({
    classes: "mm-classname", // older versions
    extensions: ["classname"]
});
````
Note that the newer versions will prefix all classnames with "mm-" automatically.

**Comment by craigh** [comment]
thank you for the help. I figured out how to change the width. Any ideas what to do with the border interfering with the counters?

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
The "mm-next" button should have a padding-left due to the preceding counter:
````css
em.mm-counter + a.mm-next {
    padding-left: 40px;
}
````
