### ISSUE TITLE
offCanvas configured in position bottom moved content to right.

### ISSUE THREAD

**Issue by fabiaojr** [BeSite/jQuery.mmenu#334]
Hi,

I configured offCanvas position in bottom, but when clicked many times in menu, occasionally content is moved to right.

For example in page:
http://mmenu.frebsite.nl/documentation/extensions/positioning.html

![image](https://cloud.githubusercontent.com/assets/7843022/7124786/3214150c-e202-11e4-83f1-124e7e5af999.png)

![image](https://cloud.githubusercontent.com/assets/7843022/7124763/0bdf6fa8-e202-11e4-9017-45b7f98850e0.png)

after clicked many times in menu (opened and closed).

![image](https://cloud.githubusercontent.com/assets/7843022/7124890/f99554ec-e202-11e4-9081-cd9dda7bdf53.png)

Result:

![image](https://cloud.githubusercontent.com/assets/7843022/7124807/5b052154-e202-11e4-858f-f831726bb7ce.png)

**Comment by FrDH** [comment]
Sounds odd, I can't think of a reason why the behavior would switch after clicking many time on the hamburger icon.
Is there an online example? I couldn't reproduce this issue using the demo files from the website.
