### ISSUE TITLE
background: cover not working correctly

### ISSUE THREAD

**Issue by ryanward86** [BeSite/jQuery.mmenu#335]
![screenshot_2015-04-20-12-15-20](https://cloud.githubusercontent.com/assets/12030825/7229259/ad0e4b5e-e759-11e4-9996-a2e0f9f18ec9.png)
![screenshot_2015-04-20-12-15-27](https://cloud.githubusercontent.com/assets/12030825/7229260/ad355b4a-e759-11e4-9010-bee2d5ed380c.png)

Hi,

When i use background: cover, the background on the page is full height when the menu slides out, but when the menu is hidden it is reduced in size. Is there a line in the mmenu.css that may conflict me using background: cover?

**Comment by FrDH** [comment]
When the menu opens (the page slides out), the page gets "background: inherit".
You can set the `offCanvas.moveBackground` option to `fasle` to prevent this behavior, but I'm not sure that'll result in the desired behavior.

If everything else fails, try using the `offCanvas.zposition` option to position the menu in front of the page.
