### ISSUE TITLE
Can we do a conditional load if using the WP plugin?

### ISSUE THREAD

**Issue by nowton** [BeSite/jQuery.mmenu#336]
I'd like to serve this menu to handhelds only. I already know how to do that, but how would I go about that in integrating the WordPress plugin. Or would we better off just manually deploying it and not using the plugin? Thanks in advance, and thanks for a wonderful menu.

**Comment by FrDH** [comment]
The WP plugin has a tab "usage", check the "Use a different location" checkbox, specify the jQuery selector and check the "clone" checkbox.
That way, your desktop menu will be cloned and used for mobile.
