### ISSUE TITLE
Uncaught TypeError: this.opts.extensions.join is not a function

### ISSUE THREAD

**Issue by jaredatch** [BeSite/jQuery.mmenu#337]
http://cl.ly/image/0K0a0a2J3u2m

This happens about 50% of the time when I refresh the page, which of course breaks the menu.

Any ideas? I moved the script to load at in the head but same results.

**Comment by jaredatch** [comment]
Here's a live URL.

Go to https://attorney-group.com/colorado/ scroll to the bottom of the page. Refresh your browser a few times, you'll see an error in console and the links will show at the bottom of the page.

I'm using

```
	$menu.mmenu({
		"offCanvas": {
			"position": "right"
		},
		"extensions": [
			"theme-dark"
		]
		}, {
		"classNames" : {
			"selected" : "current-menu-item"
		}
	});
```

I can't figure out why it works on some loads but errors on others.

Any insight?

**Comment by jaredatch** [comment]
It's something with the extensions opts.

I cleaned things up, per the documentation, but as long as I provide an extension (or multiple) the errors still occur frequently

```
	$menu.mmenu({
		"extensions": [
          "theme-dark",
          "pageshadow"
        ],
		"offCanvas": {
			"position": "right"
		},
		"classNames" : {
			"selected" : "current-menu-item"
		}
	});
```

If I remove the extensions it works fine....

**Comment by FrDH** [comment]
That's odd, if the `extensions` option always is an array, I can't think of any reason why `join` would not be a function.

**Comment by jaredatch** [comment]
I know, I can't figure it out for the life of me, it's driving me nuts :grin: .

If you sit there and refresh that page several times you'll see sometimes it loads without issue, other times that error triggers and the menu fails.

There are no other console errors, so I don't see where anything else would be conflicting.

I'm trying to think that the scenario could be? Menu sometimes loads too quick or too late? Code is below. I thought maybe in some cases things are trying to initialize too fast maybe?

```
	var $menu = $(".nav-primary").clone().appendTo('body');
	$menu.removeAttr( "id" ).removeAttr( "class" ).find( 'ul' ).removeClass( "genesis-nav-menu menu-primary" );
	$menu.mmenu({
		"extensions": [
          "theme-dark",
          "pageshadow"
        ],
		"offCanvas": {
			"position": "right"
		},
		"classNames" : {
			"selected" : "current-menu-item"
		}
	});
	var API = $menu.data( "mmenu" );
	$(".mobile-menu-toggle").click(function() {
		API.open();
	});
```

**Comment by FrDH** [comment]
Somehow, I still can't reproduce the issue, I've refreshed the page about 20 times but am not getting the error.
Completely irrelevant to this issue, but your `classNames.selected` should be in the second argument (the "configuration" object).

**Comment by jaredatch** [comment]
Yeah it's weird to me too. Never figured it out, I ended up just not loading the extensions and it works fine. I'm using this script on probably half a dozen seperate client sites (love it!) and this is the only one that has encountered this error - so even though the console log doesn't show it, I'm going to assume there is some script or edge case at play here just on this site. Because of that I'm not going to worry about it any further - when I posted this I thought maybe it was something obvious.

So you're saying the correct syntax would be what I have below? Let me know. That and go ahead and close this.

```
$menu.mmenu({
        "extensions": [
          "theme-dark",
          "pageshadow"
        ],
        "offCanvas": {
            "position": "right"
        },
      }, {
        "classNames" : {
            "selected" : "current-menu-item"
        }
    });
```

**Comment by FrDH** [comment]
That ought to do it, check the mmenu + WordPress tutorial:
http://mmenu.frebsite.nl/tutorials/frameworks/wordpress.html

**Comment by parkerault** [comment]
I've run across this as well, you can kind of see what's going on here:

<img width="866" alt="screen shot 2015-08-25 at 5 15 47 pm" src="https://cloud.githubusercontent.com/assets/78856/9482038/049dee18-4b4d-11e5-834b-aaec90554408.png">

In this case, some overly chatty PHP caused multiple elements with the `[data-ref="mobileMenu"]` selector to get passed to the constructor. The exception is not raised when passed a constructor that matches a single element. Maybe that will help you narrow it down.
```javascript
  $(function() {
    // mobile nav
    $('[data-ref="mobileMenu"]').mmenu({
       "offCanvas": {
          "position": "top"
       },
       "extensions": [
          "theme-dark"
       ],
       "autoHeight": true,
       "navbars": [
          {
             "position": "top",
             "content": [
                "prev",
                '<img src="/wp-content/uploads/2015/06/afm-logo.png" class="afm-header-logo">',
                '<a class="mm-btn" href="#mm-0"><img src="/wp-content/uploads/2015/06/icon-close.png" class="afm-nav-mobile-close-icon"></a>',
             ]
          },
          {
             "position": "bottom",
             "content": [
                '<a class="afm-cta-button-link" href="#">REGISTER</a>'
             ]
          }
       ]
    });
  });
```
