### ISSUE TITLE
 $.mobile.changePage not working with mmenu

### ISSUE THREAD

**Issue by Kiwi79** [BeSite/jQuery.mmenu#338]
Hello. I have several page roles in the same html.  $.mobile.changePage funcntion is working right, but if I add mmenu, no error is thrown but navigation does not occur.

I'm using v 1.3.2 of jquery mobile. 

$("#menu").mmenu({       
        offCanvas: {
            position: "right",
            zposition: "front"
        }
    });

Regards

Xabi

**Comment by FrDH** [comment]
I'm not really familiar with jQM. But without an online example, there really is nothing I can do to debug this.

**Comment by FrDH** [comment]
As of version 5.4.1, there's a "framework wrapper" for jQ mobile:
http://mmenu.frebsite.nl/documentation/framework-wrappers.html

Give that a try, should make mmenu work in jQ mobile out of the box.
