### ISSUE TITLE
Can't install package on NPM

### ISSUE THREAD

**Issue by falzhobel** [BeSite/jQuery.mmenu#339]
Tried `npm install jQuery.mmenu` but npm returns a 404 not found. I know I can install from the git url directly, but just wanted to raise the issue ;)

**Comment by FrDH** [comment]
any idea what file(s) caused the 404? I recently moved the distribution files from the `src` to the `dist` folder.

**Comment by falzhobel** [comment]
It's in the command line directly that I get the error:

```
$ npm install jQuery.mmenu
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "jQuery.mmenu"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code E404

npm ERR! 404 Not Found: jQuery.mmenu
npm ERR! 404
npm ERR! 404 'jQuery.mmenu' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '...'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by FrDH** [comment]
I really am not that familiar with installing stuff through npm. Is there anything I need to do to make this work?

**Comment by falzhobel** [comment]
You can follow the instructions on NPM's website:

https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by FrDH** [comment]
I'm pretty sure I never done that before so my guess is, somebody else did.

**Comment by kaesetoast** [comment]
Hi @FrDH.

Your lib is not registered on npm. Maybe you might do this, many folks are switching to npm as a bower replacement and it would be really cool if one would be able to install mmenu via npm.

For now, I'll install via git url, but would definitely cool if you would publish this on npm :-)

**Comment by FrDH** [comment]
I honestly have no idea how to register anything on npm, I anyone else can do this, please do.

**Comment by kaesetoast** [comment]
If that's ok for you, I'll publish it there. NPM does not allow uppercase letters in package names, so I created a Pull Request to change the name inside package.json (#388).

If this is fine with you, I would publish your lib on npm and try to keep it up to date with your repo. If you want to take over the npm ownership at any time, feel free to contact me. :-)

**Comment by zgordan-vv** [comment]
Hello, can you tell me, please, how to use mmenu if installed as npm package? Thank you.

**Comment by kaesetoast** [comment]
@zgordan-vv it depends on how you structure your JavaScript. Do you use NPM just for managing dependencies, or are you using it in conjunction with a module loader like Browserify?

The easiest approach would be to just include the source files from the /dist folder.

**Comment by zgordan-vv** [comment]
I try to use it with react. The reason I decided to try npm package instead of usual way like <script>src="path/to/js/jquery.mmenu.all.min.js"></script> and then $("#menu").mmenu() is I get an error like SyntaxError: expected expression, got '<' and Unhandled promise rejection TypeError: __WEBPACK_IMPORTED_MODULE_5_jquery___default(...)(...).mmenu is not a function. I don't know though if using npm can help.
