### ISSUE TITLE
Not working scroll with Fullpage.js

### ISSUE THREAD

**Issue by levin10111** [BeSite/jQuery.mmenu#340]
Hi!

I have a website with https://github.com/alvarotrigo/fullPage.js
This script has own fullscreen scrolling by anchors. When I type URL with anchor in browser, it's ok, scroll is working. But, if I paste the same URL in href attribute of link Mmenu, scroll is not working, I click to link, panel closing without scrolling.

Please, help!

**Comment by FrDH** [comment]
Have you seen the one-page example?
http://mmenu.frebsite.nl/examples.html

**Comment by levin10111** [comment]
Thank you for your reply!

It was strange bug:
I used method of Fullpage.js "$.fn.fullpage.moveTo('section2')" with text anchor, It did not work.
Then I tryed method "$.fn.fullpage.moveTo(2)" with index anchor, and it's working!

P.S. without mmenu both methods is working.
