### ISSUE TITLE
mmenu vs event click incompatibility

### ISSUE THREAD

**Issue by adrianmihalko** [BeSite/jQuery.mmenu#341]
I have problem with mmenu on [my site] (http://mihalko.eu/?view=mobile) (just click on search icon) I have a simple .slideToggle function:

    $(function() {
    
      $("#search_link").on('click', tapHandler);
    
      function tapHandler(event) {
        $('#search-div').slideToggle();
        setTimeout(function() {
          $('#search-text').focus().tap();
        }, 0);
      }
    });

But the slideToggle(); is not working properly, it's immediately slides up. If I remove mmenu code:

      <script type="text/javascript" data-no-instant>
         $(document).ready(function() {
            $("#menu").mmenu({
               "extensions": [
                  "pageshadow"
               ],
               "header": {
                      "title": "Menu",
                      "add": true,
                      "update": true
                   }
            });
         });
      </script>

It's immediately start working. But why? What cause the incompatibility?

**Comment by jaredatch** [comment]
Are you getting any console errors?

**Comment by adrianmihalko** [comment]
Nothing, the console is empty:

http://gyazo.com/f876a908aa270f93874352c9ade25fad

**Comment by jaredatch** [comment]
I don't understand what you are doing with your search toggle code.

Why are you not using the event to preventDefault? What is the time out for? Why not use the slide toggle callback function instead. I think something with that code is running twice which is the issue. You should place some console.logs in your event to help debug what is double firing.

**Comment by MiguelSyll** [comment]
Hello. I had the same problem. I changed the order of the calls to js files and I got something better. Links work, but I can see the contents of may pages for a moment and the contents then disappear.

Any idea?

Here is my code:

------------------

<!DOCTYPE HTML>
<html>
    <head>
      <title>TestMenu</title>
      <meta charset="utf-8">
	  <meta name="format-detection" content="telephone=no" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
      <link rel="stylesheet" href="css/jquery.mobile-1.4.5.css" type="text/css" />
        
	  <link rel="stylesheet" href="css/index.css" type="text/css" />
	  <link rel="stylesheet" href="css/demomenu.css?v=5" type="text/css" />
	  
      <link type="text/css" href="css/jquery.mmenu.all.css?v=5" rel="stylesheet" />

     <script type="text/javascript" src="lib/jquery-1.11.2.min.js"></script>
	    
      <script type="text/javascript" src="lib/jquery.mmenu.min.all.js?v=5"></script>
	      
       <style type="text/css">
		.mm-menu li.img:after
		{
			left: 75px !important;
		}
		.mm-menu li.img a
		{
			font-size: 16px;
		}
		.mm-menu li.img a img
		{
			float: left;
			margin: -5px 10px -5px -5px;
			border-radius: 100px;
		}
		.mm-menu li.img a small
		{
			font-size: 12px;
		}
		</style>
      
     

      
      <script type="text/javascript">
      
      $(function() {
    	  $('#menu').mmenu({
				extensions 		: [ "pageshadow" ],
				offCanvas       : {
	                  position  : "right"
	                  
	               },
				counters		: false,
				searchfield		: false,
				dividers		: {
					add				: false,
					addTo			: "[id*='contacts-']",
					fixed			: true
					},
				sectionIndexer	: {
					add				: true,
					addTo			: "[id*='contacts-']"
								  },
				header			: {
					add				: true,
					update			: true,
					title			: "Menüpünkte"
								  },
				onClick		: {
					blockUI			: false,
					preventDefault	: function() {
						return this.rel != 'external';
					}
				}
			}, {
				pageSelector: 'div[data-role="page"]:first'
			});
			

			$('#menu a[rel!="external"]').on(
					'click',
					function()
					{
						
						var _t = this;
						
						$('#menu').one(
							'closed.mm',
							function()
							{
								
								$.mobile.changePage( _t.href, {
									transition: 'slide'
								});
							}
						);
						
					}
				);
			
		});
      
      $(document).on(
				'pageshow',
				function( e, ui )
				{
					$('#menu').trigger( 'setPage', [ $(e.target) ] );
					$('#menu a').each(
						function()
						{
							if ( $.mobile.path.parseUrl( this.href ).href == window.location.href )
							{
								$(this).trigger( 'setSelected.mm' );
							}
						}
					);
				}
			);
   </script>
   <script type="text/javascript" src="lib/jquery.mobile-1.4.5.min.js"></script>

    </head>
    
    <body>
    
      <div data-role="page" id="home">
				
			<div data-role="header" data-position="fixed" data-theme="b">
				
				<div data-role="navbar">
			    <ul>
			      <li><a href="#home" data-icon="home"  data-role="button" data-iconpos="notext"></a></li>
			      <li><a href="#object" data-icon="sitemap"  data-role="button" data-iconpos="notext"></a></li>
			      <li><a href="#menu" data-icon="bars" id="btn-exit" data-role="button" data-iconpos="notext"></a></li>
			    </ul>
			  </div>
			  

			</div>
				
			<div role="main" class="ui-content">
				
	        	<br>
				<h2>Startseite</h2>
				
			</div>
			<div data-role="footer" data-position="fixed" data-theme="b" style="height:20px;">
				<h6 style="padding-top:0;">
	                <div class="ui-grid-b">
	                    <div class="ui-block-a" style="text-align: left;"> v.2</div>
	                    <div class="ui-block-b" style="text-align: left;">Auswahl</div>
	                                  
	                </div>
            	</h6>
			</div>

	</div>

		
	<div data-role="page" id="object">
		<div data-role="header" data-position="fixed" data-theme="b" style="min-height: 40px;">
			<h1>Objekte</h1>
			<a href="#home" data-role="button" data-icon="forward" data-transition="slide" data-iconpos="notext" data-theme="b" data-inline="true" class="ui-btn-right">My button</a>
		</div>
	
		<div role="main" class="ui-content">
			<h1>Objekte Liste</h1>
			<ul data-role="listview" data-inset="true" data-divider-theme="a" data-filter="true">
				<li>Objekte 1</li>
				<li>Objekte 2</li>
				<li>Objekte 3</li>
				<li>Objekte 4</li>
				<li>Objekte 5</li>
			</ul>
		</div>
	</div>
      
      <div data-role="page" id="inhalt">
		<div data-role="header" data-position="fixed" data-theme="b" style="min-height: 40px;">
			<h1>Inhalt</h1>
			<a href="#home" data-role="button" data-icon="forward" data-transition="slide" data-iconpos="notext" data-theme="b" data-inline="true" class="ui-btn-right">My button</a>
		</div>
	
		<div role="main" class="ui-content">
			<h1>Inhalt Auswahl</h1>
			<h2>Bla bla bla bla</h2>
		</div>
	</div>
    
   
	
	<div data-role="page" id="detail">
		<div data-role="header" data-position="fixed" data-theme="b">
			<h1>Kategorien</h1><a href="#sync" data-transition="slideup" data-icon="home" data-direction="reverse" data-icon="back" class="ui-btn-left">Zurück</a>
		</div>
	
		<div role="main" class="ui-content">
			<div id="resultdetail"></div>
			<ul data-role="listview" data-inset="true" data-divider-theme="a" data-filter="true" id="katList"></ul>
		</div>
	</div>


 <nav id="menu">
			<ul>
				<li>
					<img src="img/basis.png" style="float:left; padding-left:15px;padding-top:5px;padding-bottom:5px;" height="25" width="25" /><span style="line-height:17px;padding-left:5px;">Basis-Funktionen</span>
					<ul id="contacts-friends">
	
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/1/" />
								Alan<br />
								<small>Thompson</small>
							</a>
						</li>
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/2/" />
								Anne<br />
								<small>Cook</small>
							</a>
						</li>
						<li>
							<span>Detail</span>
							<ul id="contacts-detail">
								<li class="img">
								<a href="#inhalt">
									<img src="http://lorempixel.com/50/50/people/7/" />
									Janet<br />
									<small>Clark</small>
								</a>
								</li>
								<li class="img">
									<a href="#inhalt">
										<img src="http://lorempixel.com/50/50/people/8/" />
										Jeffrey<br />
										<small>White</small>
									</a>
								</li>
								<li class="img">
									<a href="#inhalt">
										<img src="http://lorempixel.com/50/50/people/9/" />
										Jeremy<br />
										<small>Green</small>
									</a>
								</li>
								
						
							</ul>
	
						</li>
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/3/" />
								Carolyn<br />
								<small>Garcia</small>
							</a>
						</li>
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/4/" />
								Charles<br />
								<small>Walker</small>
							</a>
						</li>
						
						
					</ul>
				</li>
				<li>
					<img src="img/raumgeb.png" style="float:left; padding-left:15px;padding-top:5px;padding-bottom:5px;" height="25" width="25" /><span style="line-height:17px;padding-left:5px;">Räume und Gebäude verwalten</span>
					<ul id="contacts-family">
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/1/" />
								Benjamin<br />
								<small>Kelly</small>
							</a>
						</li>
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/2/" />
								Brenda<br />
								<small>Price</small>
							</a>
						</li>
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/3/" />
								Eric<br />
								<small>Hughes</small>
							</a>
						</li>
						
					</ul>
				</li>
				<li>
					<img src="img/arbeitsablaeufe.png" style="float:left; padding-left:15px;padding-top:5px;padding-bottom:5px;" height="25" width="25" /><span style="line-height:17px;padding-left:5px;">Arbeitsabläufe organisieren und überwachen</span>
					<ul id="contacts-work-colleagues">
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/7/" />
								Anthony<br />
								<small>Roberts</small>
							</a>
						</li>
						<li class="img">
							<a href="#inhalt">
								<img src="http://lorempixel.com/50/50/people/8/" />
								Daniel<br />
								<small>Gonzalez</small>
							</a>
						</li>
						
	
					</ul>
				</li>
			</ul>
	</nav>

    </body>

</html>
------------------

Miguel

**Comment by coffeeshell** [comment]
Hi, you have the same issue as here: https://github.com/BeSite/jQuery.mmenu/issues/309
Just cut all your scripts from markup and put it in your scripts file.

**Comment by MiguelSyll** [comment]
Hi cofeeshell
mmm... i cant find a solution with your answer. In the answer there is a broken link, maybe inside was the answer, isn't? 
Did you solve it? I tried to copy and paste the examples and I got the same behaviour. Content visible and then not visible.

Thanks for your Time!!!

Miguel

**Comment by coffeeshell** [comment]
With this plugin you can't use scripts inside your markup because they will execute twice. All the scripts that are wrapped by <div class="mm-page"></div> are executed twice. 
The solution is to move all your scripts outside of the mm-page div (if possible) or move them in a file (ex: script.js) and in this way the events (functions and so on) will be fired only once.
P.S. sry for my language, not my native language :)

**Comment by adrianmihalko** [comment]
Hi,

I am not a JS genius, but I found few things which works:

Workarounds:

<a href="#" onclick="searchToggle()">Search</div>

<script type="text/javascript">
  function searchToggle() {
    $('#search-div').slideToggle();
    setTimeout(function() {
      $('#search-text').focus();
    }, 0);
    return false;
  }
</script>

This works everywhere.

Second:

Add this to <head>:

              <script type="text/javascript">
        
$( document ).ready(function() {
    $( "#search_link" ).click(function() {
      $( "#search-div" ).slideToggle( "slow", function() {
        $('#search-text').focus();
    });
});
});
        </script>

Link can be now placed anywhere:

<a href="javascript:void(0)" id="search_link">Search</a>

I choosed this one.

**Comment by FrDH** [comment]
The mmenu plugin needs all content to be in one DIV, otherwise it can not slide out the "page" when opening the menu. If there are multiple DIVs, the plugin will wrap these DIVs in a new DIV, this is what causes scripts inside the DIVs to run twice.
If you have multible DIV's, but only one of them actually contains content, you can tell the plugin it should consider this DIV to be the "page" by using the `offCanvas.pageSelector` option in the configuration object: http://mmenu.frebsite.nl/documentation/addons/off-canvas.html

Inline SCRIPTs are bad, don't use them. Put all JS in a .js file and include it in the HEAD.

**Comment by MiguelSyll** [comment]
Hello everyone.

Thanks for taking your time to discuss about this issue. 

FrDH, do you a have a working example with multiple divs (pages) where offCanvas.pageSelector is used to tell the plugin which page should be showed? 

Thanks ins advance

Miguel

**Comment by adrianmihalko** [comment]
@FrDH your suggestion is better, but I can't get it work:

          <script type="text/javascript" data-no-instant>
             $(document).ready(function() {
                $("#menu").mmenu({
                   "extensions": [
                      "pageshadow"
                   ],
                   "header": {
                          "title": "Menu",
                          "add": true,
                          "update": true
                       }
                }, {
                pageSelector: "#container"
                });
             });
          </script>

Still not working. :( can you please take a look [on my site] (http://mihalko.eu?view=mobile)?

**Comment by FrDH** [comment]
`pageSelector` should be an option in the `offCanvas` object in the configuration object:
````javascript
$("#menu").mmenu({
    // options
}, {
    // config
    offCanvas: {
        pageSelector: "#container"
    }
});
````

**Comment by adrianmihalko** [comment]
Finally, thank you. :)

          $(document).ready(function() {
            $("#menu").mmenu({
                "extensions": [
                              "pageshadow"
                           ],
                           "header": {
                                  "title": "Menu",
                                  "add": true,
                                  "update": true
                               }
            }, {
                // config
                offCanvas: {
                    pageSelector: "#container"
                }
            });
          });

**Comment by MiguelSyll** [comment]
Hi,

it works better! I can change Pages. The only problem that I have now is that when I open a new page I the links do not work.

For example: I click on an element menu and a new page (a div) is showed,  The new page has only a 'Back' button (#home) but when I click on it nothing happens.

What must I do each time that I load a new page? Must I update the pageSelector dinamically? How?

Thanks

Miguel
