### ISSUE TITLE
Loading widescreen before page load

### ISSUE THREAD

**Issue by idolab** [BeSite/jQuery.mmenu#343]
Widescreen takes effect after the page is loaded (reload the http://mmenu.frebsite.nl/ and you will see the menu flashing at the left)
That is a bad user experience because for every page load they will see a "flash" of the menu.

I recommand changing this behavior that the mmenu checks the screen width before page load, however mmenu is loaded on doc.ready

**Comment by FrDH** [comment]
I don't think I understand.
The widescreen extension (like all other extensions) is CSS only. CSS takes effect immediately.
Also, there is no delay between creating the menu and activating the extensions.

**Comment by idolab** [comment]
http://g.recordit.co/tiLBoROe1P.gif

Notice the flash of the menu from the left.

**Comment by FrDH** [comment]
I see, this actually is a flash of the lack of a menu :-)
I guess you could add the class "mm-slideout" to the DIV that gets the class "mm-page". That's the classname used to push the page out to the left, it's added by the plugin onDocumentReady.
