### ISSUE TITLE
Multiple mmenus using WP plugin?

### ISSUE THREAD

**Issue by webguy262** [BeSite/jQuery.mmenu#344]
Is it possible to have two instances of mmenu using the WP plugin?

**Comment by FrDH** [comment]
Unfortunately not by using the settings page. I guess you could setup the JS for the second menu manually, but that kind of bypasses the whole idea of the WP plugin.

**Comment by webguy262** [comment]
Thought so...thanks for the quick response! 

BTW, also trying to use your terrific code on a non-wp site: http://brinsterinc.com/ibh/.

Can't figure out why the menu is not appearing correctly. See anything obvious?

**Comment by FrDH** [comment]
The error `ReferenceError: jQuery is not defined` probably has somthing to do with it.

**Comment by webguy262** [comment]
Thanks for noticing the jQuery issue!  The call was being made async. Removing the async fixed it!
