### ISSUE TITLE
Error with Magento and prototype

### ISSUE THREAD

**Issue by fusco** [BeSite/jQuery.mmenu#345]
Hi, 
I trying to install mmenu on a magento theme 
- magento v1.9.1
- personal theme
- Jquery v1.11
- no conflict used ($j) and works fine with other script
- prototype v1.7
- bootstrap v3.3.2
- mmenu v5.0.4

I construct an basic menu <ul> <li> without magento classes and i call mmenu script with a simple

       $j('#my-menu).mmenu

I display a menu link and i can open menu with slide effect but i don't  show the submenu 
I have an js error in console 

      Uncaught TypeError: this._each is not a function
             each	                                        @	prototype.js:1
              t.(anonymous function).trigger	@	jquery.mmenu.min.all.js:13
              t.(anonymous function).init	@	jquery.mmenu.min.all.js:13
              t.(anonymous function)	        @	jquery.mmenu.min.all.js:13
              (anonymous function)	        @	jquery.mmenu.min.all.js:13
              n.extend.each	                        @	jquery-1.11.0.min.js:2
              n.fn.n.each	                                @	jquery-1.11.0.min.js:2
              t.fn.(anonymous function)	        @	jquery.mmenu.min.all.js:13
              (anonymous function)	        @	scripts.js:777
              n.Callbacks.j	                        @	jquery-1.11.0.min.js:2
              n.Callbacks.k.fireWith	        @	jquery-1.11.0.min.js:2
              n.extend.ready	                        @	jquery-1.11.0.min.js:2
              K	                                        @	jquery-1.11.0.min.js:2

**Comment by FrDH** [comment]
I don't think is something I can fix.
All mmenu JS is wrapped in an anonymous function in where "$" is an alias of "jQuery".

**Comment by cmfcmf** [comment]
In case anyone has the same issue: The cause was discussed in https://github.com/BeSite/jQuery.mmenu/issues/345 and is fixed in later releases (I tried 5.5.1).
