### ISSUE TITLE
current page wordpress

### ISSUE THREAD

**Issue by ukguy** [BeSite/jQuery.mmenu#346]
, {
         classNames: {
            selected: "current-menu-item"
         }

This works in Wordpress but if you are on a parent page (which has children) mmenu opens on the child pages of the selected parent.

I think it's something to do with the "current-menu-item" being detected on ALL li elements, so mmenu goes straight to the deepest li and selects that.

Is there any way we can detect li.current-menu-item a so it's more specific?

**Comment by FrDH** [comment]
That's the intended behavior.
If you don't want the submenu of the deepest selected LI to be shown, I guess you could add the default "Selected" class to its parent LI and use that when firing the plugin:
````javascript
$(".current-menu-item").last().closest( ".current-menu-item" ).addClass( "Selected" );
$("#menu").mmenu();
````
