### ISSUE TITLE
Deprecated events

### ISSUE THREAD

**Issue by gateway7** [BeSite/jQuery.mmenu#347]
Is there any substitution for the deprecated events like "opening.mm" or any other way to monitor menu (not panels) opening & closing events? The only solution I can see at this point is binding to click events of the menu trigger button, its links, and the page content blocker, which seems pretty ugly in terms of the design and not particularly reliable. 

Thanks!

**Comment by FrDH** [comment]
Have you tried including the debugger.js script? It should tell you when you're using deprecated options and events and suggest an alternative to use.

**Comment by gateway7** [comment]
I have, but for some reason, it didn't yield any messages. Anyways, I went through the code in debugger.js, and other than saying that a bunch of events are deprecated for version 5.0, it didn't have any hints.

**Comment by FrDH** [comment]
Maybe your debugger only shows errors, not warnings?
Anyway, as of version 5.0.0 the events were replaced with an API: http://mmenu.frebsite.nl/documentation/api.html

**Comment by gateway7** [comment]
I may be missing something, but I don't see how the API provides any substitution for such events. Also, even panel opening / closing event binding it provides seem to work only with manually triggered events.

**Comment by FrDH** [comment]
The API `bind` method works a lot like jQueries `bind` method:
````javascript
var API = $("#menu").mmenu().data( "mmenu" );

API.bind( "opening", function() {
 alert( "the menu is opening" )
} );
````
A code example is given after the first few lines of text on the documentation page:
http://mmenu.frebsite.nl/documentation/api.html

The available method names are listed on that page too, and extended per add-on on its own page:
http://mmenu.frebsite.nl/documentation/addons/off-canvas.html

**Comment by gateway7** [comment]
Perfect!
Thanks!!!

**Comment by FrDH** [comment]
Do you mean this?


http://mmenu.frebsite.nl/documentation/api.html
> Possible values: "closeAllPanels", "closePanel", "getInstance", "init", "openPanel", "setSelected", "update"


http://mmenu.frebsite.nl/documentation/addons/off-canvas.html
> Possible values for the method argument in the bind method: "close", "closed", "closing", "open", "opened", "opening", "setPage".

**Comment by gateway7** [comment]
Yup. Thanks!
