### ISSUE TITLE
Swipe / drag bug with iconbar extension: you can drag the page over the icon bar

### ISSUE THREAD

**Issue by ewjmulder** [BeSite/jQuery.mmenu#349]
First of all: I love the mmenu plugin and it's various extensions! Works very well with different devices and creates a really nice looking menu in a breeze. Goed bezig! ;)

I use the iconbar extension and I think I spotted a bug, at least on my device (Galaxy Note 4, newest Android). When you have opened and closed the menu once, afterwards you can 'drag' the main page to the left over the icon bar menu, hiding it. I see this behavior also when I open the iconbar demo page on my phone:
http://mmenu.frebsite.nl/demo/index.html?demo=iconbar
The dragging is not possible before the menu has been opened and closed once. That might be a hint to the problem source.
Actually what I think is going on is that the page width is re-calculated after menu open-close and somehow the 60px width from the iconbar are added to it, so the mobile browser allows horizontal scrolling to see the extra 60px on the right. Those extra 60px are empty and useless of course, so we must try to 'convince' the browser that the page has no extra width on the right.

I hope it is clear what I mean and you can reproduce it. If not, please let me know and I'll try to attach a screenshot.

I guess this can be solved with some CSS changes. I hope you can help me with that. Meanwhile, I'll try some options myself as well.

**Comment by FrDH** [comment]
Not all options, extensions and add-ons might be compattible with one another. If you include the "debugger.js" script in your page, you'll get a warning in the console when using incompattible options, extensions and add-ons. At least, the ones I know of :-)
I'll do some testing and update the debugger if needed.

**Comment by ewjmulder** [comment]
Thanks for your reply & suggestions. I looked at the debugger and I do not have any conflicting extensions or addons. Also, it happens at your own demo page for the iconbar:
http://mmenu.frebsite.nl/demo/index.html?demo=iconbar
and I assume that has no conflicts.

It seems this bug/issue is browser dependent. I tried it on a few mobile browsers and it happens on the default Android browser and on Firefox for Android, but it does not happen on Chrome for Android and also not on Opera for Android browsers. Not sure whether it should be counted as a browser CSS bug or not. I would be nice to solve it though. So if you have any further pointers on how to solve this, thanks!

I played with it a little bit and found that the added css below solves this issue, but unfortunately introduces another one, namely that the page is always 60 pixels shorter on the right side.
```
.mm-page {
    width: -moz-calc(100% - 60px);
    width: -webkit-calc(100% - 60px);
    width: calc(100% - 60px);
}
```
I am no CSS wizard, so maybe you have another suggestion that might fix this issue?

For clarity: steps to reproduce:
1. Open http://mmenu.frebsite.nl/demo/index.html?demo=iconbar in the default Android browser or in the Firefox for android browser.
2. Open the menu
3. Close the menu
4. Now drag the main page to the left and it will overlap the iconbar. This is probably a horizontal scrolling behavior, since the browser somehow 'thinks' the main page has 60 pixels extra to the right.

**Comment by FrDH** [comment]
I've tried the `overflow-x: hidden;` before I think, it introduced more bad behavior.
I'll see If I can use the `calc()` solution, seems solid enough.

**Comment by ewjmulder** [comment]
For now I'm using ```overflow-x: hidden;``` without any further problems. Do you remember what extra bad behavior you encountered when using that? The problem with the ```calc()``` solution that I had, was that the page was indeed 60 pixels smaller: not the same background color, not taken into account for centering items, etc. But maybe it can be tweaked so that it works or I attached it to the wrong elements or ...

I'm happy to test any possible solutions that you have.

You might also consider using an online tester, like in one of these results:
https://www.google.com/webhp?q=online+android+testing
Although these all seem to be paid services, there are some that offer some free tryout time.

**Comment by FrDH** [comment]
Hmm, just checked and the iconbar extension already adds `overflow-x: hidden;` to the `body`.
I'll see if adding to the the `html` as well causes any unwanted behavior on desktop and ios.

**Comment by ewjmulder** [comment]
Ah yes, I did not notice it before. Indeed, if I remove that from the css, the horizontal scroll bar shows up on a desktop browser and the same issue applies. For me as inexperienced CSS user, it seems very weird that adding a 'do not scroll' to the html element gives a different result than adding it to the body only. But oh well, browser quirks...

Seems then that this added piece of css indeed is the way to go to solve the issue. Only weird thing is that with ```overflow-x: hidden;``` added to both html and body it still fails on Firefox for Android. I'll check to see if it disappears if I add it to even more elements. :)
