### ISSUE TITLE
New Div does not wrap the body tag entirely

### ISSUE THREAD

**Issue by ubresponsive** [BeSite/jQuery.mmenu#350]
I'm experiencing an issue where on certain pages the mm-panel div does not wrap the entire body section which results in a broken page, I have run a html validator on page but cannot see the issue.

**Comment by FrDH** [comment]
Is there an online example? Or could you post some of the HTML?

**Comment by FrDH** [comment]
Can I close this issue?

**Comment by ubresponsive** [comment]
Yes thank you

**Comment by Skalman** [comment]
I also encountered this problem. It only wraps `<div>`, and I had a `<header>` element too.
The offending code seems to be in offCanvas addon:

https://github.com/BeSite/jQuery.mmenu/blob/0472961e5966a64d7abce3139a15c3c61bc28165/src/js/addons/jquery.mmenu.offcanvas.js#L148
https://github.com/BeSite/jQuery.mmenu/blob/0472961e5966a64d7abce3139a15c3c61bc28165/src/js/addons/jquery.mmenu.offcanvas.js#L45

**Comment by Skalman** [comment]
To clarify, line 45 should be replaced by `conf.pageSelector = '> *';`.

**Comment by FrDH** [comment]
No it should not.

If you do so, SCRIPT nodes also will be considered to be content and the plugin will wrap all nodes -including the SCRIPT nodes- in a new DIV. This causes the JS inside the SCRIPT nodes to run twice.

**Comment by FrDH** [comment]
By the way, are you sure you are using the HEADER node correct?
http://html5doctor.com/the-header-element/

**Comment by Skalman** [comment]
Yes, I believe I am. The [https://html.spec.whatwg.org/multipage/semantics.html#the-header-element HTML spec] even has a `<header>` as a direct child node to a `<body>` in an example.

The JS inside the `<script>` tag will *not* run twice, at least not in Firefox or Chrome, if you do it correctly. I haven't had time to test with jQuery.mmenu, but you can easily move `<script>` nodes in a document without executing them multiple times. [http://danwolff.se/2015/jquery.mmenu/ Example page]:

```html
<head>
<script>
$(function () {
  $('#inline-script, #external-script').attr('myattr', 'before second run?');

  var wrapper = $('<div id="wrapper">');
  wrapper.append($('body > *'));
  wrapper.appendTo('body');
});
</script>
</head>
<body>
<script id="inline-script" myattr="initial">
  var val = $('#inline-script').attr('myattr');
  console.log('inline script', val);
  $('#inline-script').attr('myattr', 'after first run');
</script>
<script id="external-script" src="script.js" myattr="initial"></script>
</body>
```

You'll notice in the console, that you only have two messages: `inline script initial` and `external script initial`. If it was run multiple times, you'd expect something more.
