### ISSUE TITLE
bower.json error

### ISSUE THREAD

**Issue by wccsp** [BeSite/jQuery.mmenu#351]
Getting an EMALFORMED error when trying to install via bower. Error Details: Unexpected token ]

**Comment by LudoVio** [comment]
remove the "," at the end of the line 6

**Comment by FrDH** [comment]
My bad, must have been looking into the sun when typing that.
Should be fixed.

**Comment by wccsp** [comment]
You may have to re-tag the release in order for the bower file to work appropriately, not sure.

**Comment by jhonparedes** [comment]
I get the same issue as well. 

![screen shot 2015-04-30 at 3 09 02 pm](https://cloud.githubusercontent.com/assets/5641734/7423514/e56a19d0-ef4a-11e4-840b-4649f88228c4.png)

**Comment by LudoVio** [comment]
you changed a comma so if you want to respect semver you are now in 5.1.1 :)
also you should add an "ignore" entry or bower will complain

**Comment by matgargano** [comment]
Please re-release 5.1.1 thanks.

**Comment by FrDH** [comment]
done
