### ISSUE TITLE
navbars add-ons not working

### ISSUE THREAD

**Issue by phamtony** [BeSite/jQuery.mmenu#352]
So I've been using the plugin for a responsive site I'm building (great plugin by the way!), and wanted to add some nav headers and nav footers on to the navigation. I followed on adding the navbars object into the mmenu to a tee, just like how it's shown in the example, but nothing shows up. I tried adding a navbar  header to your advanced.html demo and it didn't work as well. Do you know if it's a conflict between features?

**Comment by FrDH** [comment]
The advanced demo already has a navbar header. So I'm not sure what you're trying to accomplish.

**Comment by phamtony** [comment]
Opps, looks like I may have altered the advanced.html. I downloaded the latest version and long and behold, the header is there. Sorry for the trouble and thank you!
