### ISSUE TITLE
Toggles are positioned wrong when 'slidingSubmenus' option is set to false.

### ISSUE THREAD

**Issue by madrabaz** [BeSite/jQuery.mmenu#354]
If 'slidingSubmenus' option is set to false and toggles add-on is enabled, opening a child menu changes the position of the toggle button of the parent.

![toggle-positioning-bug](https://cloud.githubusercontent.com/assets/3491078/7473329/0f7daf42-f343-11e4-94d6-83fe849c91cd.PNG)

**My workaroun/solution for this issue is**
```diff
---
 src/scss/addons/jquery.mmenu.toggles.scss | 3 ++-
 src/scss/jquery.mmenu.oncanvas.scss       | 2 +-
 2 files changed, 3 insertions(+), 2 deletions(-)

diff --git a/src/scss/addons/jquery.mmenu.toggles.scss b/src/scss/addons/jquery.mmenu.toggles.scss
index 9bc6fc5..bb9cfa1 100644
--- a/src/scss/addons/jquery.mmenu.toggles.scss
+++ b/src/scss/addons/jquery.mmenu.toggles.scss
@@ -17,7 +17,6 @@ label.mm-check
 {
 	margin: 0;
 	position: absolute;
-	bottom: 50%;
 	z-index: 2;
 	
 	&:before
@@ -34,6 +33,7 @@ label.mm-toggle
 	width: $mm_toggleWidth;
 	height: $mm_toggleHeight;
 	margin-bottom: -( $mm_toggleHeight / 2 );
+    margin-top: ($mm_btnSize - $mm_toggleHeight) / 2;
 
 	&:before
 	{
@@ -53,6 +53,7 @@ label.mm-check
 	width: $mm_checkWidth;
 	height: $mm_checkHeight;
 	margin-bottom: -( $mm_checkHeight / 2 );
+    margin-top: ($mm_btnSize - $mm_checkHeight) / 2;
 
 	&:before
 	{
diff --git a/src/scss/jquery.mmenu.oncanvas.scss b/src/scss/jquery.mmenu.oncanvas.scss
index 4267aad..6a8625a 100644
--- a/src/scss/jquery.mmenu.oncanvas.scss
+++ b/src/scss/jquery.mmenu.oncanvas.scss
@@ -103,7 +103,7 @@
 .mm-listview .mm-vertical .mm-panel
 {
 	display: none;
-	padding: $mm_padding 0 $mm_padding $mm_padding;
+	padding-left: $mm_padding;
 
 	.mm-listview > li:last-child:after
 	{
-- 
```
![toggle-positioning-fix](https://cloud.githubusercontent.com/assets/3491078/7473820/6d5d9ad4-f346-11e4-8c74-6d47a02c3dc5.PNG)

**Comment by FrDH** [comment]
Thanks for pointing this out to me.
This same issue occurred with the ">" arrows, I fixed this by using a similar calculation for vertical submenus only.

Note that `$mm_btnSize` is the default height for list items with a single line of text, if a second line of text is added (with a `<br />` or when the multiline extension is used), this calculation will not center the toggles.

Anyway, I'll implement the fix it in the next version.
