### ISSUE TITLE
implement multi searchfield

### ISSUE THREAD

**Issue by vtproduction** [BeSite/jQuery.mmenu#355]
Hi dude,
I'm playing with your searchfield component. With the 'addTo' option, i can add the searchfiled to specific sub-menu, but i don't find the option to implement searchfield to more than one menu (I'm trying to add 2 searchfield to 2 indepedent sub-menu, which search the value within this sub-menu's scope).
Could you tell me how to work with this idea ?

**Comment by FrDH** [comment]
For the `searchfield.addTo` option, you can specify either `"menu"`, `"panels"` or any jQuery selector. So try something like `"ul.add-searchfield"` or `"ul#first, ul#second, ul#third"`.

**Comment by vtproduction** [comment]
it worked perfectly, thankyou !
