### ISSUE TITLE
Hide menu on larger resolutions?

### ISSUE THREAD

**Issue by Jakob96** [BeSite/jQuery.mmenu#356]
Hi! I'm currently builing a responsive page with two menus (ul). The mmmenu should be hidden on larger resolutions than 400px.

Normally I use media quaries with luck but can't get it to work with this plugin. The menu still takes up space on the page in all resolutions anyway (when the menu id for mmenu is 'display:none'), just as if it was there but it isn't. 

Hope someone can help me a bit :)

**Comment by FrDH** [comment]
Try the `clone` configuration option.
Have a look at the tips and tricks: http://mmenu.frebsite.nl/support/tips-and-tricks.html

**Comment by Jakob96** [comment]
Thanks, but I don't wanna clone it because I already have two menus.

**Comment by FrDH** [comment]
This sounds pretty odd, you should be able to not show the menu with `display: none;` like you normally would.
Have you tried adding `!important`?

If that also doesn't work, is there an online example?

**Comment by Jakob96** [comment]
Succeeded to hide it on desktop version now by changing <code>pageNodetype</code> but when I have <code>display:none;</code> on the normal site the menu doesn't open on the mobile site when clicking on the link who refers to the mmenu-id.

What's the best thing to do?

**Comment by FrDH** [comment]
I don't think I understand the situation, an online example would be very helpfull.

**Comment by Jakob96** [comment]
It works now, thank you :)

Hovever, the icons in the menu footer aren't showing up with this code:
<code>
navbars: [
                  {
                     position: "bottom",
                     content: [
                        "<a class='fa fa-facebook' href='http://www.facebook.se'></a>",
                        "<a class='fa fa-twitter' href='http://www.twitter.com'></a>"
                     ]
                  }
               ],
</code>

**Comment by FrDH** [comment]
The plugin doesn't really do anything with the fontawesom CSS, so I don't think there is much I can do to help with that.
