### ISSUE TITLE
body is displaced down by 32px

### ISSUE THREAD

**Issue by joseluis** [BeSite/jQuery.mmenu#357]
After upgrading to the last version 5.1.2, from 5.01, now the body is displaced down 32px when mmenu is closed.

In many projects I give the body 100% height, and a fixed footer, so the footer is now partially hidden. As a workaround I have to give the body a negative top-margin.

**Comment by FrDH** [comment]
Is there an online example? I can't think of any changes I made as of 5.0.1 that would cause this behavior.

**Comment by joseluis** [comment]
Yes, you can [take a look here](http://medula.demo.andamira.net/), it's the simplest one I have.

I've not added a negative margin to the body there.

**Comment by FrDH** [comment]
The 32px offset comes from the div#site-content-wrapper.
I don't think this is due to a new version of the mmenu plugin.

You can easily fix this by adding a 1px padding-top to the div#page-wrapper.

**Comment by joseluis** [comment]
You're absolutely right. Thank you for the fixup and please accept my apologies. I must've changed something else at the same time as mmenu without noticing.
