### ISSUE TITLE
How to retain the navbar when the menu is active?

### ISSUE THREAD

**Issue by cheestudio** [BeSite/jQuery.mmenu#358]
Hello,

First off, LOVE the plugin! It's perfect in almost every way.

One thing I could not figure out is how to generate a navbar/toggle bar automatically. So I created one on my own and have a trigger generated to open the menu. The navbar/trigger is fixed to the top of the screen so it's always accessible. The problem is that if you are scrolled down from the top of the page and open the menu, the navbar disappears completely, but does return if you close the menu. Any idea on why this is?  Example URL:

http://turtlerockpreschooldev.com/about-us/ (please resize or emulate mobile to see the menu)

**Comment by FrDH** [comment]
The navbar (or any button that opens the menu) is not generated by the plugin, you need to do that manually.
If your navbar (or any other element) has `position: fixed`, try using the "fixedElements" add-on.

**Comment by cheestudio** [comment]
Ah, I missed that Add On! Thank you, sir!
