### ISSUE TITLE
Typo3 Compatibel

### ISSUE THREAD

**Issue by jenda77** [BeSite/jQuery.mmenu#360]
Hello, 

unfornutanely, your great extension does not work with Typo3 - or I cannot set the right thing. Could you look at this what is wrong there? It should be displayed when the page is getting showed on mobile phone. 

http://dev.hee-rechtsanwaelte.de/startseite.html

My code is: 

$(document).ready(function() {
      $('#navigation').mmenu({
         slidingSubmenus: true,
         searchfield: true
      });
      var API = $('#navigation').data('mmenu');
      $('#mobilnavi a').click(function() {
         API.open();
      });
   });

I would be very thankful for any help. Thanks by now. Jan

**Comment by FrDH** [comment]
I just tried and the menu seems to be working ok. Is this issue still actual?

**Comment by jenda77** [comment]
Thank you. I have fixed the issue. You can close it here. Thank you for your answer.
