### ISSUE TITLE
Page navigation in jQuery mobile

### ISSUE THREAD

**Issue by phelgren** [BeSite/jQuery.mmenu#363]
This is similar to the issue stated in #323 and I created a very simple example to hopefully reveal the issue.  I know you stated that you aren't a "big fan" of JQM but it is a pretty well established framework and it would be great if you could sort out the issue so I could use mmenu with JQM. I like how it looks and how it behaves.

I have two examples:  

This one: "http://petesworkshop.com/mmenu_demo/default_mobile.html" is pretty standard JQM.  Each link navigates to a new "page".  

This one is exactly the same except I have added the css and javascript for mmenu: "http://petesworkshop.com/mmenu_demo/default.html

The menu looks great but none of the links navigate to the "page" (just a hidden div by JQM standards)

Even if you can't fix it, perhaps a hint of where to start looking?  I'll keep trying, hit or miss, but a fix or a clue might help.

Thanks

**Comment by FrDH** [comment]
As I mentioned in issue 323, I don't know much about jQ mobile. I'd suggest asking this question on Stackoverflow.com

**Comment by FrDH** [comment]
I'm currently working on a "framework wrapper" for jq mobile. Basically, it should be a fix for this issue w/o you having to do any extra work. Stay tuned for the update.

**Comment by phelgren** [comment]
Thanks.  I'll look forward to the fix!

**Comment by FrDH** [comment]
As of version 5.4.1, there's a "framework wrapper" for jQ mobile:
http://mmenu.frebsite.nl/documentation/framework-wrappers.html

Give that a try, should make mmenu work in jQ mobile out of the box.
