### ISSUE TITLE
Mmenu SearchField to use Google Search

### ISSUE THREAD

**Issue by hauareyou** [BeSite/jQuery.mmenu#364]
I want the search field to display the google search "<gcse:search></gcse:search>". How can I get this to display correctly.

**Comment by FrDH** [comment]
Havent tested it, but I guess you could use the navbars addon and specify `"<gcse:searchbox></gcse:searchbox>"` for the content:
````javascript
$("#menu").mmenu({
    navbars: [{
        position: "top",
        content: [ "<gcse:searchbox></gcse:searchbox>" ]
    }]
});
````

Note that for this to work, mmenu needs to be fired before google does its magic.
