### ISSUE TITLE
Customize or Remove First Menu Title -- Version 5.2.0

### ISSUE THREAD

**Issue by kriskd** [BeSite/jQuery.mmenu#365]
I've been reading documentation and issues and I'm still unclear as to how to either remove the first .mm-title that defaults to the word "Menu" or customize it.  I've seen references to the navbars addon and using the 'header' option.  I feel this must not be difficult.  Any assistance appreciated.

**Comment by FrDH** [comment]
First, the `header` and `footer` add-ons have been replaced with the `navbars` add-on. So if you're using the latest version of the plugin, forget about the `header` add-on.

Second, the `navbars` add-on uses (or "inherits") the default `title` (and its behavior) from the `navbar` option (note the slightly different name).

So basically, this should do the trick:
````javascript
$("#menu").mmenu({
    navbar: {
        title: "my custom title"
    },
    navbars: [{
        position: "top",
        content: ["prev", "title"]
    }]
});
````

`navbar` options:
http://mmenu.frebsite.nl/documentation/options/#h1

`navbars` add-on options
http://mmenu.frebsite.nl/documentation/addons/navbars.html#h2

**Comment by kriskd** [comment]
Thank you, this worked well.  I ended up setting title to an empty string to get rid of that initial title completely.

**Comment by m-salim** [comment]
@kriskd  thank you, as I was looking how to remove the initial title. Leaving with empty string did the job.

Many thanks

**Comment by Dedrago** [comment]
Sorry, a bit dummy. Where should I put this code?

**Comment by claudchan** [comment]
Hi,
I am looking for this to remove the initial title but it leave an empty space. Is there workaround or option to remove the empty space entirely instead?

**Comment by moyarich** [comment]
i removed the empty space with the css below
~~~css
.mm-panels .mm-hasnavbar:first-child{
  padding-top:0;
}

.mm-panels .mm-hasnavbar:first-child  .mm-navbar + .mm-listview{
 margin-top:20px;
} 
~~~
