### ISSUE TITLE
jquery.mmenu.offcanvas.min.js missing from Bower

### ISSUE THREAD

**Issue by charlievaughan** [BeSite/jQuery.mmenu#366]
Hi there

I was trying to configure menus with different positioning, without much luck, using the Bower release of mmenu.

After some debugging I noticed jquery.mmenu.offcanvas.min.js isn't included in the Bower release but is in this Git repo.

I've tried adding the missing file and code to my codebase manually but JS error messages are being returned:

<code>Uncaught TypeError: Cannot read property '$blck' of undefined</code>

**Comment by FrDH** [comment]
The `main` option points to the ".all" .js and .css files, those files have the offcanvas add-on included.
