### ISSUE TITLE
Don't want to have additional classes on menu items

### ISSUE THREAD

**Issue by ravbetsky** [BeSite/jQuery.mmenu#368]
Hi!
I want to use your plugin only for sliding menu from left... But I don't see any options to prevent plugin add classes like 'mm-'. So i have to use {classNames: null} It's not good because I get js error in this case.

Please add a possibility to turn off all your cool features and let the developer use it only for sliding.

Thanks!

**Comment by FrDH** [comment]
> By default all ULs will automatically be styled like an app-menu. If you don't want an UL to be styled like an app-menu, add the class "mm-nolistview" to it.
http://mmenu.frebsite.nl/tutorials/basic/styling-lists.html

Does that help?
