### ISSUE TITLE
Position right and widescreen plugin not working together

### ISSUE THREAD

**Issue by brewern** [BeSite/jQuery.mmenu#369]
I am trying to use the menu positioned right while also using the widescreen plugin, so that it's open by default at a larger media query. This doesn't seem to be working. I get a blank area on the left where the menu would normally be, instead of being open on the right.

The margin-left on mm-slideout should be a margin-right when position right is used. Am I missing something?

**Comment by FrDH** [comment]
The widescreen add-on will always assume the menu to be positioned on the left.
I'll see if I can force the menu to be positioned on the left in the next version.

Thanks for pointing out the issue.

**Comment by FrDH** [comment]
Should be fixed in the current version.
