### ISSUE TITLE
Menu "back" navigation is broken in IE9

### ISSUE THREAD

**Issue by jawinn** [BeSite/jQuery.mmenu#370]
This is the same issue described here (the comments were on a closed item, so re-opening as a new issue): https://github.com/BeSite/jQuery.mmenu/issues/157#issuecomment-87583352 

This is broken on http://mmenu.frebsite.nl/
To replicate using Internet Explorer 9:
- Click menu
- Click on arrow to view any tiered item such as "Tutorials"
- Click the back arrow at the top

The menu heading text changes, but the menu items do not change back.

Confirmed as still broken using the latest files and the example HTML.

NOTE: I was able to get the "hack" fix in the above link to work in the meantime. It did require targeting ".mm-navbar .mm-btn" instead of ".mm-header .mm-btn".

**Comment by FrDH** [comment]
That's pretty odd. If the title changes, this means the `openPanel` method is fired. 
Unfortunately, I don't have access to a computer with IE9 and can't do much debugging.
Could you try and pinpoint where IE9 stops working? Just add a few `console.log`s somewhere between line `140` and `170` in `jquery.mmenu.oncanvas.js`.
Thanks in advance.

**Comment by Miw0** [comment]
Any updates about this issue?

**Comment by joebanks10** [comment]
I'm having this issue as well. Can't debug for you, but hope this gets resolved soon.

**Comment by rburch** [comment]
Same issue here.

**Comment by wallybh** [comment]
Hi! @FrDH.

I'm debuging on IE9 to find out where is the problem and I think I found it. The openPanel trigger don't add the class mm-hidden to the current panel. In your code, you are removing the $current panel from the array of panels before you add the class mn-hidden. When I comment that part of code, the back button works perfectly in IE9. 

This are happening in all browsers, but just in IE9 this is a problem.

Here is the piece of code that changed (jquery.mmenu.oncanvas.js):
![image](https://cloud.githubusercontent.com/assets/593137/8708480/a0c2f21c-2b12-11e5-88f5-05a979bf2585.png)

I clicked in all menus and submenus in my application, and for me this is resolved. But I don't now if that alteration will impact in others parts of code.

If everyone wants to see my commit I created a pull request to this repository.

PS.: I apologize for not being word-perfect in English.

**Comment by FrDH** [comment]
Issue should be fixed in version 5.3.4
Could anyone check?

Note, panels don't animate on IE9, as IE9 has no support for transitions. Instead, the panel immediately becomes visible.

**Comment by wallybh** [comment]
Hi, @FrDH!

I pulled and tested it in IE9. It's working fine here.

**Comment by rburch** [comment]
Fixed for me too! Great job!
