### ISSUE TITLE
WP plugin: Notice: register_uninstall_hook was called incorrectly

### ISSUE THREAD

**Issue by webguy262** [BeSite/jQuery.mmenu#371]
Your plugin is OUTSTANDING! 
But it's giving me this issue...

Notice: register_uninstall_hook was called incorrectly. Only a static class method or function can be used in an uninstall hook. Please see Debugging in WordPress for more information. (This message was added in version 3.1.) in /nfs/c11/h01/mnt/200192/domains/farbest.com/html/wp-includes/functions.php on line 3560.

Your plugin has this line...
register_uninstall_hook( 	__FILE__, array( $this, 'uninstall' ) );

Which apparently is not the current way to code this function. Reference is here...
http://codex.wordpress.org/Function_Reference/register_uninstall_hook

Sorry I can't fix on my own... I'm sure you can!

**Comment by FrDH** [comment]
Thanks for pointing this out to me. I'll have a look at it and fix it in the next version.
The uninstall hook doesn't do anything yet, so it should have no effect anyway.

**Comment by webguy262** [comment]
Sorry, but it does seem to have an effect b/c one of my key plugins -- https://wordpress.org/plugins/custom-post-type-pdf-attachment/ -- does not work when mmenu is enabled.  Can you send me the fix so I can to patch my version and launch my site? Client is ANXIOUS! And you can make sure the fix works, at least in my case.

**Comment by FrDH** [comment]
Are you sure this is due to the `register_uninstall_hook`? Sounds odd to me, but then again, WordPress has its oddities I guess.
For now you can simply remove the line where it is called. I'll upload a new version later on.

**Comment by FrDH** [comment]
I uploaded a new version (1.0.1) that uses the preferred "uninstall.php":
http://mmenu.frebsite.nl/wordpress-plugin.html

**Comment by webguy262** [comment]
Just to close the loop. The new MMenu version has A LOT of changes from mine, and since I probably hacked something in my version, I'm keeping it for now until I can make sure I don't lose anything in the upgrade.
I did comment out the uninstall hook as you suggested earlier, and that did eliminate the issue with my other plugin. Not sure why, but it's working. Thanks for a great plugin!
