### ISSUE TITLE
Change width of submenus

### ISSUE THREAD

**Issue by nanu-miguel** [BeSite/jQuery.mmenu#372]
Fantastic plugin and many thanks for making it available!! This is more of a request than an issue.  Is it possible to make the width of the submenu's less than that of top parent menu?  For example I am using the menu with an Iconbar, but would like the icons to be in view and clickable when a user goes down into lower levels.  Is it possible to modify the width of the submenus without affecting the width of the top menu?  Many thanks for your help in advance.

**Comment by FrDH** [comment]
Cool idea, I'll see if I can create an add-on for this behavior.

**Comment by FrDH** [comment]
Check out the new add-on "iconPanels":
>  If you want a small part of the parent panel to always be visible (most commonly when you're using icons), include the "iconPanels" add-on .js and .css files and use the iconPanels options.

http://mmenu.frebsite.nl/documentation/addons/icon-panels.html

Actually using icons is not required... :)

**Comment by nanu-miguel** [comment]
Great update Fred! This will be very useful to a lot of people I suspect so thanks very much for taking the time to produce this add on.  I am currently working with your menu and have adapted it to suit certain requirements.  I will get a link up when its completed, I think it looks well.  May also have to pick your brains about the cloning option.

**Comment by FrDH** [comment]
Hmm, there seems to be an issue when opening a submenu after having scrolled down.
