### ISSUE TITLE
em.mm-counter position is wrong

### ISSUE THREAD

**Issue by Patta** [BeSite/jQuery.mmenu#373]
the position of the em.mm-counter is right: 45px, but better is right: 70px

image added

![emcounter](https://cloud.githubusercontent.com/assets/2151127/7879956/660fcb46-05f5-11e5-816b-d8bf04c849b5.png)

**Comment by FrDH** [comment]
Not exactly, the border for the button should be positioned left of the counter. As can be viewed in the documentation example: http://mmenu.frebsite.nl/documentation/addons/counters.html

I'm not sure why the behavior is different on your site, is there an onine example?

**Comment by Patta** [comment]
oh ok, its my mistake. i use this global style: 
* { box-sizing: border-box;} 
and this gives the "error".

thanks for your feedback!

**Comment by FrDH** [comment]
Ah yes, the wildcard selector...
