### ISSUE TITLE
top fixed site header is hidden if mmenu is opened

### ISSUE THREAD

**Issue by Patta** [BeSite/jQuery.mmenu#374]
i have an fixed site header with style="position:fixed,top:0px; height:120px;z-index:40,..." if the page is scrolled down (like 50%) and mmenu is opened via an icon in the site header, the site header is hidden or the fixed position with top 0px isn't working anymore. are there any known issues?

**Comment by FrDH** [comment]
Have you tried searching the tips and tricks page?
http://mmenu.frebsite.nl/support/tips-and-tricks.html

> If your page contains elements that have position: fixed; that suddenly seem to disappear when opening the menu, have a look at the fixed elements add-on.
http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html

**Comment by Patta** [comment]
thx!
