### ISSUE TITLE
#mm-blocker styles all elements to display:none;

### ISSUE THREAD

**Issue by Sanafan** [BeSite/jQuery.mmenu#375]
Hey guys,
just facing a curious issue. All my divs get a `display: none;` and i don't know why exactly. I figured out, that when i set `#mm-blocker's display: none;` to `display: block;` anything works fine, without the mmenu then. Maybe someone here has an idea.

**Comment by FrDH** [comment]
That sounds really odd, is there an online example?

**Comment by Sanafan** [comment]
No, sorry - there isn't. I'm going to give you detailed information at the next weekend. No time for that before, sorry.

**Comment by FrDH** [comment]
Any updates? Or can I close this issue?
