### ISSUE TITLE
Using Fixed addon causes element to disappear entirely.

### ISSUE THREAD

**Issue by treykane** [BeSite/jQuery.mmenu#376]
I'm really liking your plugin, and it makes working with an off canvas menu much easier.  However, the page I'm working on has a fixed header.  

I have seen and implemented the fixed elements add-on.   The issue I'm running into now, is that when I add the class "Fixed" to my element it disappears from the page entirely. Any idea what is going wrong here?  My menu is a child within the fixed header, but I'm not sure if this is playing a factor?

**Comment by cmathieu333** [comment]
I'm having a similar issue. But instead of disappearing it's moving my fixed element to the bottom of the page. Has anybody run into this?

**Comment by FrDH** [comment]
The plugin uses `transform: translate3D( 80%, 0, 0 )` to slide the page out to the right. This CSS property makes the page behave like a "viewport", so all elements inside it with `position: fixed` will become positioned relative to the page.
To prevent this, the fixedElements add-on moved these elements out of the page and add the class "mm-slideout" to them.
Without an online example, there isn't much more I can tell you about these issues.

**Comment by cmathieu333** [comment]
Here's dev page showing the issue http://marathon.newbreedmarketing.com/mmenu-test , you can see it starts at the top but then jumps down to the bottom of the page.

I'm using the following code to trigger it.

$("div#hs_menu_wrapper_top_menu").mmenu({
         // options
      }, {
         // configuration
         classNames: {
            fixedElements: {
               fixed: "header-container-wrapper"
            }
         }
      });

It's worth noting that when I went the route of using jQuery to assign a class of "Fixed" to that element it caused it to disappear completely as treykane described above.

Thanks for your help!

**Comment by treykane** [comment]
I am seeing the same result when I place the class "Fixed" on my inner wrapper.  If I place it on the actual fixed element that is the parent of the wrapper thats when it vanishes entirely.

**Comment by FrDH** [comment]
Note that the plugin removes the classnames specified in the `classNames.fixedElements.fixed` configuration option and replaces it with `mm-slideout`. That makes any CSS for `.header-container-wrapper` stop working.

My advice would be to add the classname `Fixed` to the element instead of changing the `classNames.fixedElements.fixed` configuration option.

**Comment by zuhloobie** [comment]
@treykane  - this just happened to me and after pulling my hair out, I found that I had forgotten to add `position:fixed; top:0; left:0;` to my fixed element's CSS. Works now...
