### ISSUE TITLE
Missing CSS in jquery.mmenu.all.css

### ISSUE THREAD

**Issue by nyubbie** [BeSite/jQuery.mmenu#378]
Just downloaded this latest version -- I think you're missing a few CSS styles for the mobile list view, like mm-header, etc.

This occurs in jquery.mmenu.all.css.

**Comment by FrDH** [comment]
The header add-on has been replace with the navbar add-on, most of its CSS is now in the integrated in the core because it is also used for the header/title above subpanels if you don't use the navbars add-on.
