### ISSUE TITLE
menu anchors not working

### ISSUE THREAD

**Issue by mkaragosian** [BeSite/jQuery.mmenu#379]
I have a responsive menu that uses mmenu with Wordpress. The menu links are anchors that point to locations on a single page.  When I click on one of the menu anchors the page correctly moves to the right position on the page.  But when I close the menu, the page view jumps back to the top instead of remaining at the anchor.  The URL still includes the anchor, however.  How can I retain page position and prevent the jump back to the top of the page?

**Comment by FrDH** [comment]
Have a look at the "one-page" example:
http://mmenu.frebsite.nl/examples.html (it's the 8th example)

**Comment by mkaragosian** [comment]
Thanks for your fast response.  (Certainly faster than me...)  Your example online works brilliantly.  The implementation in my Wordpress theme (by others) does not.  I attempted to modify the code that first calls mmenu following your example.  The error console shows "TypeError: undefined is not a function..." when evaluating this line:
"API.setSelected( $mobileMenu.find( "li" ).first() );"
The version of mmenu is 4.1.9.
Any thoughts?

The full function as implemented in the theme (added code after the comment with date):
	// Main Function
	if (jQuery("body").hasClass('mobile-enabled')) {
		jQuery("body").addClass( "mobile-on" );
		
		// Build out our mobile menu
		var $primaryMenu = '', 
			$secondaryMenu = '',
			$socialMenu = '',
			$searchForm = '';
		
		if (jQuery('.menu-primary').length) { var $primaryMenu = jQuery('.menu-primary').html(); }
		if (jQuery('.menu-secondary').length) { var $secondaryMenu = jQuery('.menu-secondary').clone(true).find('li.backtotop, li.toggle-menu').remove().end().html(); } 
		if (jQuery('.social-list .social-icons').length) { var $socialMenu = jQuery('.social-list .social-icons').html(); }
		if (jQuery('.social-list .search').length) { var $searchForm = '<div class="social-list search">'+jQuery('.social-list .search').html()+'</div>'; }
		
		var $mobileMenu = jQuery('<nav id="mobile-menu"><div>'+$searchForm+'<ul>'+$primaryMenu+'</ul><ul>'+$secondaryMenu+'</ul><div id="menu-inner"><div class="social-list social-icons mm-list">'+$socialMenu+'</div></div></div></nav>');
		
		jQuery($mobileMenu).mmenu({
			// Options
		}, {
			// Config
		});
		
		// added for single page operation 2015-06-20
		var API = $mobileMenu.data( "mmenu" );
		API.setSelected( $mobileMenu.find( "li" ).first() );

		var closer = null;

		$mobileMenu.find( 'a' ).on( 'click', function() {
			closer = $(this).attr( "href" );
		});

		API.bind( "closed", function() {
			if ( closer ) {
				setTimeout( function() {
					$html.animate({
						scrollTop: $(closer).offset().top
					});	
					closer = null;
				}, 25 );
			}	
		});
	}

**Comment by FrDH** [comment]
The API was introduced in version 5.0.0
http://mmenu.frebsite.nl/documentation/changelog.html

In earlier versions, the plugin used custom events.
