### ISSUE TITLE
Unable to determine blocker css

### ISSUE THREAD

**Issue by filip-van-hoeckel** [BeSite/jQuery.mmenu#380]
Currently the #mm-blocker makes our site background looks like it changes the opacity of the site, in order to improve the contrast of the menu. I'd like to disable this behaviour, but have been unable to find the css causing this, even after extensive debugging. Please advise, thanks.

**Comment by filip-van-hoeckel** [comment]
Nevermind, found it; now I have a different issue: clicking the close btn does not close the mmenu.

**Comment by FrDH** [comment]
This issue is to vague for me to answer (what button? where is it?), could you provide an online example?

**Comment by filip-van-hoeckel** [comment]
You're right, sorry for that. In the meantime I managed to solve this. For others experiencing this issue, if you use the default close btn but choose to meddle with css for #mm-blocker: don't ;-)
