### ISSUE TITLE
Callback not working

### ISSUE THREAD

**Issue by Licoti** [BeSite/jQuery.mmenu#381]
Hi,

I don't know if it's normal, but, in the new version > 5.0 the callback dosen't work anymore, (but still working on  v4.7.5)

Bug example for the opening :
      $('#foo').on('opening.mm', function() {
        alert("hello");
      });

If you have a solution :)

**Comment by FrDH** [comment]
As of version 5, all events have been refactored to API methods
http://mmenu.frebsite.nl/documentation/api.html

Your new JS would look something like this:
````javascript
var $menu $("#foo").mmenu();
var API = $menu.data( "mmenu" );

API.bind( "opening", function() {
    alert( "hello" );
});
````

**Comment by Licoti** [comment]
Oh thank you, I was used to the old version :(
