### ISSUE TITLE
Unrecognized syntax error for href='#...'

### ISSUE THREAD

**Issue by 2ooom** [BeSite/jQuery.mmenu#382]
See the [fiddle](https://jsfiddle.net/8t2q5gwr/1/), whenever clicking on the items starting with '#' jquery Sizzle fires the error:

    Sizzle.error = function( msg ) {
	    throw new Error( "Syntax error, unrecognized expression: " + msg );
    };

Although the execution is not affected and the page loads as expected in all cases the error is really annoying. Reproducible in any browser.

**Comment by FrDH** [comment]
Will be fixed in the next bugfix version.

**Comment by 2ooom** [comment]
Thanks, are there any workarounds meanwhile?

**Comment by FrDH** [comment]
You van wrap the code in a try/catch.

**Comment by 2ooom** [comment]
Not sure how can do that, say for given example

**Comment by FrDH** [comment]
You can ignore the error. Just because Sizzle throws an error, doesn't stop it from working.

**Comment by FrDH** [comment]
Should be fixed in the latest version.

**Comment by 2ooom** [comment]
Thanks! 5.3.1 resolves the issue
