### ISSUE TITLE
Open submenu directly

### ISSUE THREAD

**Issue by leone510es** [BeSite/jQuery.mmenu#383]
I'm using the mmenu for my website. It has many pages and subpages with 2-3 levels. The problem is when I am on a subpage and I want to select an other page from the menu from the the same menu level, I only want to show the submenus for the page. 
Menu example:

* Home
* Services
  * service 1
  * service 1
  * service 3
* About
  * gallery
  * details
* Contact

So if I am on 'Service 1" page and if I open the menu I want to directly open the Services submenu, not the main menu. Because now if I want to select "Service 2" I have to open the menu, select "Services" submenu and only after that I can select "Service 2"

Is it possible to open the menu directly with a submenu?

**Comment by FrDH** [comment]
Have you tried the basic tutorial?
> To make a LI visibly selected, add the class "Selected" to it.

http://mmenu.frebsite.nl/tutorials/basic/styling-lists.html

**Comment by apptaro** [comment]
Hi, I have the same requirement. It is easily possible by something like this:
```javascript
var mymenu = $("#my-menu");
var current = mymenu.find("a[href=service1]").closest("li");

mymenu.mmenu();
var api = mymenu.data("mmenu");
api.setSelected(current);
api.openPanel(current.closest(".mm-panel")); // pre-open the panel containing the current item
```

**Comment by FrDH** [comment]
Or, as I suggested in the previous comment, you can add the class "Selected" to the LI.
