### ISSUE TITLE
Destroy mmenu

### ISSUE THREAD

**Issue by Dinfyru** [BeSite/jQuery.mmenu#385]
How can i destroy menu? I have responsive site and i need destroy menu in desktop mode.

**Comment by FrDH** [comment]
No you can't destroy the menu.
For responsive layouts, it is recommended to use the `clone` configuration option:
> If you only want to use the jQuery.mmenu plugin for the menu on a smaller screen, don't try to destroy and (re)create the menu onWindowResize. That won't work because the plugin makes a lot of modifications to the HTML that can not be reverted. Instead, you should clone the menu and use CSS to show and hide either the original or cloned menu.

http://mmenu.frebsite.nl/support/tips-and-tricks.html

**Comment by Dinfyru** [comment]
This is bad.

**Comment by FrDH** [comment]
Care to elaborate on why you think this is bad?
The `clone` config option works like a charm if I may say so myself.
