### ISSUE TITLE
Open Menu by default on page load when the page is big like the demo site

### ISSUE THREAD

**Issue by vanduzled** [BeSite/jQuery.mmenu#390]
The demo site is what I'm trying to achieve where the menu is open on page load on big screen and it will responsively close on medium ones.

I can't seem to find any solutions or questions about this. I even tried putting .mm-opened on my nav but it won't open the menu onLoad.

**Comment by FrDH** [comment]
The demo site uses the `widescreen` extension (with a mediaquery so it only applies on wider screens)
http://mmenu.frebsite.nl/documentation/extensions/widescreen.html
