### ISSUE TITLE
Menu anchors - dont work properly. 

### ISSUE THREAD

**Issue by ashearlam** [BeSite/jQuery.mmenu#392]
Hi,

Apologies in advance, I'm not a massive Javascript programmer, much more css and html however:

It has taken me ages to finally get the menu plugin to work on the site in the way I intended 

It is amazing btw :+1: 

Although, I could not use your clone function? The tutorials miss out the header tags (as I have no idea whether I should be calling functions etc) and I'm not sure if the script should be included with the script already in place calling all functions? Anyway I have using css media queries replaced my normal one for yours when the browser hits 820px so i'm happy although the code is ugly. The reason I had to do it this way was that i want the menu to appear past a certain scroll point and not before. In full screen its just text, but then on smaller screens I want this menu. but still in a scrolled position. Hard to explain. Link below...

My MAJOR problems are two things:

1) Anchor links, do not work? If I use the div name to anchor to, 90% of the time when I click the link in the menu, the menu closes and the page stays at the top? I have also used "a name" and have the same problem occurs?

2) The second is that the position on the webpage does not stay when the menu is activated? Is this intended? For example, if I am half way down my one page site, I open the menu, I do not want to the user to be automatically catapulted to the top? Is there a way to solve this? Is this linked to an underlying issue relating to the errors in point 1 above?

So so sorry I am not up-to-speed on Javascript but would be very appreciated if you could help, and if so could you be as clear as possible!? (Apologies again)

The page in question is (which still needs a lot of work, but once I have a working menu system I can carry on!):

http://www.e-vate.com/ashtest

Ash (rapidly losing hair)

**Comment by ashearlam** [comment]
And now, it doesn't work at all and i haven't changed anything to do with that code.
i have however fleshed out more of the site, do you know of any conflicts with smooth scroll or the like?

http://www.e-vate.com/ashtest2

**Comment by FrDH** [comment]
The plugin bind a click-event to the body. When a user clicks, and the click-event bubbled up the DOM to the body, the plugin tests if it came from an anchor linking to the menu (with `href="#menu"` in your case). Other plugins might (BUT SHOULD NOT) hijack this event.

For the page jumping back to the top, this is probably due to your CSS for the `HTML`
````css
html {
    height: 100%;
}
````
See: http://mmenu.frebsite.nl/support/tips-and-tricks.html#tt-basic-css-tips

**Comment by ashearlam** [comment]
Thanks, i have ripped it all out and now will replace very slowly and hopefully will work :)

Thanks for the advice re "height"

**Comment by ashearlam** [comment]
I have tried again but it doesn't work. I know its something I am doing but I have followed your guide very closely, the bit about cloning doesn't state (for noobs) exactly where that goes so I have created, through CSS queries, to show a normal menu until 820px wide then under that value show the menu icon which when clicked should activate #menu2 which is your menu. But nope.

I can see in the element inspector it is appending the relevant ID's with "mm" but nothing. Nada.

I used your playground to generate the code with the parameters (which is excellent btw, I wish everyone did that!)

I am at a loss, are you able to help?

**Comment by ashearlam** [comment]
Ok, i'm back to the original problem.

Basically I took your demo pages, and coded bit by bit my content into your demo page.

1) Your code does have problems or conflict with smooth scroll. If i have my smooth scroll code open, the menu doesn't work at all. If i comment out my code the menu opens! When I looked at your script for you menu, its huge! Do you incorporate offset and smooth scroll in here?

<script type="text/javascript">
			$(function() {
				var $menu = $('nav#menu'),
					$html = $('html, body');

				$menu.mmenu({
					dragOpen: true
				});

				var $anchor = false;
				$menu.find( 'li > a' ).on(
					'click',
					function( e )
					{
						$anchor = $(this);
					}
				);

				var api = $menu.data( 'mmenu' );
				api.bind( 'closed',
					function()
					{
						if ( $anchor )
						{
							var href = $anchor.attr( 'href' );
							$anchor = false;

//	if the clicked link is linked to an anchor, scroll the page to that anchor 
							if ( href.slice( 0, 1 ) == '#' )
							{
								$html.animate({
									scrollTop: $( href ).offset().top
								});	
							}
						}
					}
				);
			});
		</script>

Here was my script generated from your playgrond area (which suits my needs i think)

"<script type="text/javascript">
         jQuery(document).ready(function( $ ) {
            $("#menu").mmenu({
               "extensions": [
                  "effect-zoom-menu",
                  "effect-zoom-panels",
                  "pageshadow",
                  "theme-white"
               ],
               "offCanvas": {
                  "position": "right"
               },
               "navbars": [
                  {
                     "position": "bottom",
                     "content": [
                        "<a>Some text :)</a>"
                     ]
                  }
               ]
            });
         });
      </script>"

2) Anchors still do not work though? With or without smooth scroll?

I am at a loss now, i thought slowly adding my content to your demo page might get round the issues but sadly not :(

**Comment by ashearlam** [comment]
![image](https://cloud.githubusercontent.com/assets/6670568/8723356/e5829e40-2bc4-11e5-83cb-5de90231f535.png)

Your code for menu

**Comment by ashearlam** [comment]
![image](https://cloud.githubusercontent.com/assets/6670568/8723379/f66a6756-2bc4-11e5-901a-aa846d85939d.png)

My code

**Comment by ashearlam** [comment]
Link to see new revisions:

http://www.e-vate.com/ashtest-jquerymenu/onepage.html

I left in your header so i could check the menu works in the first place... which it does but doesn't want to play ball

**Comment by FrDH** [comment]
There's a JS error on the page:
> SyntaxError: expected expression, got '}'
> });
> onepage.html (regel 53, kol 12)

**Comment by ashearlam** [comment]
What should it be there?

I'm no wiz on this, thats why I have to ask specifically...

**Comment by FrDH** [comment]
Are you looking for someone to debug your script? Try stackoverflow.com orsome similar platform. Id there actually is an issue with the plugin, open up a new issue.
