### ISSUE TITLE
Classname for fixed elements not respected

### ISSUE THREAD

**Issue by abombelli** [BeSite/jQuery.mmenu#393]
Hello,

As of the manual we should be able to define any class name for fixed elements.
```classNames: {
            fixedElements: {
               fixed: "navbar-fixed-top"
            }```

Unfortunately this setting is not respected.
Any idea?

**Comment by FrDH** [comment]
Is there an online demo?
Make sure to put this option in the configuration-object (the second object):
````javascript
$("#menu").mmenu({
   // options
}, {
   // configuration
});
````

**Comment by abombelli** [comment]
The setup seams correct:
http://web12.skouhus.bombelli.ch/

**Comment by abombelli** [comment]
Did you have a chance to look into it?

**Comment by FrDH** [comment]
Sorry, no I hadn't.
Where exactly should I be looking for the JS? I couldn't find it in the source of that page :/

**Comment by abombelli** [comment]
The code is in main.js, but minified. So here it is:
```javascript
 $("#site-nav").mmenu({
            // options
            "offCanvas": {
              "position": "right",
              "zposition": "next"
          }
      },
      {
          // configuration
          clone: true,
          classNames: {
            fixedElements: {
               fixed: "navbar-fixed-top"
            }
         }
    });```

**Comment by FrDH** [comment]
Pretty odd, I ran some tests and all worked as expected.
Could you tell me what is alerted if you add this JS:
````javascript
var api = $("#site-nav").data( "mmenu" );
alert( api.getInstance().conf.classNames.fixedElements );
````

For now, I guess you could do a small workaround by adding the default classname "Fixed" to the fixed elements before firing the plugin:
````js
$('.navbar-fixed-top').addClass( "Fixed" );
$("#site-nav").mmenu();
````

**Comment by abombelli** [comment]
The alert returns: [object Object]

As for the workaround, did not work. Do I still need to add the classNames?
```javascript
classNames: {
            fixedElements: {
               fixed: "Fixed"
            }
         }
```

**Comment by abombelli** [comment]
Could it be related to the z-Index of the mm-menu?

**Comment by FrDH** [comment]
I don't think the `z-index` or any other CSS property will have anything to do with this.
What if you replace the alert with a console.log?

**Comment by abombelli** [comment]
This is the output: `Object {fixed: "navbar-fixed-top"}`

**Comment by FrDH** [comment]
Is that what is logged for fixedElements or for fixedElements.fixed?

**Comment by abombelli** [comment]
For fixedElements:
`console.log(mmAPI.getInstance().conf.classNames.fixedElements);`

**Comment by FrDH** [comment]
Hmm, I think I found the issue. 
The fixedElements add-on searches for ".Fixed" inside the "page".
So you need to wrap your `<header>`, `<div class="wrap">` and `<footer>` in a `<div>`. Otherwise only the `<div class="wrap">` is considered to be the "page".

If that doesn't seem like a good idea, I guess you could also add the class "mm-slideout" manually:
````javascript
$("#site-nav").mmenu();
$('.navbar-fixed-top').addClass( "mm-slideout" );
````

Hope this helps.
