### ISSUE TITLE
iconbar extension and sub menus

### ISSUE THREAD

**Issue by fidoboy** [BeSite/jQuery.mmenu#394]
Hi, I'm trying to use the iconbar extension and it works fine, however when one of the icons open a panel or submenu I want to fully open the mmenu to display the menu items How can I do that? Right now, the submenu opens but you can't read it because it's hidden and the iconbar zone is too small to allow displaying the full text. Any ideas?

**Comment by fidoboy** [comment]
In other words, my question is how can I trigger the full mmenu from the openPanel event? What I want is to force mm-opened to display full menu and not only the small side bar with icons.

**Comment by FrDH** [comment]
Try this:
````javascript
var $menu = $("#menu").mmenu({
   // your options
});

var api = $menu.data( "mmenu" );
api.bind( "openPanel", function() {
   $menu.open();
});
````

**Comment by fidoboy** [comment]
It works fine! Many thanks @FrDH :wink:
