### ISSUE TITLE
"effect-slide-listitems" only works for 1st 9 list items

### ISSUE THREAD

**Issue by zuhloobie** [BeSite/jQuery.mmenu#395]
List items #10 and on do not slide...they just sit there - no animation - while the 1st 9 slide in. Even though they are coded just like the others.

Fix?

Thanks!

**Comment by FrDH** [comment]
The effect is applied to the first 9 list items:
https://github.com/BeSite/jQuery.mmenu/blob/master/src/scss/extensions/jquery.mmenu.effects.scss#L158

Unfortunately, the list can't be infinite, but I'll add more list items in the next version.

**Comment by zuhloobie** [comment]
Thanks for the info. I added more children to

`html.mm-effect-slide-listitems .mm-menu.mm-effect-slide-listitems .mm-listview > li:nth-child(12)`

and adjusted their `...transition-delay`.

Works great! Thanks for pointing me in the right direction.
