### ISSUE TITLE
How to get the 'Drag open' Add-on on working with two menus?

### ISSUE THREAD

**Issue by dotnetsharp** [BeSite/jQuery.mmenu#397]
To open the mmenu on a swipe gesture, you can include hammer.js and configure the add-on in the options when initializing the menu (see http://mmenu.frebsite.nl/documentation/addons/drag-open.html):

    _JQ('#rightMenu').mmenu({        
        dragOpen: true
    }, {
        // configuration
        clone: true
    });

    _JQ('#leftMenu').mmenu({        
        dragOpen: true
    }, {
        // configuration
        clone: true
    });

That works fine for one menu, but as I have two menus on one site (one opening from the left side, one from the right), the add-on does only work on the first (the left) menu, but not on the second (right) menu. 

How to get it work on both menus?

**Comment by FrDH** [comment]
I don't think this is possible at all. It would mean the same HTML node is used twice for creating a `new Hammer()`.
Are you getting any errors on that?
