### ISSUE TITLE
Icon panels non-smooth animation due to unnecessary transition?

### ISSUE THREAD

**Issue by apptaro** [BeSite/jQuery.mmenu#399]
When using icon panels addon with many menu items with submenues, subpanel open/close animation becomes less smooth on iPhone5s(iOS8.4). Here's the test case:
http://codepen.io/apptaro/full/RPJmgp

I found that the source of the issue is this seemingly unnecessary transition of "right" position:
.mm-iconpanel .mm-panel.mm-subopened { right: 40px; }

When "right" position remains "0px", the animation becomes smoother. Try the above test case with "with fix" link.

Why do you bother to change the "right" position of the panel when subpanel is opened?

**Comment by FrDH** [comment]
Thank you for taking the time to find a solution for your issue.

Without the `right` position changing, opening/closing a sub-sub-sub-sub menu looks odd (the text in the navbar isn't centered).
Having written the word "sub-sub-sub-sub menu", I realize this might not be a very valid argument. Althoug, the amount of visible panels is configurable. Consider this setup:
````javascript
$("#menu").mmenu({
   iconPanels: {
      add: true,
      visible: 1
   }
});
````
Now opening/closing a sub-sub menu would  have the same issue.

If the fix works for you, please keep using it, I'll consider removing the `right` position for the next version.

**Comment by apptaro** [comment]
I setup a demo, but didn't understand what you mean.
http://codepen.io/apptaro/full/YXjpaN

With/witout right position changing, sub-sub-sub-sub menu looks just fine to me.

**Comment by FrDH** [comment]
The position of the text in the navbar isn't centered. But like I mentioned, I'll consider removing the `right` position for the next version.
