### ISSUE TITLE
[usage] Do not collapse menu when click outside of it

### ISSUE THREAD

**Issue by george-silva** [BeSite/jQuery.mmenu#402]
Hello!
First of all, congratulations on the amazing, excelent plugin.

I have a mobile app, that render some information on a bottom panel, powered by mmenu. The div below, is a full screen map.

I was wondering if there is way to keep the menu/panel on canvas while the user interacts with the map. That's because a single click, hides the information we rendered there, and it's somewhat annoying that the user needs to ask the panel to pop back up again.

Any tips?

**Comment by FrDH** [comment]
Not by default, the DIV#mm-blocker closes the menu onMousedown / onTouchstart. I guess you could use CSS to hide the blocker alltogether:
````css
#mm-blocker {
   display: none !important;
}
````

If you manually want to open/close the menu, try using the API:
http://mmenu.frebsite.nl/documentation/api.html
````javascript
var $menu = $("#menu").mmenu();
var API = $menu.data( "mmenu" );

API.open();
API.close();
````

**Comment by george-silva** [comment]
Brilliant! Genius!

Works perfect. Just hid the mm-blocker.
