### ISSUE TITLE
Remote DataSource, disable and visible item with angularjs

### ISSUE THREAD

**Issue by checco1983** [BeSite/jQuery.mmenu#404]
I have this datasource and I want to bind to the menu as I do?
          
$scope.menu2 = [
               {
                   title: 'UPF',
                   id: 'menuID',
                   items: [
                     { name: 'RA', id: 'itemRA' ,visible:false},
                     { name: 'RB', id: 'itemRB',disabled:true},
                   ]
               }
            ];

you can disable or visible an item?

**Comment by FrDH** [comment]
To hide a `<li>`, you can add the class "mm-hidden" to it. That'll hide it and ignores it when using the searchfield.
