### ISSUE TITLE
MMenu not work with angular

### ISSUE THREAD

**Issue by checco1983** [BeSite/jQuery.mmenu#405]
$scope.menu2 = [
               {
                   title: 'UPF',
                   items: [
                     { name: 'RA', id: 'itemRA' },
                     { name: 'RB', id: 'itemRB' },
                     {
                         name: 'RS', id: 'itemRS',
                         items: [
                                      {
                                          title: 'RS',
                                          items: [
                                              { name: 'RS1', disabled: true },
                                              { name: 'RS2' }]
                                      }
                         ]
                     },
                   ]
               }
            ];  

    <nav id="menu">
        <ul>
            <li><a href="">My controller says: {{menu2.title}}</a></li>
            <li><a href="">my link 2</a></li>
            <li><a href="">my link 3</a></li>
            <li><a href="">my link 4</a></li>
            <li><a href="">my link 5</a></li>
            <li><a href="">my link 6</a></li>
        </ul>
    </nav>

$('#menu').mmenu({
            });

This error is:
TypeError: Cannot read property 'childNodes' of undefined
    at compositeLinkFn (angular.js:7078)
    at compositeLinkFn (angular.js:7078)
    at nodeLinkFn (angular.js:7721)
    at compositeLinkFn (angular.js:7075)
    at publicLinkFn (angular.js:6954)
    at angular.js:1451
    at Scope.$get.Scope.$eval (angular.js:14388)
    at Scope.$get.Scope.$apply (angular.js:14487)
    at bootstrapApply (angular.js:1449)
    at Object.invoke (angular.js:4182)

how can I do?

**Comment by FrDH** [comment]
The plugin moves the HTML from whereever it is and prepends it to the BODY, could that cause Angular to mess things up?
If so, this is more a question about Angular.
