### ISSUE TITLE
Including hammer.js breaks tap-highlight

### ISSUE THREAD

**Issue by apptaro** [BeSite/jQuery.mmenu#406]
I noticed that when I include hammer.js for use with drag open addon, tapping a menu item no longer highlights it. Together with the setSelected issue for iPhone (see pull request #403,) I can't tell if I tapped on a menu item or not.

The issue is caused because hammer.js adds -webkit-tap-highlight-color: rgba(0, 0, 0, 0); to mmenu. The fix is to re-enable tap-highlight for menu items. For example:

.mm-menu .mm-listview > li a { -webkit-tap-highlight-color: rgba(0, 0, 0, 0.2); }

**Comment by FrDH** [comment]
Thanks, I'll look into adding the CSS
