### ISSUE TITLE
Mmenu SearchField Customizing

### ISSUE THREAD

**Issue by hauareyou** [BeSite/jQuery.mmenu#408]
I am trying to set the search menu to do a custom search through my google search. For example: http://www.askdavetaylor.com/how_can_i_add_a_google_search_box_to_my_web_site/

I want to do this google search rather than searching the menu. I can add the action for the form but not sure where to do so.

**Comment by FrDH** [comment]
You can add any HTML in a navbar:
````javascript
$("#menu").mmenu({
   navbars: {
      content: [ "<form><input /><button>click</button></form>" ]
   }
});
````
