### ISSUE TITLE
Refresh MMenu

### ISSUE THREAD

**Issue by checco1983** [BeSite/jQuery.mmenu#409]
Hi,

there is a way to update the menu? I want that when I click on a button I update the menu with a different datasource

**Comment by FrDH** [comment]
What exactly do you mean with "update"?
Add a new UL?
Add new LI's to an UL?
Remove an old LI?
Remove an old UL?
Completely remove all HTML and insert new HTML?

**Comment by checco1983** [comment]
Completely remove all HTML and insert new html
--
Inviato da Libero Mail per Android Martedì, 04 Agosto 2015, 03:19PM +02:00 da Fred Heusschen < notifications@github.com> :

**Comment by FrDH** [comment]
Try the last comment in topic https://github.com/BeSite/jQuery.mmenu/issues/57
