### ISSUE TITLE
mmenu playing up when turbolinks are enabled

### ISSUE THREAD

**Issue by transat** [BeSite/jQuery.mmenu#41]
Loving the menu but it stops working correctly when turbolinks are enabled in a Rails 4 app.

**Comment by alameenkhader** [comment]
+1. Can not get it to work with turbolinks enabled..

**Comment by LuisCDias** [comment]
+1, menu dies after the first page:change event. Any solution? @transat @karlingen any of you figured it out?

**Comment by karlingen** [comment]
@LuisCDias Unfortunately not. We switched the entire menu to something else.

**Comment by transat** [comment]
@LuisCDias Switched to Foundation after i couldn't get turbo links working

**Comment by LuisCDias** [comment]
Thanks @transat and @karlingen, will probably go with Foundation as well.

**Comment by FrDH** [comment]
I don't know much about turbolinks, but when it replaces the entire contents of the body (including the menu), shouldn't you simply re-create the menu on page:change?
Without an online example, there is not much I can do to debug.

**Comment by LuisCDias** [comment]
Yes, and that's what I am doing along with all the other scripts. But the menu doesn't recreate, although no error is shown. Is there any option to "reset" the menu?

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
My guess is, some of the elements the plugin stores in variables need to be updated.

**Comment by karlingen** [comment]
@FrDH 
I've created a repo for this: https://github.com/karlingen/rails4_mmenu
Online example: http://rails4-mmenu.herokuapp.com/

**Comment by karlingen** [comment]
@FrDH Anything new here?
Do you mind re-opening this issue so that others as well might be interested in helping us out?

**Comment by karlingen** [comment]
Ping...

**Comment by viktorperez** [comment]
Any solution/update about this? Thanks.

**Comment by FrDH** [comment]
I'm currently working on a new (mayor) version that should have no issues with turbolinks. For now, it seems there are two issues you need a workaround for:

The first issue is that the "offCanvas_initBlocker" method is emptied after it is fired once.
You can comment out line 380 of "addons/jquery.mmenu.offcanvas.js" and put all code in that method inside an `if` statement that checks if the blocker does not yet excist:

````javascript
if ( !$("#" + _c.blocker).length ) {
// ...
}
````

The second issue is that the `$page` and some other elements are stored in a variable and the script test for these variables instead of for the elements to excist. You can empty the variables by setting `$.mmenu.glbl` to an empty object before firing the plugin:

````javascript
$.mmenu.glbl = {};
$("#menu").mmenu();
````

I think that should do the trick for now, but again: A new version that has support for turbolinks is coming soon.

**Comment by karlingen** [comment]
Wow, that's amazing news! Looking forward to it.
Thanks for taking the time and sorting this one out. :)

**Comment by LuisCDias** [comment]
Thanks for the help @FrDH. Great to know a new version is almost here :)
However, I couldn't really fix the problems with your suggestions. I'm requiring "jquery.mmenu.min" and "jquery.mmenu.offcanvas", and the last function on this file now looks like this (after your suggestions):
```
$[ _PLUGIN_ ].prototype[ _ADDON_ + '_initBlocker' ] = function()
	{		
		if ( !$("#" + _c.blocker).length ) {
			var that = this;
			var $blck = $( '<div id="' + _c.blocker + '" class="' + _c.slideout + '" />' )
				.appendTo( glbl.$body );
				
			$blck
				.on( _e.touchstart,
					function( e )
					{
						e.preventDefault();
						e.stopPropagation();
						$blck.trigger( _e.mousedown );
					}
				)
				.on( _e.mousedown,
					function( e )
					{
						e.preventDefault();
						if ( !glbl.$html.hasClass( _c.modal ) )
						{
							glbl.$allMenus.trigger( _e.close );
						}
					}
				);

		}		
		//	Once fired, it can be removed
		//$[ _PLUGIN_ ].prototype[ _ADDON_ + '_initBlocker' ] = function() {};
	};
```

Thanks again for your availability.

**Comment by FrDH** [comment]
That seems about right but I can image I'm missing something here. Are you getting any errors?
I'll post an update when I find a solution.

**Comment by LuisCDias** [comment]
No console errors show up. Thank you!

**Comment by FrDH** [comment]
In the next version (should be coming soon), the following works:
````javascript
// Instead of an actuall ajax call, I cloned the <body>, should have the same result.
var $body = $('body').clone();

// Fire the plugin
$('#menu1').mmenu();

// Open the plugin (just for show)
$('#menu1').data( 'mmenu' ).open();

// Instead of clicking on a (turbo)link, I used a timeout, should have the same result
setTimeout(function() {

	// This is kinda what turbolinks does
	$('body').replaceWith( $body );

	// In case the menu was opened, all "mm-" prefixed classnames need to be removed from the <html>
	$('html').removeAttr( 'class' );

	// This makes the plugin re-init the global variables
	$.mmenu.glbl = false;

	// Re-create the menu, this is what you'd normally do in the turbolinks page:load event
	$('#menu1').mmenu({
		header: true,
		searchfield: true
	});

}, 1500);
````

**Comment by nonameolsson** [comment]
@FrDH sounds great! Would you recommend us to use this temporary fix, or wait for the new version?

**Comment by FrDH** [comment]
This temporary fix won't work in the current version. :)

**Comment by FrDH** [comment]
The new version is out (5.0.0).
This is a major release (4 > 5) because it is not backward compatible with previous versions.

For more information, see the changelog:
http://mmenu.frebsite.nl/documentation/changelog.html

**Comment by LuisCDias** [comment]
Thanks and awesome work @FrDH :)
Can you tell me if there's any workaround needed to make version 5 work with turbolinks? I'm still experiencing the same problem as before. I'm including jquery.mmenu.all.

Thanks.

**Comment by FrDH** [comment]
Here's a modification of my earlier comment.
I don't use turbolinks myself so can't test this, let me know if that does it.

````javascript
function ready() {
    // In case the menu was opened, all "mm-" prefixed classnames need to be removed from the <html>
    $('html').removeAttr( 'class' );

    // This makes the plugin re-init the global variables
    $.mmenu.glbl = false;

    // (re)create the menu
    $('#menu1').mmenu({
        header: true,
        searchfield: true
    });
}
$(document).ready(ready);
$(document).on('page:load', ready);
````

**Comment by LuisCDias** [comment]
It still doesn't seem to work.

**Comment by FrDH** [comment]
are you getting any errors or warnings in the console?
Is there an online example?

Like I mentioned, I don't use turbolinks myself so can't do any actuall testing.

**Comment by muhic** [comment]
I can confirm that turbolinks are now working, tested on Android with Chrome & Dolphin. You have to reset the global vars as @FrDH suggested. Here is my current js code:
``` javascript
var ready;
ready = function() {
	// reset global variables
    $('html').removeAttr( 'class' );
    $.mmenu.glbl = false;

   	$("#menu").mmenu({
   		header: true,
   	 	footer: {
   	 	   add: true,
   	 	   content: "&copy; 2015 Ibyiza Ltd. All rights reserved"
   	 	},
   	 	extensions: ["pageshadow"],
        backButton: {
           close: true
        }
   	});
};

$(document).ready(ready);
$(document).on('page:load', ready);
```

**Comment by FrDH** [comment]
I wrote a tutorial for using mmenu with Turbolinks:
http://mmenu.frebsite.nl/tutorials/frameworks/turbolinks.html

Please let me know if anything in this tutorial isn't working.

**Comment by fdwillis** [comment]
how do i get started with this? saying glbl undefined
