### ISSUE TITLE
Refresh mmenu with angular using $watch

### ISSUE THREAD

**Issue by checco1983** [BeSite/jQuery.mmenu#410]
When I click the button my datasource changes , however, when I go to call the below items mmenu work incorrectly           

var menu = (function ($) {
                return {
                    initMenu: function () {
                        $('nav#menu').mmenu({
                            navbar: { title: "Menu UPF" },
                            slidingSubmenus: true,
                            onClick: {
                                blockUI: function () {
                                    if ($("#" + this.text + "").find(".disabled").length > 0)
                                        alert("Quadro Disabilitato")
                                    else
                                        alert(this.text)
                                }
                            }
                        });
                    }
                };
            })(jQuery);

            $scope.$watch('items', function (newValue,oldValue) {
                $(function () {
                        menu.initMenu();
                    });

            });

            $("#btn").click(function () {
                $scope.items = [
                    { name: 'RE', id: 'itemRE' },
                    {
                        name: 'RF', id: 'itemRF',
                        items: [
                            { name: 'RF1' }
                        ]
                    },
                ];
            });

**Comment by FrDH** [comment]
Calling $.mmenu() twice on the same HTML node is not a good idea.
You could try using the `init` method in the API, have a look at the last comment in this issue:
https://github.com/BeSite/jQuery.mmenu/issues/57

**Comment by checco1983** [comment]
Hi,

I tried as you told me it is not properly updated the menu with the angular approach , the error occurs in the subitems , I noticed that when I update the menu under the < li> missing for example

<a class = " mm -next " href = " # mm - 1 " on - target = " # mm - 1 " > </a>

**Comment by checco1983** [comment]
This is my code, When I click on the checkbox changing my datasource
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles
{
    @Styles.Render("~/Content/dx/css")
}

@section scripts
{

    @Scripts.Render("~/bundles/dx")

    <script type="text/javascript">

        var myApp = angular.module('myApp', ['dx']);

        myApp.controller('AnagraficaController', ['$scope', function ($scope) {

            $scope.items = [
                     { name: 'RA', id: 'itemRA', disabled: true },
                     { name: 'RB', id: 'itemRB', visible: false },
                     { name: 'RC-CR', id: 'itemRCCR' },
                     { name: 'RD', id: 'itemRD', disabled: true },
                     { name: 'RE', id: 'itemRE' },
                     {
                         name: 'RF', id: 'itemRF',
                         items: [
                             { name: 'RF1' },
                             {
                                 name: 'RF2', items: [
                                   { name: 'RF2_1' },
                                   { name: 'RF2_2' }
                                 ]
                             }
                         ]
                     },
                     { name: 'RG', id: 'itemRG' },
                     { name: 'RH', id: 'itemRH' },
                     { name: 'RL', id: 'itemRL' },
                     { name: 'AC', id: 'itemAC' },
                     {
                         name: 'FC', id: 'itemFC',
                         items: [
                             { name: 'FC1' },
                             { name: 'FC2' }
                         ]
                     },
                     {
                         name: 'CE', id: 'itemCE',
                         items: [
                             { name: 'CE1' },
                             { name: 'CE2' }
                         ]
                     },
                     {
                         name: 'RM', id: 'itemRM',
                         items: [
                             { name: 'RM1' },
                             { name: 'RM2' }
                         ]
                     },
                     { name: 'LM', id: 'itemLM' },
                     {
                         name: 'RN', id: 'itemRN',
                         items: [
                             { name: 'RN1' },
                             { name: 'RN2' }
                         ]
                     },
                     { name: 'RR', id: 'itemRR' },
                     {
                         name: 'RS', id: 'itemRS',
                         items: [
                             { name: 'RS1' },
                             { name: 'RS2' }
                         ]
                     },
                     { name: 'RT', id: 'itemRT' },
                     { name: 'RQ', id: 'itemRQ' },
                     {
                         name: 'RU', id: 'itemRU',
                         items: [
                             { name: 'RU1' },
                             {
                                 name: 'RU2', items: [
                                 { name: 'RU22' },
                                 { name: 'RU22' }
                                 ]
                             }
                         ]
                     },
                     { name: 'RV', id: 'itemRV' },
                     { name: 'RX', id: 'itemRX' },
                     { name: 'RW', id: 'itemRW' },
                     { name: 'TR', id: 'itemTR' },

            ];


            $scope.isChecked = function () {

                $scope.items = [
                        { name: 'RA', id: 'itemRA', disabled: true },
                        { name: 'RB', id: 'itemRB' },
                        { name: 'RC-CR', id: 'itemRCCR' },
                        { name: 'RD', id: 'itemRD', disabled: true },
                        { name: 'RE', id: 'itemRE' },
                        {
                            name: 'RF', id: 'itemRF',
                            items: [
                                { name: 'RF1' },
                                {
                                    name: 'RF2', items: [
                                        { name: 'RF2_1' },
                                        { name: 'RF2_2' }
                                    ]
                                }
                            ]
                        },
                ];


            };

            var menu = (function ($) {
                return {
                    initMenu: function () {
                        $('nav#menu').mmenu({
                            navbar: { title: "Menu UPF" },
                            slidingSubmenus: true,
                            onClick: {
                                blockUI: function () {
                                    if ($("#" + this.text + "").find(".disabled").length > 0)
                                        alert("Quadro Disabilitato")
                                    else
                                        alert(this.text)
                                }
                            }
                        });
                    }

                };

            })(jQuery);

            $scope.$watch('items', function (newValue, oldValue) {

                angular.element(document).ready(function () {

                    menu.initMenu();


                    //var $menu = $("#menu").mmenu(),
                    //    api = $menu.data("mmenu");

                    //var $ul = $menu.find("#nav");
                    //$menu.find("#nav").remove()
                    ////api.remove($ul);
                    //    api.init($ul);
                });
            });


        }])

        myApp.directive('sidemenu', function () {

            return {
                restrict: "E",
                replace: true,
                scope: {
                    items: '='
                },
                template: "<ul style='margin-right: -37px;overflow-y: scroll;overflow-x: hidden;height: 100%;'><sidemenuitem ng-repeat='item in items' item='item'></sidemenuitem></ul>",
                link: function (scope, element, attrs) {
                    scope.$watch('items', function (newValue, oldValue) {
                    });
                }

            }
        })

        myApp.directive('sidemenuitem', function ($compile) {

            var linker = function (scope, element, attrs) {
                if (angular.isArray(scope.item.items)) {
                    element.append("<sidemenu items='item.items'></sidemenu>");
                    $compile(element.contents())(scope)
                }
                else {
                    element.append("<ul><li style='position: static' class = 'border-sidemenuitem'><listitem ></listitem></li></ul>");
                    $compile(element.contents())(scope)
                }
            }

            return {
                restrict: "E",
                replace: true,
                scope: {
                    item: '='
                },

                template: '<li id="{{item.name}}" ng-class="{hidden : isHidden(item)}">' +
                            ' <a href="#" ng-click="invoke(item)" ng-class="[\'mm-listview border\',{true: \'mm-listview disabled\'}[isDisabled(item)]]">{{item.name}}' +
                            '</a> ' +
                          '</li>',



                controller: function ($scope) {
                    $scope.isDisabled = function (item) {
                        if (angular.isObject(item) && angular.isFunction(item.disabled))
                            return item.isDisabled();
                        if (angular.isObject(item) && (item.disabled == true || item.disabled == false))
                            return item.disabled;
                        else
                            return false;
                    },
                $scope.isHidden = function (item) {
                    if (angular.isObject(item) && angular.isFunction(item.visible))
                        return item.isHidden();
                    if (angular.isObject(item) && (item.visible == true || item.visible == false))
                        return !item.visible;
                    else
                        return false;
                },

                $scope.invoke = function (item) {
                    if (angular.isObject(item) && angular.isFunction(item.action)
                        && !$scope.isHidden(item) && !$scope.isDisabled(item))
                        item.action();
                }

                },

                link: linker

            }
        })

        myApp.directive('listitem', function () {
            return {

                controller: function ($scope, $element, $attrs, $location) {
                    $scope.itemsNum = [];
                    $scope.lastItems = [];
                    $scope.name = $scope.item.name
                    var length = 50

                    if ($scope.name == "RA")
                        length = 200
                    if ($scope.name == "RC-CR")
                        length = 3

                    var counter = 1;
                    $scope.loadMore = function () {
                        for (var i = 1; i <= length; i++) {
                            if (counter > length)
                                break;

                            $scope.itemsNum.push({ Num: "# " + counter, Action: 'delete', ImgAction: '/TAB/Images/DELETE.jpg', operator: "-" });

                            if (i == length)
                                $scope.itemsNum.push({ Num: "# " + (length + 1), Action: 'new', ImgAction: '/TAB/Images/NEW.png', operator: "*" });

                            counter += 1;
                        }
                    };

                    $scope.loadMore();

                    $scope.modello = function (item, name) {

                        $('#' + name + ' div').each(function () {
                            if ($(this).text() == item.Num)
                                $(this).addClass('on');
                            else
                                $(this).removeClass('on');
                        });

                        console.log(item.Num);
                    };

                    $scope.operazione = function (item, name) {
                        if (item.operator == "-") {
                            console.log(item.Num + ' Delete');
                        }

                        if (item.operator == "*") {
                            console.log(item.Num + ' Add');
                        }

                    };

                    $scope.Scroll = function (item, items, name) {

                        $quadro = $('#' + name)
                        $panel = $quadro.find('.scroll');
                        var pos = items.map(function (e) { return e.Num; }).indexOf(item.Num);

                        if (pos > 19) {
                            $panel.css("height", "680px")

                            if (item.operator == "-")
                                return "item"
                            else
                                return "lastitem";
                        }
                        else {
                            $panel.css("height", "730px")
                            return "item"
                        }
                    }
                },

                template: '<div id="{{name}}" class="scroll" when-scrolled="loadMore()">' +
                            '<li ng-repeat=\'item in itemsNum\' ' +
                            '<div ng-class="Scroll(item,itemsNum,name)">' +
                                '<div class="numModello dx-item-content dx-list-item-content">' +
                                    '<span style="color:white" class="template-number" ng-click="$parent.modello(item,name)">{{item.Num}}</span>' +
                                '</div>' +
                                '<div class="operator dx-list-item-after-bag dx-list-static-delete-button-container">' +
                                    '<span class="template-button" ng-click="$parent.operazione(item,name)">{{item.operator}}</span>' +
                                '</div>' +
                              '</div>' +
                            '</li>' +
                         '</div> '
            };
        })

        myApp.directive('whenScrolled', function () {
            return function (scope, elm, attr) {
                var raw = elm[0];

                elm.bind('scroll', function () {
                    if (raw.scrollTop + raw.offsetHeight >= raw.scrollHeight) {
                        scope.$apply(attr.whenScrolled);
                    }
                });
            };
        })


        angular.bootstrap($("#main"), ["myApp"]);

    </script>
}

<div id="main" ng-controller="AnagraficaController">

    <div class="anagrafica-panel">

        <div class="anagrafica-dati">
            <div class="dato">00001</div>
            <div class="dato">PAGANO FRANCESCO</div>

            <input id="btn" type="checkbox" ng-click='isChecked()' />
        </div>

    </div>


    <nav id="menu">
        <sidemenu id="nav" items='items'></sidemenu>
    </nav>

</div>

**Comment by checco1983** [comment]
Yhis is code HTML

<div id="main" ng-controller="AnagraficaController">

    <div class="anagrafica-panel">

        <div class="anagrafica-dati">
            <div class="dato">00001</div>
            <div class="dato">PAGANO FRANCESCO</div>

            <input id="btn" type="checkbox" ng-click='isChecked()' />
        </div>

    </div>


    <nav id="menu">
        <sidemenu id="nav" items='items'></sidemenu>
    </nav>

</div>

**Comment by FrDH** [comment]
I'm not familliar with angualar so I don't think I can help. For the record; I don't think it matters what framework you use to change the HTML inside the menu. The solution to the "changing the content" issue should be the same for Angular as for changing it manually.

**Comment by checco1983** [comment]
Ciao amico!

Volevo solo condividere con te alcune foto del mio posto preferito, è così bello! Ecco il link per  le foto <http://fulvia.prageeta.com/vyc>

In fretta, francesco pagano

**Comment by checco1983** [comment]
Saluti,

Volevo  ringraziarvi per il vostro sostegno e  condividere con voi alcune informazioni interessanti, si possono  trovare qui <http://one.jfinkphoto.com/bp/97>

Cari saluti, francesco pagano

**Comment by checco1983** [comment]
Salve,

Siamo stati davvero in  un  bel posto  di recente, potrebbe piacerti, ti prego  di dare  un'occhiata <http://thus.bulldogclubmexico.com/jng/464>

Più tardi, francesco pagano
