### ISSUE TITLE
Broken Navbar Example

### ISSUE THREAD

**Issue by DavidGagne** [BeSite/jQuery.mmenu#411]
The text says to look at the differences between the two different implementations, but the two examples are exactly the same:
http://mmenu.frebsite.nl/documentation/addons/navbars.html

**Comment by FrDH** [comment]
The first example (using the navbars add-on) has a fixed header, the second (not using the navbars add-on) has a header per panel. Both have the same content and look the same, but there is a difference. Also, click the "more examples" button to see what more the navbars add-on can do.
