### ISSUE TITLE
Menu doesn't work with UBlock

### ISSUE THREAD

**Issue by markorapaic** [BeSite/jQuery.mmenu#417]
The menu seems to get blocked by UBlock - any fixes for this?

**Comment by FrDH** [comment]
What is UBlock?

**Comment by markorapaic** [comment]
UBlock is an ad blocker - https://www.ublock.org/

**Comment by FrDH** [comment]
If UBlock blocks content it shouldn't block, I'd contact UBlock.

**Comment by sogen** [comment]
Works for me, are you using this one?
https://github.com/chrisaljoudi/uBlock
