### ISSUE TITLE
Chrome/desktop: links are frozen the first few seconds

### ISSUE THREAD

**Issue by InsoftDigital** [BeSite/jQuery.mmenu#419]
In Chrome desktop (Windows >= 7): the first few seconds after opening the sidebar, the links are frozen/not active. A click on them will just close the menu. In some cases, the delay can be as long as 20 seconds. It varies. But it is annoying as hell.
The issue can be easly reproduced on the default mmenu demo: http://mmenu.frebsite.nl/demo/index.html?demo=menu-behavior-1
Running Chrome in safe mode won't change anything.

**Comment by FrDH** [comment]
I haven't noticed any add behavior on the latest Chrome for Mac. Please let me know if you find what might cause this behavior

**Comment by InsoftDigital** [comment]
OMG

**Comment by FrDH** [comment]
?

**Comment by FrDH** [comment]
if OMG is the only further explanation, I'm going to close this issue.

**Comment by kingbiscit** [comment]
I can also see this issue in latest Chrome on my project and the demo project.

If you decrease the transition time it isn't as bad.
