### ISSUE TITLE
Ads is not displayed

### ISSUE THREAD

**Issue by afurtll** [BeSite/jQuery.mmenu#420]
On my page, located – 3 Adsense ads, when you first load the page one of the ads, which is located in the footer of the page is not displayed. After refreshing the page, this as starts to show up, but also sometimes after refreshing the page – the upper ad does not appear. I know that the problem appeared after connecting mmenu, because if mmenu turn off no such problem occurs. This problem occurs only in Chrome (desktop) and Safari (mobile). Other browsers do not have this problem.

 I also discovered that if you open the page in a new tab, then all ads are displayed normally, but open another page of the site in this new tab by clicking on the link, one of the ads is no longer displayed. I also see that this is problem with adsense, because I try to use a different code of advertising and ads is displayed normally. 

I am not a programmer, so difficult for me to understand what has been done wrong, the programmer who has connected the mmenu can not understand what is the error. I copied the files that are involved in the connection mmenu - https://dl.dropboxusercontent.com/u/4993586/mmenu.rar

**Comment by FrDH** [comment]
The issue probably is, that the plugin needs to wrap all HTML that appears to be "the page" into one DIV. That rearranging of the HTML can cause an error in the JS of the ad.
So basically all you'd need to do, is wrap all your HTML into one DIV:

````html
<div>
   <div id="header"></div>
   <div id="content"></div>
   <div id="footer"></div>
</div>
````

**Comment by afurtll** [comment]
I did it, but it does not solve the problem :(

**Comment by FrDH** [comment]
Could you try to set the `offCanvas.wrapPageIfNeeded` configuration option to false.
It is not recommended to do so, but if that solves the issue, at least we know what's causing it:
````javascript
$("#my-menu").mmenu({
    // options
}, {
    // config options
    offCanvas: {
        wrapPageIfNeeded: false
    }
});
````

**Comment by FrDH** [comment]
Has this issue been fixed and can I close this issue?

**Comment by afurtll** [comment]
Sorry for my late answer. Where I need to use this code:

$("#my-menu").mmenu({
    // options
}, {
    // config options
    offCanvas: {
        wrapPageIfNeeded: false
    }
});

Please explain. Thank you.
