### ISSUE TITLE
Can not prevent menu from staying open when body is clicked

### ISSUE THREAD

**Issue by VeeK727** [BeSite/jQuery.mmenu#421]
Hi, I noticed there's no option to keep the menu open when you click outside it. Considering the level of customizations this plug in provides,I think it must be included, is it a bug?

The file removes a few classes from the HTML element but I can't pin point to the code that does that, if someone could point me to that piece of code, I may be able to create a work around for it.

Thanks

**Comment by FrDH** [comment]
For now, clicking outside the menu will close the menu. This is due to the `DIV#mm-blocker` that blocks interaction with the page while the menu is open.
I guess you could hide this blocker with css:
````css
#mm-blocker {
   display: none !important;
}
````

**Comment by VeeK727** [comment]
@FrDH Thanks a lot man. I managed to create a workaround for now.
