### ISSUE TITLE
dragOpen, Hammer and horizontal scroll

### ISSUE THREAD

**Issue by fidoboy** [BeSite/jQuery.mmenu#423]
Hi, I'm trying to find a solution for the following issue: when I use the dragOpen addon it also prevents all items in my page to scroll horizontally (child items). How can I exclude them from being passed to hammer? I'm using horizontal scrollable DIVs that are childs of pageNode item being passed to dragOpen. Any ideas?

**Comment by FrDH** [comment]
I'm not all that familiar with Hammer and how it stops the propagation of events.
My guess is, Hammer needs to prevent the default behavior when a horizontal dragging gesture is detected. Maybe you can stop the `touchstart`, `touchend` and `touchmove` events from bubbling up to the page when touching one of the horizontally scrollable DIVs?

````javascript
$(".scrollable-div").on( "touchstart touchmove touchend", function( event ) {
    event.stopPropagation();
});
````

**Comment by fidoboy** [comment]
Hi @FrDH thanks for the tip. I've already tried that but it doesn't worked. Drawer drag is being stopped but the scrollable div still doesn't work. If I remove the dragOpen addon then it works again

**Comment by FrDH** [comment]
If that doesn't do it, I'm out of ideas. Personally I'd drop the dragOpen add-on. How many apps (and mobile websites) besides Facebook actaully have that feature?

**Comment by fidoboy** [comment]
May be you are right. I'm just trying to fix that before surrender. If I can't find any alternative I'll remove the addon :(

**Comment by SKYDA** [comment]
cool

**Comment by fidoboy** [comment]
I've solved it! You should add this code in your mmenu creation:

```dragOpen: {
	open: true,
	vendors: {hammer: {touchAction:'manipulation'}}
},```

This way also horizontal scrollable areas works fine on iOS :wink:
