### ISSUE TITLE
Chome - interactivity delay

### ISSUE THREAD

**Issue by fishwack** [BeSite/jQuery.mmenu#425]
In Chrome - When opening a menu there is an issue with trying to immediately click on links. If you attempt to click on an item too quickly the menu will just close and not register the clicked item. You can easily reproduce this on the following demo page: http://mmenu.frebsite.nl/demo/index.html?demo=menu-behavior-1 Simply click the hamburger and then quickly try to click a menu item. It doesn't repro 100% of the time, but about %75 of the time it will happen. This issue does not happen in IE or other browsers that I've noticed.  Interestingly it doesn't appear to be reproducible with this demo example: http://mmenu.frebsite.nl/demo/index.html?demo=menu-style-2

**Comment by fishwack** [comment]
One note: I've narrowed down the difference between working / not working correctly is the due to the presence of "effect-slide-listitems" in the extensions. If "effect-slide-listitems" is being used the menu reacts to clicks properly.  I'm not sure why this is yet but at least I know whats causing one to work and not the other.

**Comment by Kashkin** [comment]
I've also experienced this issue.

Thanks for the quickfix, @fishwack.

**Comment by abusquets** [comment]
I have this issue too. Anybody has solved this without "effect-slide-listitems" in the extensions?

**Comment by kingbiscit** [comment]
I also have this issue, only way to solve it was edit
jquery.mmenu.css

And comment the transitions

.mm-slideout {
  // -webkit-transition: -webkit-transform 0.4s ease;
  // -ms-transition: -ms-transform 0.4s ease;
  // transition: transform 0.4s ease; 
}

.mm-panel {
  // -webkit-transition: -webkit-transform 0.4s ease;
  // -moz-transition: -moz-transform 0.4s ease;
  // -ms-transition: -ms-transform 0.4s ease;
  // -o-transition: -o-transform 0.4s ease;
  // transition: transform 0.4s ease;

**Comment by Maxime-J** [comment]
I also have this issue in Chrome.
effect-slide-menu also corrects the problem, thanks for the tip.

Interesting to note that this bug happens only with pixels in css translate.
(cf end of jquery.mmenu.css)
Indeed
It's not ok with `transform: translate(440px, 0);`
whereas there's no problem with `transform: translate(80%, 0);`

It's seems to be a chrome bug with some position refresh/focus issues.

**Comment by FrDH** [comment]
I (again) tested all examples on the website in Chrome (on OSX) but could not find any inactivity delay or what so ever. Is this issue still relevant?

**Comment by Maxime-J** [comment]
I no longer have this problem in Chrome last version (on Windows).
I think it's ok to close this issue.

**Comment by fishwack** [comment]
I've also re-tested this in the current version of Chrome on windows and it seems to be working fine. Yay!
