### ISSUE TITLE
Prepending offcanvas menu to a different element than body

### ISSUE THREAD

**Issue by tobyh77** [BeSite/jQuery.mmenu#426]
Hi, I am using this menu on a site that uses .NET Webforms.  One of the menu panels has a search bar in it, but the search won't work because mmenu attaches to the body and I need it to attach inside the form.  I unfortunately don't have an example to show, but hopefully this is clear enough one won't be needed.  The HTML is set up similar to this:
```
<html>
  <body>
    <form id="aspnetForm" class="" action="/" method="post">
    </form>
  </body>
</html>
```

I was hoping the config options you had in the documentation would solve this issue, but it doesn't seem to, so I may be misunderstanding what the use of those configs are for (or just setting it up wrong).  But I tried this:
```
    $("#search-nav-copy").mmenu({
        offCanvas: {
            menuWrapperSelector: "#aspnetForm",
            pageNodetype: "form",
            pageSelector: "body > form",
        }
    });
```
The menu still attaches inside the body when I need it inside that form.  Is there any way to achieve this?  Thanks for the help and for the plugin!

**Comment by FrDH** [comment]
The configuration options go in athe second object:
````javascript
$('#search-copy').mmenu({
  // options
}, {
  offCanvas: {
      menuWrapperSelector: "#aspnetForm",
      pageNodetype: "form",
      pageSelector: "body > form"
  }
});
````

**Comment by tobyh77** [comment]
Thanks for the response!  That was a silly oversight on my part, that did what it should.  However, now I'm having a new issue.

The divs the script generates:
```
<div id="mm-0" class="mm-page mm-slideout">
```
and
```
<div id="mm-blocker" class="mm-slideout">
```
are wrapped around the form, so when it opens the panel opens inside the form like I needed, but if you click to start typing in the field, the panel closes because "mm-blocker" overlays everything.  Is there a way I can prepend these divs inside the form as well?

Thanks again!

**Comment by FrDH** [comment]
The div `.mm-page` is created when the config option `offCanvas.pageSelector` targets more than one node.
The div `#mm-blocker` is prepended to the config option `offCanvas.menuWrapperSelector`.

I'm not sure what you're trying to accomplish, but have you considered not using the default offCanvas behavior?
http://mmenu.frebsite.nl/on-and-off-canvas.html
