### ISSUE TITLE
Object doesn't support property or method 'mmenu' 

### ISSUE THREAD

**Issue by arunsasi** [BeSite/jQuery.mmenu#427]
Hi,

In chrome Jquery Mmenu working perfectly. But in IE and Mozilla Menu not working

Showing

Object doesn't support property or method 'mmenu' 

below is the code

jQuery(document).ready(function( $ ){
            $("#offcanmenu").mmenu({
               "extensions": [
                  "border-full",
                  "pageshadow"
               ],
               "offCanvas": {
                  "position": "top"
               },
               "navbar": {
                  "title": "Navigation"
               },
               "navbars": [
                  {
                     "position": "top",
                     "content": [
                        "prev",
                        "title",
                        "close"
                     ]
                  }
               ],
               "sectionIndexer": true
            }, {
				   clone: true
				});
         });

**Comment by FrDH** [comment]
Seems to be working OK on FireFix over here. Can't test IE right now, but my guess is you're doing something wrong somewhere...

**Comment by FrDH** [comment]
Any update on this? I haven't had any other complaints so I'm going to assume this issue is due to something on your end.
