### ISSUE TITLE
Sliding submenus won't slide after first click/slide

### ISSUE THREAD

**Issue by onetrev** [BeSite/jQuery.mmenu#428]
I've got a weird issue, my sliding submenus won't slide after first click. This applies to the main menu / back link at the top of mmenu. 

*To explain:*  I load a page on the site I'm building. Click on menu button. Menu opens. I click to go to a submenu, the sub-menu slides in. But now I can only click to go to the menu items on this sub-menu page or close the menu. The back button / header of the menu does nothing. If I close the menu and reopen it I still cannot click the go back to home or view another submenu. The only way to get the sliding submenus to work again is to refresh the page or navigate to a new page.

Definitely no console / js errors are reported though during this entire process, so it's very strange.

I can provide a private link to demo this, but unfortunately can't post publicly. Thanks!!

**Comment by JoshuaRogan** [comment]
I was having the same issue with 5.4.*. Reverted back to 5.3 and the issue was resolved.

**Comment by onetrev** [comment]
Thanks! Just reverted to latest version of 5.3, and it works now for me too. This is a bad bug then in 5.4 it seems. Yikes!

**Comment by JoshuaRogan** [comment]
Yeah it is. I spent a little some time trying to figure out what it was. One thing I did notice was the classes were not being updated between each of the panels. They were all in the open state.

**Comment by FrDH** [comment]
Hmm that's odd, The unminified files (with which I do most of my testing) work OK, the minified files don't. I'll update the minified files and upload a bugfix version asap.

**Comment by FrDH** [comment]
Should be fixed in 5.4.2
