### ISSUE TITLE
HTML 5 Video stops playing when jquery MMenu is active

### ISSUE THREAD

**Issue by arunsasi** [BeSite/jQuery.mmenu#429]
HTML 5 Video stops playing when jquery MMenu is active

**Comment by FrDH** [comment]
This could be due to the plugin wrapping all HTML in one DIV, try having all HTML in one DIV to begin with so the plugin doesn't need to.

**Comment by arunsasi** [comment]
i didn't understand what you have said. 
This issue is occuring only in chrome. Please check the url
http://goo.gl/tT70Bj. Check the main banner area.

**Comment by FrDH** [comment]
If there are multiple `div` nodes directly inside the body, the plugin wraps these `div`s into one `div`. That "re-inserting HTML into the DOM" could cause a video to stop playing.

**Comment by arunsasi** [comment]
Thanks.
