### ISSUE TITLE
Synchronous XMLHttpRequest - warning

### ISSUE THREAD

**Issue by razz3251** [BeSite/jQuery.mmenu#430]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

warning in chrome - OK, it's only a warning but what is causing this?

**Comment by FrDH** [comment]
Are you sure you posted this in the right repo? I don't see any relevance with the mmenu plugin.

**Comment by razz3251** [comment]
Thanks for the reply - I'll dig a bit deeper and try and find out what is going on.
