### ISSUE TITLE
The header does not shift to the right when you click on the Menu button

### ISSUE THREAD

**Issue by mkb-buerokonzepte** [BeSite/jQuery.mmenu#432]
Good day,

the following problem I have:

The header does not shift to the right when you click on the Menu button.

Just like on this demo page here: http://mmenu.frebsite.nl/demo/index.html?demo=menu-style-4

Only the content within the Main Divs shifts to the right.

What could be wrong? Are there any positions of #menu I have to comply with?

My website address: www.mkb-buerokonzepte.de

Many thanks.

**Comment by hxu-aa** [comment]
I have the same question.

**Comment by FrDH** [comment]
What exactly do you mean with "header"? The example seems to be working fine by me (on an iPhone and FireFox)

**Comment by mkb-buerokonzepte** [comment]
Hello,

With 'header' I mean the upper part of my website. Where my logo, Top Menu, login menu etc. are placed.

The plugin detects on my side only the lower part. So everything is placed under the header. Accordingly, the MM menu puts over my 'header' and the rest pushes to side.

This the the MM-menu sets over the head area, this area is not visible.

I have it retested for my Iphone, Tablet and Firefox browser. Everywhere the same result.

Where is the problem? In the Tutorials and Tips I can not find any solution to my problem.

Incidentally, this issue came to the latest version after the update.

Thank you

**Comment by mkb-buerokonzepte** [comment]
Could it be because I use HTML 5 tags?

So <header> blblblbbla </ header> and not <div id = 'header'> blabalabla </ div> and so on?

Thank you

**Comment by FrDH** [comment]
If the header is fixed, you should use the FixedElements add-on:
http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html

If it is a direct childnode of the `body`, you should wrap all HTML in only one `div`, as suggested in the tutorial:
http://mmenu.frebsite.nl/tutorials/basic/setting-up-the-html.html

**Comment by mkb-buerokonzepte** [comment]
Good Day,
Yes that has solved the problem. ;)

I had to pack all HTML in a wrap and that was it.

Thank you very much.
