### ISSUE TITLE
mmenu scrolling not work (iPhone6 Plus iOS8)

### ISSUE THREAD

**Issue by xpur** [BeSite/jQuery.mmenu#433]
Hi. 

i used mmenu v5.4.2

i tested safari and chrome, i trying (vertical) scroll to menu but not scrolling. (only content scrolling)

how can fix this issue.

sorry for my english.

**Comment by FrDH** [comment]
I've heard about this issue before, but never could reproduce it on my iPhone (not in iOS7, 8 or 9).
My guess is, there's a compatibility issue with your sites CSS.

**Comment by xpur** [comment]
@FrDH i too like this think! but how can i find this conflicts?

**Comment by FrDH** [comment]
good question :/
try removing parts of the css and see if the issue persists.

**Comment by Marschl** [comment]
Hi, 
the css attributes `transform` in Safari iOS 8.1 - 8.4 and Chrome have to be prefixed `-webkit-`. Otherwise it will not work. Maybe this will help you.
