### ISSUE TITLE
Open first panel after menu closeed it from nested panel

### ISSUE THREAD

**Issue by atna** [BeSite/jQuery.mmenu#434]
Is there a way (option or method) to open menu with start panel, when you close it by clicking on mm-blocker or button? Now it's opening the last panel where you were.

**Comment by FrDH** [comment]
Not by default, but I guess you could use the API to bind a function that opens the first panel when closing the menu.
````javascript
var menu = $("#my-menu").mmenu();
var api = menu.data( "mmenu" );

api.bind( "closed", function() {
    api.closeAllPanels();
});
````

Hope this helps.

**Comment by atna** [comment]
Just what I wanted. Thanks a lot.
