### ISSUE TITLE
Not working well when using the <footer> as the tag

### ISSUE THREAD

**Issue by liujohnliu** [BeSite/jQuery.mmenu#435]
I set up the top menu position:fixed, when I scroll down to the footer section, then click to open menu, the opened menu cannot on the top of footer section. In the HTML code, I used `<footer>` as the tag, after I changed "footer" tag to "div", everything works fine.

**Comment by FrDH** [comment]
Yes that would be correct. The offCanvas addon has a configuration option called `pageNodetype` to specify what type of node it should consider to be the page. It defaults to `div`.
As mentioned in the tutorial, you're best off wrapping all HTML in one `div`.

**Comment by liujohnliu** [comment]
After i try to put everything in one div, it works. I do not often put all HTML in one `div`.  for there already has `body` tag to wrap everything.
