### ISSUE TITLE
Menu wont close on new page 

### ISSUE THREAD

**Issue by edgin** [BeSite/jQuery.mmenu#436]
Hello 
when go to new page 
get url of new page but the page is blank 
with this div covering whole page:

<div class="mm-page mm-slideout" style="/* min-height: 798px; */"><div id="iron-router-progress" class="loading spinner done" style="width:100%"></div></div>

sometimes menu even dont get closed but stayes fixed above blank page
And after that menu button dont work .

**Comment by FrDH** [comment]
That sounds odd, are there any other scripts or frameworks you're using that might cause issues?
Are there any JS errors in the console?

**Comment by edgin** [comment]
Yes , its a web aplication, has few Js scripts,
container fluid is where the page content ,
but its not targeted with mmenu classes ( mm-slideout ), there are two js
scipts instead in it
here is screenshoot :
screencast.com/t/ucB2gy4Ko

**Comment by FrDH** [comment]
Having `<script>` nodes inside the page is not recommended. To prevent the plugin from wrapping all content in a new `<div>` (and so possibly breaking scripts inside), wrap all HTML in one `<div>`, as suggested in the tutorial:
http://mmenu.frebsite.nl/tutorials/basic/setting-up-the-html.html

**Comment by edgin** [comment]
Thank you for your reply.
Yes im using <div id="wraper">
to wrap all the devis beatween the body tags
It seems that for me is router.js that is creatig the problem ,
he gets encpsulated inside mmenu divs.

**Comment by FrDH** [comment]
OK, that also would re-insert the script tag in the DOM after documentReady. There's no way around that. Can you move the script tag outside of the menu?
