### ISSUE TITLE
Modernizr 3 breaks mmenu sliding Animation

### ISSUE THREAD

**Issue by magic-77** [BeSite/jQuery.mmenu#437]
Hey,
the Menu sliding Animation get´s broken when using with Modernizr 3 together.
I´m injecting Modernizr before the closing  `</head>`-Tag,
and jQuery + mmenu before the closing `</body>`-Tag.

**Comment by FrDH** [comment]
I don't really know a lot about modernizr but can't think of a reason why it would mess up CSS transitions and animations.
Is there an online example I could have a look at?

**Comment by magic-77** [comment]
Hey,
i´ve prepared two Demos:
With Modernizr 3:
http://20thcenturyinterior.com/mmenu/demo/default-test.html

Without Modernizr 3
http://20thcenturyinterior.com/mmenu/demo/default.html

Tested on Windows 7 / Chrome 45.
For me, the Demo with Modernizr has a corrupted Sliding Menu Animation

**Comment by FrDH** [comment]
well, the plugin tries to detect whether css-transitions are supported by the browser wit the following test:
````javascript
if ( typeof Modernizr !== 'undefined' ) {
   return Modernizr.csstransitions;
}
````
Logging `Modernizer` to the console shows an object with some properties, but not `csstransitions`. Therefor `Modernizer.csstransitions` evaluates `undefined`, which equals `false`.


In short, I'll fix this issue in the next update :)
Thanks for reporting it.
