### ISSUE TITLE
Menu gets closed without animation on Chrome

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#438]
The menu gets closed suddenly when clicking outside it without any animation at all (or a very fast one) when using Chrome.

This happens from time to time and not every time the menu gets closed. Please use the following link to reproduce the issue.

- Open the menu by clicking the text
- Close it by clicking outside the menu
- Do this multiple times

[Reproduction online](http://jsfiddle.net/g0nqcsq1/)

**Comment by FrDH** [comment]
I clicked the link about a hundred times but could not reproduce the issue (using the latest Chrome on a mac)

**Comment by alvarotrigo** [comment]
I'll record a video for you tomorrow. 
I believe it is related with [this chrome bug](https://code.google.com/p/chromium/issues/detail?id=501297)

**Comment by abusquets** [comment]
I have the same problem.
With windows 7 google chrome 45 and with ubuntu and google chrome 44
