### ISSUE TITLE
searchfield: menu items empty after failed search

### ISSUE THREAD

**Issue by abusquets** [BeSite/jQuery.mmenu#439]
In a failed search the items of menu are not restored if you remove last inserted letters and neither if you delete all text from the input.

I solved the first fail search removing this css code

    /*
  .mm-panel.mm-subopened {
    -webkit-transform: translate3d(-30%, 0, 0);
    -moz-transform: translate3d(-30%, 0, 0);
    -ms-transform: translate3d(-30%, 0, 0);
    -o-transform: translate3d(-30%, 0, 0);
    transform: translate3d(-30%, 0, 0); }*/

But if you make a failed search again, the result is always empty.

**Comment by FrDH** [comment]
That cant be good, i'll investigate later on.

**Comment by FrDH** [comment]
Should be fixed in version 5.5.2
