### ISSUE TITLE
Programatically close mmenu

### ISSUE THREAD

**Issue by danbramall** [BeSite/jQuery.mmenu#441]
Hi,

Great plug-in, thanks to the author and contributors! :)

I need a way to close mmenu when the browser window is resized.  I don't see an event that will do this ('closeAllPanels' doesn't seem to close all panels, it keeps the first panel open).  I implemented a custom jQuery function to remove various CSS classes which are added when mmenu is opened:

```
	$(window).smartresize(function () {
		cleanUpMMenu();
	});

	function cleanUpMMenu() {
		$('html').removeClass('mm-opened mm-blocking mm-background mm-opening');
		$('#menu').removeClass('mm-current mm-opened');
	}
```

This looks like it works visually, but once called it renders the menu toggle button inactive, so the menu can't be opened again.

Am I missing something obvious, or could anyone suggest a way to get mmenu to close neatly via a JavaScript event?

Thanks!

**Comment by FrDH** [comment]
The `closeAllPanels` method closes all panels, except for the main panel :)
You're looking for the `close` method:
http://mmenu.frebsite.nl/documentation/addons/off-canvas.html

**Comment by danbramall** [comment]
Perfect, thanks.  I didn't realise there were 'extra' methods available in that default plug-in.  Works nicely.
