### ISSUE TITLE
First menu won't close when 2 menus are used

### ISSUE THREAD

**Issue by clarosa-garlock** [BeSite/jQuery.mmenu#442]
My website has 2 menus which open with jQuery.mmenu.  Both menus works fine with jQuery.mmenu-4.7.5.  However, when I upgrade to jQuery.mmenu-5.5.2, the first menu (the one that calls mmenu() first in the ready function) no-longer closes when I click on the page overlay.  Here is my ready function:

	jQuery(document).ready(function($) {

		$("#main-mmenu").mmenu({
			// options
			extensions: [ "theme-dark" ],
			offCanvas: { position: "left" },
		}, {
			// configuration
			clone: true
		});

		$("#language-mmenu").mmenu({
			// options
			extensions: [ "theme-dark" ],
			offCanvas: { position: "right" }
		}, {
			// configuration
			clone: true
		});
	});

I have included all the appropriate CSS and JS files.  This appears to be a regression.

**Comment by FrDH** [comment]
That's odd, I'll see if I can reproduce this issue and let you know.

**Comment by clarosa-garlock** [comment]
I don't have an online example, unfortunately, because it's currently an internal site until it goes live.  But I have narrowed the version down to version 5.0 of jQuery.mmenu.  In version 5.0.0, neither the right nor the left menu will close when I click on the page overlay.  In version 5.0.4, the the first (left) menu (the one that calls mmenu() first in the ready function) doesn't close when I click on the page overlay, but the second (right) menu does close when I click the page overlay.  So it's something that apparently changed between versions 4.7.5 and 5.0.0.

**Comment by clarosa-garlock** [comment]
I have attached an HTML file that reproduces the problem quite easily.  Just add "jquery-1.7.js" to the same directory and the "jQuery.mmenu-5.5.2" package as a sub-directory.  Then click "index.html" to view in your browser, and try the left and the right menu.  The left one won't close.
[index.html.txt](https://github.com/BeSite/jQuery.mmenu/files/35825/index.html.txt)

**Comment by clarosa-garlock** [comment]
I have created a file to reproduce this problem easily.  Just save the attached file to a directory on your hard disk and rename it to "index.html".  Then download a copy of "jquery-1.7.js" to the same directory, and extract a copy of jQuery.mmenu 5.5.2 to the subdirectory "jQuery.mmenu-5.5.2".  Now open "index.html" in a browser and click the link to open the left menu.  If you try to close it by clicking the overlay, it won't close.  You'll have to reload the page.  However, if you open the right menu, you can close it by clicking the overlay.
[index.html.txt](https://github.com/BeSite/jQuery.mmenu/files/35835/index.html.txt)
Note:  I have a full ZIP package for this, but GitHub won't let me attach a ZIP file.

**Comment by FrDH** [comment]
Thank you for the demo file.
I found It has something to do with the `clone` config option set to `true` on the first menu, setting it to `true` in the second menu makes no difference.
I'll investigate why and see if I can fix this in the next version.

**Comment by FrDH** [comment]
As it turned out, the `clone` config option prevented the API from being exposed to the DOM element (it actually got exposed to the original DOM element, not the clone), preventing the script in another menu from being able to close it.

I've fixed the issue and will publish a new version some time soon.
For now, I guess you can manually clone the menu(s) before firing the plugin, a short description of how to do so can be found here: http://mmenu.frebsite.nl/support/tips-and-tricks.html

**Comment by clarosa-garlock** [comment]
Thank you for the quick reply!  For now, I will continue to use version 4.7.5 until you release the fix.  I prefer the way you implement clone because you add the "mm-" prefix to all ID's.  I eagerly await the fix because there are some features in the 5.x version I'd like to use.  Thanks for an excellent menu system (and great documentation to go along with it)!
