### ISSUE TITLE
Problem with "zposition" using the option "next"

### ISSUE THREAD

**Issue by maofree** [BeSite/jQuery.mmenu#443]
Hi
I prefer to report here a problem that I get with mmenu on this site
http://www.saharizanzibar.net

all is ok using browsers from a pc, reducing their width
instead on my lg2 with chrome and android 5.0.1, the side menu is not present, it is shown only a white right side

I've seen that it is due from zposition using the option "next"
with the other two values all is ok, so with front and back there is any error and I can see all the voices and its background

I leave that option on the website to help you to fix this bug
when it is solve alert me

thanks

bye

**Comment by FrDH** [comment]
Does it make any difference what `position` is set? `"left"` or '"right"' both fail?

**Comment by maofree** [comment]
Hi
I tested using position on the left and I can see it, but there are some problems if I scroll in vertical
I can see the website under the menu. Probably there is some code that gives problems to the menu, like bootstrap
