### ISSUE TITLE
Search field searches only in <li> tag

### ISSUE THREAD

**Issue by yarons** [BeSite/jQuery.mmenu#447]
Hi guys,
I added a search field to the navbar, I wanted to ask if there's any way to customise the search function to make it search inside `<p>` tags (so I can also search in the titles)?

I think my request can be considered as a feature request.

Kind regards,
Yaron Shahrabani.

**Comment by FrDH** [comment]
Sort of, I guess... The searchfield searches every `A` and `SPAN` directly in a `LI` of a listview (mostly every `UL`). So if you put a `P` in a `SPAN` in a `LI` in an `UL`, the searchfield should find its content.

Could you show me what your HTML looks like? I'd like to see what you're trying to accomplish so I can think of a way to realize that.

**Comment by yarons** [comment]
Thank you for the quick reply and sorry for the delay.
Let me explain first: I want to have some metadata inside the menu header so at the top of the `LI` tag I added a `<p>` element and described the clicked item.

So it looks like this:

```html
      <nav id="menu">
         <ul>
            <li><a href="/">Instructions</a></li>
            <li><a href="#">Web server</a>
              <p>IP Address: 192.168.1.7</p>
              <p>Role:Proxy</p>
              <p>User:dev_user</p>
              <p>Password:P@$$w0rD</p>
               <ul>
                  <li><a href="/about/history">History</a></li>
                  <li><a href="/about/team">The team</a></li>
                  <li><a href="/about/address">Our address</a></li>
               </ul>
		</div>
            </li>
            <li><a href="/contact">Contact</a></li>
         </ul>
      </nav>
```

I don't care much about the username or the password so it would be the best if I'll just add `id="nosearch"` for example but I can live without this feature.

What I really need id the ability to search for the Role or IP Address (I'll probably have some more metadata, these 2 are just for the example).

Thank you!

**Comment by yarons** [comment]
I almost forgot, since I'm using the items counter for menu items I can't include the metadata in `LI` tags.

**Comment by yarons** [comment]
I opened a StackOverflow issue:

http://stackoverflow.com/questions/33215884/use-mmenu-as-an-item-listing-platform

Nobody answered yet.
