### ISSUE TITLE
Open/Close Button

### ISSUE THREAD

**Issue by alouellette** [BeSite/jQuery.mmenu#448]
When I click on the menu open button i does not move and continues to lay over the the top menu item. My close button never appears. Has anyone else had this problem?

Thanks
Amanda

**Comment by FrDH** [comment]
The plugin does not provide in an open- or close button, but I guess you could use the classname "mm-opened" that is added to the `HTML` to hide the menu button and show the close button.

If the button has `position: fixed;` try using the `fixedElements` add-on:
http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html
