### ISSUE TITLE
Second level of sliding menus don't render immediately when in standalone mode on iOS

### ISSUE THREAD

**Issue by kriskd** [BeSite/jQuery.mmenu#451]
Currently using version 4.7.5 of the plugin.

The menus work great with the exception of when the site is being run in standalone mode in iOS.  To achieve this I have the following in my `<head>`

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

Once the user adds the site to their home screen and then accesses it with the icon on the home screen, the site opens without an address bar and has move of a native look to it.  However, in this mode, when the user accessing the menus, the first level displays, but upon selecting an item to open the second level, the second level is empty.  If the panel is closed and reopened, the second level menu is there.  The same thing happens when accessing the third level menu.  Empty at first, reappears when closing the panel and opening.  I verified this issues goes away if I remove the meta tags above and recreate the home screen icon.  I created a home screen icon for the jQuery.mmenu demo site but the meta tags aren't being used because the site opens with an address bar from the home screen icon so I can't verify if this is an issue with the plugin or my implementation.

Any suggestions to solve this?

**Comment by FrDH** [comment]
Sounds odd, I'm not aware of any differences in standalone mode.
Is this issue also present in the latest version of the plugin?

**Comment by kriskd** [comment]
I rebased my branch where I started an upgrade to 5.x (I have other issues with 5.x I need to find time to chase down) and the issue is present in that version as well.

Of course it's possible the issue could be an issue with my code.  Could you verify it by adding the meta tags to the demo site and create a home screen icon?

**Comment by FrDH** [comment]
Does the issue present if you add one of the demo files to your homescreen?
