### ISSUE TITLE
Two visible levels

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#452]
Is it possible to have two visible levels at the same time?
Similar to what happens in Mac Os X finder explorer but with only two levels.

The 2nd one would be empty if nothing from the 1st level is selected.

![columnview](https://cloud.githubusercontent.com/assets/1706326/10667754/db0111e6-78d0-11e5-943d-e82fc96a2687.png)

**Comment by alvarotrigo** [comment]
I just realized it doesn't make sense. Not with this layout.

**Comment by FrDH** [comment]
FYI
I've been thinking about this behavior before, but couldn't find any proper usage for it and thus moved it down the roadmap.

**Comment by FrDH** [comment]
Good news, the next version will have a "columns" add-on included.

**Comment by alvarotrigo** [comment]
Great news!
