### ISSUE TITLE
Callbacks?

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#453]
Does the plugin include any callbacks? 
Something like `onClick` , `onFinishLoading` and so on would be very useful.

I'm thinking about loading submenus dynamically once the user clicks on an element. And right now I'm not quite sure if its possible at all. 
I didn't see anything in the docs besides the `onClick` option, which is just an option.

[I manged to find out something on stackoverflow referencing some undocumented callback](http://stackoverflow.com/questions/30559505/callback-event-when-jquery-mmenu-opened). But not sure if there's any more.

**Comment by FrDH** [comment]
You can always use jQuery to bind a new function to an onClick event.

Also, there's an API that provides methods you can call or bind new functions to:
http://mmenu.frebsite.nl/documentation/api.html

You can use the `update` method, have a look at the first comment in this topic:
https://github.com/BeSite/jQuery.mmenu/issues/57

**Comment by alvarotrigo** [comment]
> You can always use jQuery to bind a new function to an onClick event.

But how can you prevent the menu to move to the next submenu on click?
I've tried preventing and stopping the propagation in the `li` and the `a`  but it doesn't seem to be working.

**Comment by alvarotrigo** [comment]
How can we cancel the sliding of the list when clicking in one of its elements and activate it later one whenever we want (eg, when getting the data from the server side).

I've tried using `e.stopPropagation();` and then using a `trigger('click')` but it doesn't seem to be working.

**Comment by FrDH** [comment]
There's no cancelling or pausing the sliding of a list.
I created similar behavior before by loading for the submenu after clicking the item and opening the submenu afterwards.
Something like this (havent tested it, but the idea is pretty straight forward I think):
````html
<nav id="menu">
   <ul>
      <li><a href="#" class="has-submenu">Item 1</a></li>
      <li><a href="#">Item 2</a></li>
   </ul>
</nav>
````
````javascript
var $menu = $("#menu").mmenu();
var api = $menu.data( "mmenu" );

$menu.on( "click", "a.has-submenu", function() {
   var $a = $(this);

   $.ajax({
      // options to retrieve the submenu
   }).success(function( data ) {
      var $ul = $(html);
      $a.removeClass( "has-submenu" );
      $a.parent().append( $ul );
      api.init( $ul );
      api.openPanel( $ul );
   });
});
````
