### ISSUE TITLE
Re-initialize mmenu? Destroy + initialize ?

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#454]
Is there any way to update the current initialized plugin?
The `update` API function doesn't seem to work and its not generating the arrows for the submenus. 

Alternatively I was looking for a destroy function to initialize the plugin again, but I didn't find any one to do so either.

Isn't there any way to update the content of the plugin once initialized ?

**Comment by FrDH** [comment]
The `update` method should update the panel specified in the argument. Could you show me some code you've used?

There's no destroy function, that's just not possible. Alternatively, you could use the `clone` configuration option (or clone the menu manually). This way you can simply remove the cloned menu and re-create the menu from the original menu.

**Comment by alvarotrigo** [comment]
> The update method should update the panel specified in the argument

Which arguments has the update function? I can not see it [in the docs](http://mmenu.frebsite.nl/documentation/api.html).  I though it had none:

```javascript
var menu = $("#menu").mmenu(),
var menuInit = menu.data('mmenu');
menuInit.update();
```

**Comment by alvarotrigo** [comment]
Also, can we just pass to `init` a list of `li` instead o the whole list with the `ul` ? 

> The panel to close.

Not very clear what a "panel" is.

**Comment by alvarotrigo** [comment]
@FrDH here you have a reproduction using the `init` method. (the update doesn't do anything)

http://jsfiddle.net/yr993rwy/2/

**Comment by alvarotrigo** [comment]
A better example here: http://jsfiddle.net/yr993rwy/3/

**Comment by FrDH** [comment]
My bad, I was referring to the `init` method (I think it was `_init` in earlier stages), the `update` method only updates the already initialized menu.
You can not pass a list of `li`s to the `init` method, it expects a "panel" (either an `UL`, `OL` or a `DIV`).
I think you're getting an error because the `init` method expects a jQuery object, not a string.

**Comment by alvarotrigo** [comment]
@FrDH in the answer you linked you are using a string:

```
var new_content = '<li><a href="/">Home</a></li>';
$ul.append( new_content );
_menu._init( $ul );
```

I was not able to find any other example.

In any case, I've tried it with an object and [it doesn't work either](http://jsfiddle.net/yr993rwy/4/). I append the submenu when clicking on the first item.

**Comment by alvarotrigo** [comment]
I'll wait to see what you suggest or if you think it is even possible to load submenus dynamically. 
Meanwhile I'll try to find [other ways around by doing it by my own](http://jsfiddle.net/Ly7v3whf/4/).

**Comment by FrDH** [comment]
I guess that answer is a bit out of date, sorry about that.
I updated the fiddle and got it to work: http://jsfiddle.net/yr993rwy/5/

First change: When re-creating the menu, you should update the variable "menu" (or delegate the onClick event to the body, like I did)

Second change: after the plugin initializes the "panels", all ULs are wrapped in a DIV, this new DIV receives the ID ("panel1" in this case). Therefor adding the new LIs to "#panel1" actaully added the LIs to the DIV. I changed it to "#panel1 > ul".

**Comment by FrDH** [comment]
FYI: I've been thinking about creating a tutorial on dynamically loading submenus and will see if I can whip something up later on.

**Comment by alvarotrigo** [comment]
@FrDH I believe you didn't save the fiddle as that's the one I was working on and still not showing the submenu correctly once you click on "Demo1 > Submenu 15"

**Comment by alvarotrigo** [comment]
Just to point it out.
If the dynamic content loads before the animation finishes and therefore you all init before the animation ends, the animation will get interrupted and it won't look as nice.

I'm solving it by using a setTimeout with 400 milliseconds, which is the time the animation needs to finish.

[Reproduction of the issue](http://jsfiddle.net/yr993rwy/7/)

**Comment by lcars79** [comment]
I have test your code with the latest Version (5.5.3) but I think this doesn't work :-( I want dynamic load sub menus (ul list) and want re-init this part but this doesn't work. Can you give me a hint how I can implement this with the current version?

**Comment by FrDH** [comment]
In the next version, you can bind to the "panelOpened" callback:
````javascript
API.bind( "panelOpened", function( $panel ) {
    console.log( "this panels just finished opening:" )
    console.log( $panel );
});
````

**Comment by alvarotrigo** [comment]
Sounds great!
