### ISSUE TITLE
slide in menu not smooth

### ISSUE THREAD

**Issue by daver77** [BeSite/jQuery.mmenu#455]
Hi, we've been using mmenu for a while now for our mobile view. When clicking the hamburger icon the menu comes in okay but it's not a smooth transition, does anyone know why?

www.medicalprotection.org/uk

**Comment by FrDH** [comment]
Could be due to changes in the CSS engine made by the browser.
The animation is (or should be) forced into hardware acceleration due to a css-trick/-hack. If the browser no longer supports that trick/hack, the animation probably will be less smooth.
