### ISSUE TITLE
Title path 

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#458]
I didn't see any option for the title to become a path looking title.
Something like:

> Menu1 > Submenu 1.1 > Submenu 1.3

I was thinking about doing it by myself, but not sure if there's any function in mmenu which I can use to navigate directly to the given panel. 

I saw the `setSelected` [in the documentation](http://mmenu.frebsite.nl/documentation/api.html), but it is not very clear what it does and probably not easy to pass the whole `LI` destination element.

**Comment by FrDH** [comment]
Have a look at the navbars add-on and look for "breadcrumbs".

**Comment by FrDH** [comment]
Here's the example (hidden behind the "more examples" button):
http://mmenu.frebsite.nl/demo/index.html?demo=navbars-2

**Comment by alvarotrigo** [comment]
Thanks for the link to the example!
