### ISSUE TITLE
Menu shows immediately without animation

### ISSUE THREAD

**Issue by Sigizmund2012** [BeSite/jQuery.mmenu#460]
Hello! In my site http://kozharozha.ru/ when i clicking hamburger icon( it shows only in touch devices ) menu shows immediately without animation. Can you help me?

**Comment by FrDH** [comment]
Could you create an online example that works on desktop? Otherwise I can't do any debugging.
Just some pointers:
- make sure all HTML is wrapped in only one DIV
- set a background-color to the BODY

**Comment by Sigizmund2012** [comment]
I'm really sorry. I just install via bower this package https://github.com/jackncoke/jquery-mmenu and thinking that your plugin. With your distributive all works fine :)

**Comment by altinselimi** [comment]
I am having the same problem also. I've made sure the HTML is all wrapped in only one DIV and I've set a background-color to body but it stills opens without any animation whatsoever. I am using only a simple "lorem ipsum" paragraph as content, beneath which relies the nav element, and both of them are children of a simple div container.

What am I doing wrong?

**Comment by FrDH** [comment]
Please follow the [contribution guidelines](https://github.com/FrDH/jQuery.mmenu/blob/master/CONTRIBUTING.md), I can't do anything without a working example of the issue.
