### ISSUE TITLE
UMD version as 'main' in bower.json / package.json

### ISSUE THREAD

**Issue by krugar** [BeSite/jQuery.mmenu#461]
hey,

do you think it would be possible to change the bower.json and/or npm package.json 'main:' attributes to reference the UMD packaged release? i guess most people pulling in mmenu through one of the package managers would not mind (but it might still break some existing builds/workflows).

**Comment by FrDH** [comment]
As the script won't (or shouldn't) break without `define` or `require` (e.i. there's a fallback), I don't really see why not to use these files as the default.
I'll change this in the next version (and wait for comments... :) )
