### ISSUE TITLE
Add a class to act as menu status

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#462]
It would be nice to add a class in the plugin's DOM structure (or even in the `body`) that let us know in which panel the menu is.

As the plugin doesn't provide callbacks, at least this way we could use them to work under certain conditions based on their classes.

I'm currently using breadcrumbs to show the path in the title as [in this example](http://mmenu.frebsite.nl/demo/index.html?demo=navbars-2).
Ideally I could have something like `data-currentPanel="demo"` somewhere in the DOM, where `demo` could be the breadcrumb title.

If not with the title, it could be done in a more simple way by just specifying the depth of the submenu and the index of the selected item: `data-current-panel="3-4-2"` meaning you are in the 3rd submenu.
The 3rd element of the menu, the 4th of the 2nd and the 2nd of the 3rd menu.

**Comment by FrDH** [comment]
Not a 100% sure, but the current opened panel should be the only panel having the class "mm-current". Also, with a normal menu hierarchy, I think it's the only panel that has the class "mm-opened" without having the class "mm-subopened".

I don't think I'll implement this functionality in the core as I don't see any logical usage for it. But ofcourse you're free to create an add-on that adds the functionality and I'll be happy to add it to the "3rd party add-ons".

**Comment by alvarotrigo** [comment]
> Not a 100% sure, but the current opened panel should be the only panel having the class "mm-current".

That's not relevant. 

The idea could be consider as a breadcrumb for the developer. A way to know in which state the menu is. 
This way the developer will be able to fire actions or check conditions based on that.

For example:

```css
.body .members.active header{
    background:red;
}
```

Or even with javascript / jQuery (as mmenu doesn't provide callbacks)
```javascript
$(document).on('click', '.mm-next', function(){
    if(  $('body').hasClass('members inactive')){
        //whatever
    }
});
```

**Comment by alvarotrigo** [comment]
Although I understand it would require extra configuration to set up the names and so on and it might not be used by many people.

**Comment by FrDH** [comment]
I'll look into providing additional callbacks when animations finish.

For the "breadcrumbs for the developer" part, I guess you could have a look at the breadcrumbs for navbars, it demonstrates how you can "climb up" the node tree from any panel:
https://github.com/BeSite/jQuery.mmenu/blob/master/src/addons/js/jquery.mmenu.navbar.breadcrumbs.js

**Comment by FrDH** [comment]
For callbacks, you can bind a new function to the "openPanel" method using the API:
http://mmenu.frebsite.nl/documentation/api.html
````javascript
var $menu = $("#menu").mmenu();
var api = $menu.data( "mmenu" );

api.bind( "openPanel",  function( $panel ) {
   console.log( $panel );
});
````
In the next version, there will also be a "panelOpened", callback method available.
