### ISSUE TITLE
Page Convulses After Closing

### ISSUE THREAD

**Issue by DaveyJake** [BeSite/jQuery.mmenu#465]
I'm using the latest version of jQuery.mmenu with Foundation 5.5 (minus Zurb's off-canvas js). For some reason, once the menu is done closing, the page convulses (i.e. its width goes below 100% and then back) and then the ScrollTop() changes to a random value. Has anyone else encountered this issue? It's driving me nuts that I can't figure out why it's happening. Any advice would be much appreciated.

**Comment by DaveyJake** [comment]
After a few more hours of testing, it would appear that the issue stems from the page loading partially zoomed-in.  I've adjust the `html` and `body` to both have `width: 100%;` and `max-width: 100%;`. So far it looks like that has resolved the matter but still testing to see if that is really the issue.

**Comment by lissman** [comment]
Have the same problem on Safari and Chrome under iOS. `html` and `body` width manipulations doesn't help.

**Comment by jamiedavidreid** [comment]
removing 'maximum-scale=1.0' from the viewport meta worked for me on iOS.

changed
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
```
to
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
```

**Comment by DaveyJake** [comment]
Here are all the mods I've made so far to help resolve the issue.

A few things to note: When downloading your `Foundation` files, **you'll need to do a *Custom Download* because we need to remove the feature that `jQuery.MMenu` replaces.**

Underneath **JAVASCRIPT COMPONENTS** uncheck `Off Canvas`.  This will prevent any possibly conflicting scripts and styles from being included in your initial setup.

*After downloading your custom Foundation files, open your theme documents...*

Add the following lines (or make sure you already have them) in the appropriate files:

### header.php
```php
// Inside the <head> tag
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes"> // included for iOS 7 compatibility

// Inside the opening <body> tag
<div id="main-site-content" class="mm-slideout mm-offcanvas">
  <header class="hide-for-large-up site-header fixed">
    <section class="custom-hamburger left-small">
      <a href="#mobile-nav" id="mobile-tap" class="mobile-toggle hide-for-large-up">
        <span class="line line-1"></span>
        <span class="line line-2"></span>
        <span class="line line-3"></span>
      </a>
    </section>
  </header>
</div>
```

### foundation.css
```css
/* replace the rule block beginning on line 50 with the following: */
html,
body {
  height: auto;
  width: 100%;
  max-width: 100%;
  overflow-x: hidden !important;
  font-size: 100%; }
```

### jQuery.MMenu config
*These are usually put inside of your own custom JS file*
```js
jQuery(document).ready(function($){

  $("#mobile-nav").mmenu({
    "extensions": ["border-full","pageshadow","theme-dark","pagedim","effect-menu-slide"],
    openingInterval: 0,
    transitionDuration: 250,
    searchfield: true,
    panelNodeType: '#mobile-menu',
  },
  { classNames: {
      selected: "current-menu-item",
      fixedElements: {
        fixed: "fixed"
      }
    },
    offCanvas : {
      pageNodetype: 'div#main-site-content'
    }
  })
    .on( "opening.mm", function(e) {
      e.preventDefault();
    })
    .on( "closing.mm", function(e) {
      e.preventDefault();
    })
    .on( "closed.mm", function(e) {
      e.preventDefault();
    });

  $("#mobile-tap").click(function(e) {
    e.preventDefault();
    $("#mobile-nav").trigger("open.mm");
  });

});
