### ISSUE TITLE
Back button for full screen

### ISSUE THREAD

**Issue by alvarotrigo** [BeSite/jQuery.mmenu#468]
This might be a bit far for the plugin's purpose, but I personally would find a back button feature (and forward as well) very useful  when dealing with full screen menus like the one in [this example from the docs](http://mmenu.frebsite.nl/demo/index.html?demo=app-settings).

Using anchor links for it ('#') in the URL seems like the approach for it. 

And of course, it would be ideal if this could also be linked with the breadcrumb extension.

**Comment by FrDH** [comment]
There's a "back button" add-on that lets you click the browser back button to close the menu. Also, you can add a "close" button to the navbar that has the breadcrubs:
````javascript
$("#menu").mmenu({
    navbars: [{
        content: [ "breadcrumbs", "close" ]
    }]
});
````

Hope this helps.

**Comment by alvarotrigo** [comment]
I know it, but that's not a navigation feature. It just closes the menu rather than going back or forward on the menu navigation.
