### ISSUE TITLE
Document the development process in the main README

### ISSUE THREAD

**Issue by RaffaeleSgarro** [BeSite/jQuery.mmenu#469]
I am going to develop two features:

 - keyboard navigation with up and down arrow keys
 - deep search

I forked the repo but can't find any way to start a development environment. Any hint? There's a `Guardfile` but no documentation about how to run it, and there's no automatic testing framework used in the code.

**Comment by FrDH** [comment]
Good point. I'll see what I can do.

Basically here's what you need to do:
- Install the guard gem, the guard concat gem and the guard uglify gem.
- Install sass.
- run guard like this: `guard`.
- run sass like this: 'sass --watch src:dist'

**Comment by FrDH** [comment]
FYI, I moved from using Guard to Gulp as a tast runner.
