### ISSUE TITLE
Padding in slidingSubmenus

### ISSUE THREAD

**Issue by eddie1976** [BeSite/jQuery.mmenu#471]
![padding](https://cloud.githubusercontent.com/assets/8769955/11179362/c0e1e4fe-8c8d-11e5-8d1b-9231e033ba86.jpg)
Hi, I noticed that when slidingSubmenus is false, there's a padding (10px) in top and bottom. So in my screenshot, height of 'History' and 'Our address' look bigger than 'The team'. Is it by design? Because when there are only 2 items in sub menu, it looks quite strange.

**Comment by FrDH** [comment]
It's by design, without the padding it's less obvious you're in a submenu. If you want, you can override the CSS and remove the padding though.
