### ISSUE TITLE
Searchfield should search leaf nodes at any depth

### ISSUE THREAD

**Issue by RaffaeleSgarro** [BeSite/jQuery.mmenu#473]
When the menu is used to arrange commands in a tree, the search field should find matching nodes in any panel. Since the behavior is not backword compatible, it should be possible to opt-in. For example, given this navigation tree:

 - About
  - Contact
    - Send email
    - Chat

one should be able to find "Chat" without opening the "About" and "Contact" submenus

**Comment by FrDH** [comment]
So instead of filtering the list items in the actual panels, you'd open a "search results panel"? I like that idea and will see if I can get something like that to work without having to re-write the entire searchfield add-on.

**Comment by RaffaeleSgarro** [comment]
A search results panel is exactly what I intended and I can help with this if it would speed things up

**Comment by RaffaeleSgarro** [comment]
Can anybody point me to the right direction to develop this thing and contribute code back?

**Comment by FrDH** [comment]
This functionality will be available in the next version (5.6.0).

**Comment by RaffaeleSgarro** [comment]
Thanks Fred. Let me know if I can help

Il giorno dom 29 nov 2015 alle ore 20:30 Fred Heusschen <
notifications@github.com> ha scritto:

**Comment by FrDH** [comment]
FYI, this has been implemented in the `searchfield.resultsPanel` option:
http://mmenu.frebsite.nl/documentation/addons/searchfield.html
