### ISSUE TITLE
css translate transform for sliding of page is moving the entire page down?

### ISSUE THREAD

**Issue by propertunist** [BeSite/jQuery.mmenu#477]
initially i configured mmenu using the z-index directive:
```
               "offCanvas": {
                  "zposition": "front"
               },
```
all went well until i decided to activate the iconbar extension. i saw the warning about not using this extension with 'offCanvas' directives - so i disabled the offCanvas one. i then noticed that when the menu slides horizontally using a CSS translate transform, the whole page (except for the menu) is also moving down (vertically) about 1 text line in height. the result is that there is an empty space at the top of the page when the menu is being displayed (although the menu itself does render correctly).
this occurs whether i am using 'iconbar' or not.
i have looked through the CSS via the inspector in firefox and am not seeing any obvious cause for this. does anyone know one?!
(i am using firefox 42 on fedora)
thanks

**Comment by FrDH** [comment]
I'm not sure I understand. Whether or not you use the iconbar extension, the page moves down with the `position` and `zposition` options set to their defaults? (basically ,everything is default?)
I'm not seeing this behavior in any of the examples so there's not much I can do without an online example:
http://mmenu.frebsite.nl/demo/index.html?demo=default

**Comment by propertunist** [comment]
ok sure, you can see the situation on my test site here: http://test.ureka.org
as you can see, the page is moving down when it shouldn't. as far i can see, it is the translate CSS directive that is causing this, but i don't know why.

**Comment by FrDH** [comment]
This is caused by the `margin-top` on `DIV.elgg-page-header`, remove it (or add a 1px padding-top to one of its parents) and everything should be OK.

**Comment by propertunist** [comment]
aha! great, thanks - that resolved the issue.
