### ISSUE TITLE
Fix flickering if javascripts are at the end of the body

### ISSUE THREAD

**Issue by skfd** [BeSite/jQuery.mmenu#478]
Is there some workaround to fix menu flickering?

Every example load scripts in head of the page and it's fine. But if you load it at the end of the body it looks nasty.

Here is a [plunkr flicker example](http://plnkr.co/edit/JBvbjvuY6ihCLpnt7t3w?p=preview).

I tried making it hidden and showing only after initiating a plugin but it did not help.

Thanks!

**Comment by FrDH** [comment]
Try the "prevent F.O.U.C." tip:
http://mmenu.frebsite.nl/support/tips-and-tricks.html#tt-prevent-fouc
