### ISSUE TITLE
fixedElements are not really responsive

### ISSUE THREAD

**Issue by Patta** [BeSite/jQuery.mmenu#479]
i have an header (with inner mainmenu) element that position is relative on desktop width. on small screens the header position is fixed and the mmenu is used via menu icon. with fixedElements configuration for the header, the header get stuck on page bottom if the window size changed again to desktop width. removing the fixedElements class from header does not help. is there an workaround to fix an element on window resize, not only on pageload?

**Comment by FrDH** [comment]
The plugin places the element directly inside the `BODY`, out of the "page". This isn't restricted to a media query or something. You're probably best of using two versions of each element that should be fixed on mobile. Hide the one with the class "Fixed" on desktop and the other on mobile using a media query.

**Comment by Patta** [comment]
ok, thanks!
