### ISSUE TITLE
menu visible during slideout if page height is less than menu

### ISSUE THREAD

**Issue by mgarcos** [BeSite/jQuery.mmenu#480]
I found that if the height of the main page is shorter than the menu then the menu will be exposed early during the transition.  Here are a couple of screenshots to see the issue:

1)  hamburger was clicked and menu is opening.  menu is visible below the page and to the left of the page.  It should only be visible to the left of the page:
![opening 1](https://cloud.githubusercontent.com/assets/1790930/11377363/4becca34-929a-11e5-941c-5f8f729d333c.png)

2)  fully open menu looks fine:

![opening 2](https://cloud.githubusercontent.com/assets/1790930/11377380/59ed4bb8-929a-11e5-9ac8-8eaf5694b043.png)

**Comment by FrDH** [comment]
My guess is, the `DIV` has a 100% height, but has a transparent background.
Try setting a background-color on the `BODY`.
