### ISSUE TITLE
If a panel only contains .mm-hidden items there shouldn't be an .mm-next arrow

### ISSUE THREAD

**Issue by overtune** [BeSite/jQuery.mmenu#481]
Hi!

I have an implementation of mmenu for a website. In desktop-mode there is a dropdown-menu with both menu-items and information-text.
I use mmenu on that menu (with the clone-feature).
But on the mobil-menu I only want the menu-items and not the information texts. So I have added the class "mm-hidden" on the information texts div:s. This works good and they do not show up in the menu.
But, if I have an parent menu-item that only have an information test beneath it (and no "real" menu-links), that parent item gets an arrow, so it can expand the submenu. But the submenu is empty (beacuse it only contains on mm-hidden element).

The arrows should not be visible if a submenu only contains hidden elements.
Is there some way to do this?

**Comment by FrDH** [comment]
Adding the class "mm-hidden" is kinda reserved for the plugin itself. I think you're better off manually cloning the menu and removing the hidden `LI`s (and their parent `UL` if there's no `LI` left) before firing the plugin.

**Comment by overtune** [comment]
Ok! That might be a better solution. Thanks for the suggestion!
