### ISSUE TITLE
opening submenu using a span element has stopped working

### ISSUE THREAD

**Issue by propertunist** [BeSite/jQuery.mmenu#482]
i have almost finished configuring mmenu for my site and overall it is great, so thanks :)
the problem i have now is that after enabling and configuring the iconbar setup, i have found that the menu / list options that are in my menu which are intended to only act as a way to open a sub-menu and not to act as a link in their own right - have stopped working.

e.g. i have an option in the menu called 'library' which does not have a page of it's own and just opens up a submenu of different types of object in the library. this is represented by a span element in the menu, yet when i click it - nothing occurs.

this was working fine, but i have not been able to find the cause of it stopping working, despite undoing numerous changes i had recently been making.

the setup for mmenu is:
```
           $("#menu").mmenu({
               "extensions": [
                  "border-full",
                  "effect-menu-zoom",
                  "pagedim-black",
                  "multiline",
                  "iconbar",
                  nav_theme
               ],
               "autoHeight": true,
               "counters": true,
               "navbar": {
                  "title": "navigation"
               },
               "navbars": [
                  {
                     "position": "top",
                     "content": [
                        "prev",
                        "title",
                        "close"
                     ]
                 },
                 {
                     "position": "bottom",
                     "content": [
                        "<a class='' href='/about'>" + elgg.echo('ureka:about') + "</a>",
                        "<a class='' href='/terms'>" + elgg.echo('expages:terms') + "</a>",
                        "<a class='' href='/privacy'>" + elgg.echo('expages:privacy') + "</a>"
                     ]                     
                  }
               ]
            });
```
you can see the menu on the live site at www.ureka.org
anyone know why these options don't work?
thanks

**Comment by propertunist** [comment]
so i have created a workaround for this. since i needed to trigger the menu to open when such a span element is clicked, i wrote a query function that both opens the relevant subpanel and also opens the main menu:
```
          $('#menu .mm-listview > li > span').click(function(){
                var api = $("#menu").data( "mmenu" );
                var target = $(this).parent().children('a').data("target");
                $('.navControl a').trigger('click');
                api.openPanel($(target));
            });
```

**Comment by FrDH** [comment]
You've added this CSS that stops the anchor from being 100% wide:
````css
em.mm-counter + a.mm-next {
    width: 60px !important;
}
````

**Comment by propertunist** [comment]
i can see that removing that line from the css file does indeed then result in the sub-menu opening correctly when the parent menu option/span is clicked; though i have no idea why adding that width value is an issue, since the default value is 90px and i am just making it a bit smaller. the mm-next anchor doesn't reach 100% across the menu option anyway, with or without my amendment.
i just looked at removing the line you highlighted, but when i do that, the hover effect is broken (which is probably why i added it in the first place) in that the mm-next area and it's related menu option text don't fit together correctly and i end up with a clash of colour, since the background color i am using for a hover effect is semi-transparent.
maybe i'm just tired, but i'm not seeing the solution here, so i'll probably just keep the code as it is with my jquery workaround.

**Comment by FrDH** [comment]
The default value for small buttons on the right is 90px, the default value for large buttons covering the entire item is 100%.
Your CSS overrides both.
