### ISSUE TITLE
<header> moved

### ISSUE THREAD

**Issue by claudchan** [BeSite/jQuery.mmenu#483]
Hi,
Is there a way or option to prevent the ```<header>``` move out of the element?
I notice that when init mmenu, the content will wrapped by ```<div id="mm-0" class="mm-page mm-slideout">``` and the ```<header>``` is moved out of the wrap.

**Comment by FrDH** [comment]
The plugin needs to have one HTML node to be the "page" (in order for it to move out the page when showing the menu).
As suggested in the tutorial (http://mmenu.frebsite.nl/tutorials/basic/setting-up-the-html.html) you're best of wrapping all HTML into one node.
That way the plugin doesn't need to wrap anything.
