### ISSUE TITLE
Change content inside menu

### ISSUE THREAD

**Issue by ddialer** [BeSite/jQuery.mmenu#57]
Hi. I'm using this plugin for mobile application and mmenu used to display AJAX generated data that need to be updated on each menu open also Inside this menu there also sub-menu and when when user make changes on sub0menu I need to update parent menu also. Is there any way I can make it with mmenu?

**Comment by hypergreatthing** [comment]
This works but i have several problems:
I want to refresh the data stored in a menu.  When i execute a $ul.empty(); the back button to the previous menu disappears.  How should i handle this correctly?
Possibly related to the append, but the scroll bar that pops up for multiple elements seems to start at the very top instead of where the first li starts, thus hiding it.

**Comment by hypergreatthing** [comment]
Nevermind, i was able to manually put in the mm-subtitle line after the empty thus fixing the problem.

**Comment by CyberSolid** [comment]
Using MMenu v 5.0.4
I finally got this working and as I haven't found any (recent) example using ajax (HINT HINT), except for FrDH comment in this github which helped me a lot, I wanted to pitch in my 5 cts. 

function refresh_menu(){
    var $ul = $('#menu-right').find( "ul.mm-listview" );
    $.ajax({url: "get_menu.php", success: function(result){
        $ul.empty(); 
        $ul.append(result);
        mmr_api.init( $ul.parent() );
    }});
}

when I tried like the example FrDH, gave, it wouldn't load the data.
Then I tried adding the data to the renamed ul ( ul.mm-listview) and I could see the data appearing, but not correctly displayed, and when I initiated the menu, the data somehow dissappeared.
After lots of trial and error, I found that initializing the parent works.

Great Script!!! 

Although I widh it was more compatible with JQuery UI, I still love it.

Hope this helps a few wanderers out there.

**Comment by CyberSolid** [comment]
After a lot of trial and error I finally got a workaround for using ajax.
As I haven't found any example of using the menu with ajax (HINT HINT), except for FrDH's comment in this github which helped me a lot in the right direction, Here is my 5 cts for the community.

Some info : 
MMenu v 5.0.4
I have 2 menus ( left and right )
I only want the rightmenu to fill using ajax.
this function should work on a single menu as well (unconfirmed)

```javascript
var $menuright, mmr_api; // globally defined
```
(For people who checked out FrDH's example ) mmr-api = _menu

```javascript
			function refresh_menu(){
				var tempid = $('#menu-right').find('.mm-panel:first').attr('id');
				$('#menu-right').find('.mm-panel').each(function(i,panel) {
					$(panel).detach();
				});
				var temptext = "<div class=\"mm-panel mm-opened mm-current\"";
				if(typeof tempid !=="undefined"){
					 temptext += " id=\""+ tempid +"\" ";
				}
				temptext += "><div class=\"mm-noresultsmsg\">No results found.</div><ul class=\"mm-listview mm-first mm-last\"></ul></div>"

				$('#menu-right').append(temptext);

				var $ul = $('#menu-right').find( "ul.mm-listview:first" );

				$.ajax({url: "get_menu.php", success: function(result){
					mmr_api.update();
					$ul.html(result);
					mmr_api.init( $ul.parent() );
				}});
			}
```

when I tried like the example FrDH gave, it wouldn't load the data. (in this version)
Then I tried adding the data to the renamed ul ( ul.mm-listview) and I could see the data appearing, but not correctly displayed, and when I initiated the menu, the data somehow dissappeared.
After lots of trial and error, I found that initializing the parent works, but when refreshing the menu, it breaks.

I finally got by this, by emptying the menu, the only problem I encounter with this, is that listcounters do not reset, so the items of the new menu continue counting. I even tried adding a 
ie : in the first refresh elements get the ids "mm-5" etc. (it starts at 5 as I have another fixed menu on the left), and the second refresh the ids will be "mm-203" ( as it is a long list aparantly )

This might cause an exception on the long term if the menu is refreshed a lot and if page doesn't reload. ( unconfirmed )

<B>How can I reset the counters (or recount all mm-panels) and then reinitialize the mmenu?</B>

Great Script!!!
I hope future versions will support Ajax better and that it will more compatible with the (latest)  JQuery UI Themeroller, to be able to use dynamic themes.

Hope this helps a few people out there, and I hope someone can help me with the counter reset.

**Comment by CyberSolid** [comment]
After a lot of trial and error I finally got a workaround for using ajax.
As I haven't found any example or documentation of using the menu with ajax (!!! HINT HINT !!!). 
FrDH's comment in this github didn't work for my situation, but it helped me a lot in the right direction, Here is my 5 cts for the community.

Some info : 
MMenu v 5.0.4
I have 2 menus ( left and right ) and I only want the rightmenu to fill using ajax.

get_menu.php generates the html :
```html
<LI><SPAN> SOME MENU ITEM</SPAN>
	<UL>
		<LI><SPAN> SOME SUBMENU ITEM</SPAN>
			<UL>
				<LI><A HREF="somelink"> SOME SUBSUBMENU ITEM WITH LINK</A></SPAN>
				
				...........ETC

				</LI>
			</UL>
		</LI>
	</UL>
</LI>
```

globalvars :
```javascript
var $menu; // globally defined for generate_menu
```

function call in this example: 
```javascript
	refresh_menu($('#menu-right'));
```


The generate_menu function is used to initiate the mmenu :

```javascript
$menu = $('nav#menu-right').mmenu({/*lots of options*/});
```

```javascript
			function refresh_menu(menu){
				var id = menu.attr('id');
				menu.remove()
			
				$('body').append("<nav id=\"" + id + "\"><ul></ul></nav>");

				$ul = $('body').find('#' + id + " ul")

				$.ajax({url: "get_menu.php", success: function(result){
					$ul.html(result);
					generate_menu();
				}});
			}
```

when I tried the solution FrDH gave, it wouldn't load the data. (version differernce ?)
Then I tried adding the data to the renamed ul ( ul.mm-listview) and I could see the data appearing, but not correctly displayed, and when I initiated the menu, the data somehow dissappeared.
After lots of trial and error, I found that initializing the parent works the first time, but when refreshing the menu, it breaks.

I finally got by this, by removing the menu completely, and reconfiguring the menu. 
The only problem I encounter with this, is that listcounters do not reset, so the items of the new menu continue counting. 
ie : in the first refresh elements get the ids "mm-5" etc. (it starts at 5 as I have another fixed menu on the left), and the second refresh the ids will be "mm-203" ( as it is a long list )

I even tried adding an element with the "mm-5" id to see if the plugin did something like : number = $( "div.mm-panel" ).length; to calculate the number, but it seems it is running an internal counter.

This might cause an exception on the long term if the menu is refreshed a lot and if page doesn't reload. ( unconfirmed )

<B>How can I reset the counters (or recount all mm-panels) and then reinitialize the mmenu?</B>

Great Script!!!
I hope future versions will support Ajax better and that it will more compatible with the (latest)  JQuery UI Themeroller, to be able to use dynamic themes.

Hope this helps a few people out there, and I hope someone can help me with the counter reset.

**Comment by FrDH** [comment]
A tutorial about adding (and maybe changing and removing) content inside the menu is on the TODO list :)

**Comment by FrDH** [comment]
Try the `update` method in the API
http://mmenu.frebsite.nl/documentation/api.html

````javascript
var api = $("#my-menu").data( "mmenu" );
api.update();
````

That should update everything that needs to be updated after changes have been made (either manually or by an add-on).

**Comment by CyberSolid** [comment]
Hi Fred,

Thank you for the solution, unfortunately it doesn't update the numbering :(

I tried this, changing the function to : 

```javascript
			function refresh_menu(menu){
				var id = menu.attr('id');
				var api = $("#" + id).data( "mmenu" );
				menu.remove()
				api.update();
				$('body').append("<nav id=\"" + id + "\"><ul></ul></nav>");

				$ul = $('body').find('#' + id + " ul")
				api.update();
				$.ajax({url: "get_menu.php", success: function(result){
					$ul.html(result);
					api.update();
					generate_rightmenu();
					api.update();
				}});
			}
```

So I tried updating in multiple locations during the generation of the menu ( I also tried them one by one ) but to no effect. The counter still adds up every time I "refresh" the menu. ( as described above )

I did however found a solution for one of the problems that I mailed you about ( to which I still haven't received an answer ) It's about the searchfield plugin not perserving links when searching. I solved this by editting the mmenu source and disabling the addclass fullsubopen : (in the minified version) /*.addClass(t.fullsubopen)*/

Maybe it is an idea to add an extra option to mmenu source to provide this functionality (?)

I hope to still get an answer to the email as there are several issues I commented on in the mail.

**Comment by kriskd** [comment]
Should the update method also take care of updating portions of the menu inserted via ajax for version 5.2.0?  My issue is either the entire contents of the panel disappear or the menu comes in, but unstyled/plugin not applied.

**Comment by FrDH** [comment]
All newly added content should be initialized with the `init` method, this adds classnames, rearranges the markup, etc.
````javascript
var $menu = $("#menu").mmenu(),
    api = $menu.data( "mmenu" );

$("#button").click(function() {
    var $ul = $menu.find( "#panel" );
    var new_content = '<li><a href="/">Home</a></li>';
    $ul.append( new_content );
    api.init( $ul );
});
````
